// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "../context";
import { Binding } from "./binding";
import { Connection } from "../connection/connection";
import { McpApprovalMode } from "./mcp-approval-mode";
import { Property } from "../core/property";

export abstract class Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  name: string = "";
  kind: string = "";
  description?: string | undefined;
  bindings?: Binding[] = [];

  constructor(init?: Partial<Tool>) {
    this.name = init?.name ?? "";
    this.kind = init?.kind ?? "";
    if (init?.description !== undefined) {
      this.description = init.description;
    }
    this.bindings = init?.bindings ?? [];
  }

  //#region Load Methods

  static load(data: Record<string, unknown>, context?: LoadContext): Tool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    // Load polymorphic Tool instance
    const instance = Tool.loadKind(data, context);

    if (data["name"] !== undefined && data["name"] !== null) {
      instance.name = String(data["name"]);
    }
    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["description"] !== undefined && data["description"] !== null) {
      instance.description = String(data["description"]);
    }
    if (data["bindings"] !== undefined && data["bindings"] !== null) {
      instance.bindings = Tool.loadBindings(
        data["bindings"] as unknown[],
        context.at("bindings"),
      );
    }

    if (context) {
      return context.processOutput(instance) as Tool;
    }
    return instance;
  }

  private static loadKind(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): Tool {
    const discriminatorValue = data["kind"];
    if (discriminatorValue !== undefined && discriminatorValue !== null) {
      const discriminator = String(discriminatorValue);
      switch (discriminator) {
        case "function":
          return FunctionTool.load(data, context);
        case "mcp":
          return McpTool.load(data, context);
        case "openapi":
          return OpenApiTool.load(data, context);
        case "prompty":
          return PromptyTool.load(data, context);
        default:
          return CustomTool.load(data, context);
      }
    }
    throw new Error("Missing Tool discriminator property: 'kind'");
  }

  static loadBindings(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): Binding[] {
    context ??= new LoadContext({ path: "bindings" });
    if (!Array.isArray(data)) {
      const result: Binding[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (Array.isArray(v)) {
          throw new TypeError(
            context.at(k).path +
              ": invalid named collection entry category array",
          );
        }
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push(
            Binding.load(
              { name: k, ...(v as Record<string, unknown>) },
              context.at(k),
            ),
          );
        } else {
          result.push(Binding.load({ name: k, input: v }, context.at(k)));
        }
      }
      return result;
    }
    return data.map((item, index) =>
      Binding.load(item as Record<string, unknown>, context.atIndex(index)),
    );
  }

  static saveBindings(
    items: Binding[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    const serialized = items.map(
      (item) => ({ ...item.save(context) }) as Record<string, unknown>,
    );
    for (const itemData of serialized) {
      if (itemData["name"] === "") delete itemData["name"];
    }

    if (context.collectionFormat === "array") {
      return serialized;
    }

    const names = new Set<string>();
    for (const itemData of serialized) {
      const name = itemData["name"];
      if (typeof name !== "string" || name.length === 0 || names.has(name))
        return serialized;
      names.add(name);
    }

    // Object format: use name as key
    const result: Record<string, unknown> = {};
    for (let index = 0; index < items.length; index++) {
      const item = items[index];
      const itemData = serialized[index];
      const name = itemData["name"] as string;
      delete itemData["name"];
      // Check if we can use shorthand (only primary property set)
      const shorthand = (item.constructor as typeof Binding).shorthandProperty;
      if (
        context.useShorthand &&
        shorthand &&
        Object.keys(itemData).length === 1 &&
        shorthand in itemData
      ) {
        result[name] = itemData[shorthand];
        continue;
      }
      result[name] = itemData;
    }
    return result;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    const result: Record<string, unknown> = {};

    if (obj.name !== undefined && obj.name !== null) {
      result["name"] = obj.name;
    }
    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.description !== undefined && obj.description !== null) {
      result["description"] = obj.description;
    }
    if (obj.bindings !== undefined && obj.bindings !== null) {
      result["bindings"] = Tool.saveBindings(obj.bindings, context);
    }

    if (context) {
      return context.processDict(result);
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): Tool {
    const data = JSON.parse(json);
    return Tool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): Tool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return Tool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

export class FunctionTool extends Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  kind: string = "function";
  parameters: Property[] = [];
  strict?: boolean | undefined;

  constructor(init?: Partial<FunctionTool>) {
    super(init);
    this.kind = init?.kind ?? "function";
    this.parameters = init?.parameters ?? [];
    if (init?.strict !== undefined) {
      this.strict = init.strict;
    }
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): FunctionTool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    const instance = new FunctionTool();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["parameters"] !== undefined && data["parameters"] !== null) {
      instance.parameters = FunctionTool.loadParameters(
        data["parameters"] as unknown[],
        context.at("parameters"),
      );
    }
    if (data["strict"] !== undefined && data["strict"] !== null) {
      instance.strict = Boolean(data["strict"]);
    }

    if (context) {
      return context.processOutput(instance) as FunctionTool;
    }
    return instance;
  }

  static loadParameters(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): Property[] {
    context ??= new LoadContext({ path: "parameters" });
    if (!Array.isArray(data)) {
      const result: Property[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (Array.isArray(v)) {
          throw new TypeError(
            context.at(k).path +
              ": invalid named collection entry category array",
          );
        }
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push(
            Property.load(
              { name: k, ...(v as Record<string, unknown>) },
              context.at(k),
            ),
          );
        } else {
          let shorthand: Record<string, unknown>;
          if (typeof v === "number" && Number.isInteger(v)) {
            shorthand = { kind: "integer", default: v };
          } else if (typeof v === "number") {
            shorthand = { kind: "float", default: v };
          } else if (typeof v === "string") {
            shorthand = { kind: "string", default: v };
          } else if (typeof v === "boolean") {
            shorthand = { kind: "boolean", default: v };
          } else {
            shorthand = { default: v };
          }
          result.push(Property.load({ name: k, ...shorthand }, context.at(k)));
        }
      }
      return result;
    }
    return data.map((item, index) =>
      Property.load(item as Record<string, unknown>, context.atIndex(index)),
    );
  }

  static saveParameters(
    items: Property[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    const serialized = items.map(
      (item) => ({ ...item.save(context) }) as Record<string, unknown>,
    );
    for (const itemData of serialized) {
      if (itemData["name"] === "") delete itemData["name"];
    }

    if (context.collectionFormat === "array") {
      return serialized;
    }

    const names = new Set<string>();
    for (const itemData of serialized) {
      const name = itemData["name"];
      if (typeof name !== "string" || name.length === 0 || names.has(name))
        return serialized;
      names.add(name);
    }

    // Object format: use name as key
    const result: Record<string, unknown> = {};
    for (let index = 0; index < items.length; index++) {
      const item = items[index];
      const itemData = serialized[index];
      const name = itemData["name"] as string;
      delete itemData["name"];
      // Check if we can use shorthand (only primary property set)
      const shorthand = (item.constructor as typeof Property).shorthandProperty;
      if (
        context.useShorthand &&
        shorthand &&
        Object.keys(itemData).length === 1 &&
        shorthand in itemData
      ) {
        result[name] = itemData[shorthand];
        continue;
      }
      result[name] = itemData;
    }
    return result;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.parameters !== undefined && obj.parameters !== null) {
      result["parameters"] = FunctionTool.saveParameters(
        obj.parameters,
        context,
      );
    }
    if (obj.strict !== undefined && obj.strict !== null) {
      result["strict"] = obj.strict;
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): FunctionTool {
    const data = JSON.parse(json);
    return FunctionTool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): FunctionTool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return FunctionTool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

export class CustomTool extends Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  kind: string = "*";
  connection!: Connection;
  options: Record<string, unknown> = {};

  constructor(init?: Partial<CustomTool>) {
    super(init);
    this.kind = init?.kind ?? "*";
    if (init?.connection !== undefined) {
      this.connection = init.connection;
    }
    this.options = init?.options ?? {};
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): CustomTool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    if (
      typeof data["kind"] === "string" &&
      data["kind"] !== "" &&
      (data["connection"] === undefined || data["connection"] === null)
    ) {
      throw new Error(
        `${context.at("connection").path}: missing required field`,
      );
    }
    const instance = new CustomTool();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["connection"] !== undefined && data["connection"] !== null) {
      instance.connection = Connection.load(
        data["connection"] as Record<string, unknown>,
        context.at("connection"),
      );
    }
    if (data["options"] !== undefined && data["options"] !== null) {
      instance.options = data["options"] as Record<string, unknown>;
    }

    if (context) {
      return context.processOutput(instance) as CustomTool;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.connection !== undefined && obj.connection !== null) {
      result["connection"] = obj.connection.save(context);
    }
    if (obj.options !== undefined && obj.options !== null) {
      result["options"] = obj.options;
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): CustomTool {
    const data = JSON.parse(json);
    return CustomTool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): CustomTool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return CustomTool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

export class McpTool extends Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  kind: string = "mcp";
  connection!: Connection;
  serverName: string = "";
  serverDescription?: string | undefined;
  approvalMode?: McpApprovalMode | undefined;
  allowedTools?: string[];

  constructor(init?: Partial<McpTool>) {
    super(init);
    this.kind = init?.kind ?? "mcp";
    if (init?.connection !== undefined) {
      this.connection = init.connection;
    }
    this.serverName = init?.serverName ?? "";
    if (init?.serverDescription !== undefined) {
      this.serverDescription = init.serverDescription;
    }
    if (init?.approvalMode !== undefined) {
      this.approvalMode = init.approvalMode;
    }
    if (init?.allowedTools !== undefined) {
      this.allowedTools = init.allowedTools;
    }
  }

  //#region Load Methods

  static load(data: Record<string, unknown>, context?: LoadContext): McpTool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    if (data["connection"] === undefined || data["connection"] === null) {
      throw new Error(
        `${context.at("connection").path}: missing required field`,
      );
    }
    const instance = new McpTool();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["connection"] !== undefined && data["connection"] !== null) {
      instance.connection = Connection.load(
        data["connection"] as Record<string, unknown>,
        context.at("connection"),
      );
    }
    if (data["serverName"] !== undefined && data["serverName"] !== null) {
      instance.serverName = String(data["serverName"]);
    }
    if (
      data["serverDescription"] !== undefined &&
      data["serverDescription"] !== null
    ) {
      instance.serverDescription = String(data["serverDescription"]);
    }
    if (data["approvalMode"] !== undefined && data["approvalMode"] !== null) {
      instance.approvalMode = McpApprovalMode.load(
        data["approvalMode"] as Record<string, unknown>,
        context.at("approvalMode"),
      );
    }
    if (data["allowedTools"] !== undefined && data["allowedTools"] !== null) {
      instance.allowedTools = (data["allowedTools"] as unknown[]).map((v) =>
        String(v),
      );
    }

    if (context) {
      return context.processOutput(instance) as McpTool;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.connection !== undefined && obj.connection !== null) {
      result["connection"] = obj.connection.save(context);
    }
    if (obj.serverName !== undefined && obj.serverName !== null) {
      result["serverName"] = obj.serverName;
    }
    if (obj.serverDescription !== undefined && obj.serverDescription !== null) {
      result["serverDescription"] = obj.serverDescription;
    }
    if (obj.approvalMode !== undefined && obj.approvalMode !== null) {
      result["approvalMode"] = obj.approvalMode.save(context);
    }
    if (obj.allowedTools !== undefined && obj.allowedTools !== null) {
      result["allowedTools"] = obj.allowedTools;
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): McpTool {
    const data = JSON.parse(json);
    return McpTool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): McpTool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return McpTool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

export class OpenApiTool extends Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  kind: string = "openapi";
  connection!: Connection;
  specification: string = "";

  constructor(init?: Partial<OpenApiTool>) {
    super(init);
    this.kind = init?.kind ?? "openapi";
    if (init?.connection !== undefined) {
      this.connection = init.connection;
    }
    this.specification = init?.specification ?? "";
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): OpenApiTool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    if (data["connection"] === undefined || data["connection"] === null) {
      throw new Error(
        `${context.at("connection").path}: missing required field`,
      );
    }
    const instance = new OpenApiTool();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["connection"] !== undefined && data["connection"] !== null) {
      instance.connection = Connection.load(
        data["connection"] as Record<string, unknown>,
        context.at("connection"),
      );
    }
    if (data["specification"] !== undefined && data["specification"] !== null) {
      instance.specification = String(data["specification"]);
    }

    if (context) {
      return context.processOutput(instance) as OpenApiTool;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.connection !== undefined && obj.connection !== null) {
      result["connection"] = obj.connection.save(context);
    }
    if (obj.specification !== undefined && obj.specification !== null) {
      result["specification"] = obj.specification;
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): OpenApiTool {
    const data = JSON.parse(json);
    return OpenApiTool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): OpenApiTool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return OpenApiTool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

export class PromptyTool extends Tool {
  static readonly shorthandProperty: string | undefined = undefined;

  kind: string = "prompty";
  path: string = "";
  mode: string = "single";

  constructor(init?: Partial<PromptyTool>) {
    super(init);
    this.kind = init?.kind ?? "prompty";
    this.path = init?.path ?? "";
    this.mode = init?.mode ?? "single";
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): PromptyTool {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    const instance = new PromptyTool();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }
    if (data["path"] !== undefined && data["path"] !== null) {
      instance.path = String(data["path"]);
    }
    if (data["mode"] !== undefined && data["mode"] !== null) {
      instance.mode = String(data["mode"]);
    }

    if (context) {
      return context.processOutput(instance) as PromptyTool;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }
    if (obj.path !== undefined && obj.path !== null) {
      result["path"] = obj.path;
    }
    if (obj.mode !== undefined && obj.mode !== null) {
      result["mode"] = obj.mode;
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): PromptyTool {
    const data = JSON.parse(json);
    return PromptyTool.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): PromptyTool {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return PromptyTool.load(data as Record<string, unknown>, context);
  }

  //#endregion
}
