// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use super::super::context::{LoadContext, SaveContext};

use super::memory_category::MemoryCategory;

/// A single agent memory. The canonical, host-neutral unit of agent memory. `content` is the memory text; `category` classifies it; `createdAt`, `tags`, and `importance` are intrinsic scoring inputs consumed by deterministic recall. Any host-specific bookkeeping (source, session association, application taxonomy, a stored embedding vector for host-side vector recall, or a stable per-entry identifier) lives in `metadata`, never as a canonical field.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MemoryEntry {
    /// The memory content
    pub content: String,
    /// The classification of the memory
    pub category: MemoryCategory,
    /// ISO 8601 UTC timestamp when the memory was created; consumed as a recency input by recall
    pub created_at: Option<String>,
    /// General labels for the memory; consumed as keyword inputs by recall
    pub tags: Option<Vec<String>>,
    /// Optional salience weight in the range 0..1; consumed as a ranking input by recall
    pub importance: Option<f32>,
    /// Opaque host-specific memory metadata (e.g. source, session association, raw application taxonomy, stable per-entry id, or a stored embedding vector for host-side vector recall)
    pub metadata: serde_json::Value,
}

impl MemoryEntry {
    /// Create a new MemoryEntry with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load MemoryEntry from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MemoryEntry from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MemoryEntry from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        Self {
            content: value
                .get("content")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            category: value
                .get("category")
                .filter(|v| v.is_object() || v.is_array() || v.is_string())
                .map(|v| MemoryCategory::load_from_value(v, ctx))
                .unwrap_or_default(),
            created_at: value
                .get("createdAt")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            tags: value.get("tags").and_then(|v| v.as_array()).map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(|s| s.to_string()))
                    .collect()
            }),
            importance: value
                .get("importance")
                .and_then(|v| v.as_f64())
                .map(|v| v as f32),
            metadata: value
                .get("metadata")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        }
    }

    /// Serialize MemoryEntry to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if !self.content.is_empty() {
            result.insert(
                "content".to_string(),
                serde_json::Value::String(self.content.clone()),
            );
        }
        {
            let nested = self.category.to_value(ctx);
            if !nested.is_null() {
                result.insert("category".to_string(), nested);
            }
        }
        if let Some(ref val) = self.created_at {
            result.insert(
                "createdAt".to_string(),
                serde_json::Value::String(val.clone()),
            );
        }
        if let Some(ref items) = self.tags {
            result.insert(
                "tags".to_string(),
                serde_json::to_value(items).unwrap_or(serde_json::Value::Null),
            );
        }
        if let Some(val) = self.importance {
            result.insert(
                "importance".to_string(),
                serde_json::Number::from_f64(val as f64)
                    .map(serde_json::Value::Number)
                    .unwrap_or(serde_json::Value::Null),
            );
        }
        if !self.metadata.is_null() {
            result.insert("metadata".to_string(), self.metadata.clone());
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize MemoryEntry to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize MemoryEntry to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_metadata_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.metadata.as_object()
    }
}

// Serde for `MemoryEntry` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
impl serde::Serialize for MemoryEntry {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

impl<'de> serde::Deserialize<'de> for MemoryEntry {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
