// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use super::super::context::{LoadContext, SaveContext};

use super::memory_entry::MemoryEntry;

/// A whole-store snapshot of agent memory. The canonical persisted shape a host loads and saves as one unit. A host backend implements only load/save of this snapshot; the engine owns the deterministic recall, formatting, and entry-mutation logic on top of it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MemoryStore {
    /// The memories held in the store, in insertion order
    pub entries: Vec<MemoryEntry>,
    /// Opaque host-specific store metadata
    pub metadata: serde_json::Value,
}

impl MemoryStore {
    /// Create a new MemoryStore with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load MemoryStore from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MemoryStore from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load MemoryStore from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        Self {
            entries: value
                .get("entries")
                .map(|v| Self::load_entries(v, ctx))
                .unwrap_or_default(),
            metadata: value
                .get("metadata")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        }
    }

    /// Serialize MemoryStore to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if !self.entries.is_empty() {
            result.insert(
                "entries".to_string(),
                Self::save_entries(&self.entries, ctx),
            );
        }
        if !self.metadata.is_null() {
            result.insert("metadata".to_string(), self.metadata.clone());
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize MemoryStore to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize MemoryStore to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_metadata_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.metadata.as_object()
    }

    /// Load a collection of MemoryEntry from a JSON value.
    /// Handles both array format `[{...}]`.
    fn load_entries(data: &serde_json::Value, ctx: &LoadContext) -> Vec<MemoryEntry> {
        match data {
            serde_json::Value::Array(arr) => arr
                .iter()
                .map(|v| MemoryEntry::load_from_value(v, ctx))
                .collect(),

            _ => Vec::new(),
        }
    }

    /// Save a collection of MemoryEntry to a JSON value.
    fn save_entries(items: &[MemoryEntry], ctx: &SaveContext) -> serde_json::Value {
        serde_json::Value::Array(
            items
                .iter()
                .map(|item| item.to_value(ctx))
                .collect::<Vec<_>>(),
        )
    }
}

// Serde for `MemoryStore` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
impl serde::Serialize for MemoryStore {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

impl<'de> serde::Deserialize<'de> for MemoryStore {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
