// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// Configuration for context window compaction. When the message history exceeds the context budget, the compaction strategy is applied to reduce the message list while preserving essential information.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct CompactionConfig {
    /// The compaction strategy identifier. Built-in strategies include 'summarize'. Can also be a path to a .prompty file used as the summarization prompt.
    pub strategy: Option<String>,
    /// Character budget for the compacted context. Overrides TurnOptions.contextBudget when set.
    pub budget: Option<i32>,
    /// Additional strategy-specific options
    pub options: serde_json::Value,
}

impl CompactionConfig {
    /// Create a new CompactionConfig with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_options_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.options.as_object()
    }
}
