// <auto-generated by typra-emitter>
// <auto-generated/>
// Code generated by Typra emitter; DO NOT EDIT.

using System;
using System.Text.Json.Serialization;

namespace Prompty.Core;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RunTurnStatus
{
    [JsonPropertyName("success")]
    Success,

    [JsonPropertyName("error")]
    Error,

    [JsonPropertyName("cancelled")]
    Cancelled,

}

public static class RunTurnStatusParser
{
    public static RunTurnStatus Parse(string value)
    {
        return value switch
        {
            "success" => RunTurnStatus.Success,
            "error" => RunTurnStatus.Error,
            "cancelled" => RunTurnStatus.Cancelled,
            _ => Enum.Parse<RunTurnStatus>(value, true),
        };
    }

    public static string ToValue(RunTurnStatus value)
    {
        return value switch
        {
            RunTurnStatus.Success => "success",
            RunTurnStatus.Error => "error",
            RunTurnStatus.Cancelled => "cancelled",
            _ => value.ToString().ToLowerInvariant(),
        };
    }
}
