// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// A project hosted by an AI service resource.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProjectInfo {
    /// Provider project name
    pub name: String,
    /// Human-readable project name
    pub display_name: String,
    /// Project-scoped inference endpoint
    pub endpoint: String,
}

impl ProjectInfo {
    /// Create a new ProjectInfo with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }
}
