// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestFoundryConnectionLoadJSON tests loading FoundryConnection from JSON
func TestFoundryConnectionLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "foundry",
  "endpoint": "https://myresource.services.ai.azure.com/api/projects/myproject",
  "name": "my-openai-connection",
  "connectionType": "model"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFoundryConnection(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FoundryConnection: %v", err)
	}
	if instance.Kind != "foundry" {
		t.Errorf(`Expected Kind to be "foundry", got %v`, instance.Kind)
	}
	if instance.Endpoint != "https://myresource.services.ai.azure.com/api/projects/myproject" {
		t.Errorf(`Expected Endpoint to be "https://myresource.services.ai.azure.com/api/projects/myproject", got %v`, instance.Endpoint)
	}
	if instance.Name == nil || *instance.Name != "my-openai-connection" {
		t.Errorf(`Expected Name to be "my-openai-connection", got %v`, instance.Name)
	}
	if instance.ConnectionType == nil || *instance.ConnectionType != "model" {
		t.Errorf(`Expected ConnectionType to be "model", got %v`, instance.ConnectionType)
	}
}

// TestFoundryConnectionLoadYAML tests loading FoundryConnection from YAML
func TestFoundryConnectionLoadYAML(t *testing.T) {
	yamlData := `
kind: foundry
endpoint: "https://myresource.services.ai.azure.com/api/projects/myproject"
name: my-openai-connection
connectionType: model

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFoundryConnection(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FoundryConnection: %v", err)
	}
	if instance.Kind != "foundry" {
		t.Errorf(`Expected Kind to be "foundry", got %v`, instance.Kind)
	}
	if instance.Endpoint != "https://myresource.services.ai.azure.com/api/projects/myproject" {
		t.Errorf(`Expected Endpoint to be "https://myresource.services.ai.azure.com/api/projects/myproject", got %v`, instance.Endpoint)
	}
	if instance.Name == nil || *instance.Name != "my-openai-connection" {
		t.Errorf(`Expected Name to be "my-openai-connection", got %v`, instance.Name)
	}
	if instance.ConnectionType == nil || *instance.ConnectionType != "model" {
		t.Errorf(`Expected ConnectionType to be "model", got %v`, instance.ConnectionType)
	}
}

// TestFoundryConnectionRoundtrip tests load -> save -> load produces equivalent data
func TestFoundryConnectionRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "foundry",
  "endpoint": "https://myresource.services.ai.azure.com/api/projects/myproject",
  "name": "my-openai-connection",
  "connectionType": "model"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFoundryConnection(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load FoundryConnection: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadFoundryConnection(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload FoundryConnection: %v", err)
	}
	if reloaded.Kind != "foundry" {
		t.Errorf(`Expected Kind to be "foundry", got %v`, reloaded.Kind)
	}
	if reloaded.Endpoint != "https://myresource.services.ai.azure.com/api/projects/myproject" {
		t.Errorf(`Expected Endpoint to be "https://myresource.services.ai.azure.com/api/projects/myproject", got %v`, reloaded.Endpoint)
	}
	if reloaded.Name == nil || *reloaded.Name != "my-openai-connection" {
		t.Errorf(`Expected Name to be "my-openai-connection", got %v`, reloaded.Name)
	}
	if reloaded.ConnectionType == nil || *reloaded.ConnectionType != "model" {
		t.Errorf(`Expected ConnectionType to be "model", got %v`, reloaded.ConnectionType)
	}
}

// TestFoundryConnectionToJSON tests that ToJSON produces valid JSON
func TestFoundryConnectionToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "foundry",
  "endpoint": "https://myresource.services.ai.azure.com/api/projects/myproject",
  "name": "my-openai-connection",
  "connectionType": "model"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFoundryConnection(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FoundryConnection: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestFoundryConnectionToYAML tests that ToYAML produces valid YAML
func TestFoundryConnectionToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "foundry",
  "endpoint": "https://myresource.services.ai.azure.com/api/projects/myproject",
  "name": "my-openai-connection",
  "connectionType": "model"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFoundryConnection(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FoundryConnection: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
