// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// Prompty represents A Prompty is a markdown file format for LLM prompts. The frontmatter defines
// structured metadata including model configuration, input/output schemas, tools,
// and template settings. The markdown body becomes the instructions.
//
// This is the single root type for the Prompty schema — there is no abstract base
// class or kind discriminator. A .prompty file always produces a Prompty instance.

type Prompty struct {
	Name                   string                 `json:"name" yaml:"name"`
	DisplayName            *string                `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	Description            *string                `json:"description,omitempty" yaml:"description,omitempty"`
	Metadata               map[string]interface{} `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	InputSchema            *PropertySchema        `json:"inputSchema,omitempty" yaml:"inputSchema,omitempty"`
	OutputSchema           *PropertySchema        `json:"outputSchema,omitempty" yaml:"outputSchema,omitempty"`
	Model                  Model                  `json:"model" yaml:"model"`
	Tools                  []interface{}          `json:"tools,omitempty" yaml:"tools,omitempty"`
	Template               *Template              `json:"template,omitempty" yaml:"template,omitempty"`
	Instructions           *string                `json:"instructions,omitempty" yaml:"instructions,omitempty"`
	AdditionalInstructions *string                `json:"additionalInstructions,omitempty" yaml:"additionalInstructions,omitempty"`
}

// LoadPrompty creates a Prompty from a map[string]interface{}
func LoadPrompty(data interface{}, ctx *LoadContext) (Prompty, error) {
	result := Prompty{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["name"]; ok && val != nil {
			result.Name = val.(string)
		}
		if val, ok := m["displayName"]; ok && val != nil {
			v := val.(string)
			result.DisplayName = &v
		}
		if val, ok := m["description"]; ok && val != nil {
			v := val.(string)
			result.Description = &v
		}
		if val, ok := m["metadata"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				result.Metadata = m
			}
		}
		if val, ok := m["inputSchema"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadPropertySchema(m, ctx)
				result.InputSchema = &loaded
			}
		}
		if val, ok := m["outputSchema"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadPropertySchema(m, ctx)
				result.OutputSchema = &loaded
			}
		}
		if val, ok := m["model"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadModel(m, ctx)
				result.Model = loaded
			}
		}
		if val, ok := m["tools"]; ok && val != nil {
			if arr, ok := val.([]interface{}); ok {
				result.Tools = make([]interface{}, len(arr))
				for i, v := range arr {
					if item, ok := v.(map[string]interface{}); ok {
						loaded, _ := LoadTool(item, ctx)
						// Polymorphic type - store as interface{}
						result.Tools[i] = loaded
					}
				}
			}
		}
		if val, ok := m["template"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadTemplate(m, ctx)
				result.Template = &loaded
			}
		}
		if val, ok := m["instructions"]; ok && val != nil {
			v := val.(string)
			result.Instructions = &v
		}
		if val, ok := m["additionalInstructions"]; ok && val != nil {
			v := val.(string)
			result.AdditionalInstructions = &v
		}
	}

	return result, nil
}

// Save serializes Prompty to map[string]interface{}
func (obj *Prompty) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	result["name"] = obj.Name
	if obj.DisplayName != nil {
		result["displayName"] = *obj.DisplayName
	}
	if obj.Description != nil {
		result["description"] = *obj.Description
	}
	if obj.Metadata != nil {
		result["metadata"] = obj.Metadata
	}
	if obj.InputSchema != nil {
		result["inputSchema"] = obj.InputSchema.Save(ctx)
	}
	if obj.OutputSchema != nil {
		result["outputSchema"] = obj.OutputSchema.Save(ctx)
	}

	result["model"] = obj.Model.Save(ctx)
	if obj.Tools != nil {
		arr := make([]interface{}, len(obj.Tools))
		for i, item := range obj.Tools {
			// Handle polymorphic type via type switch
			switch v := item.(type) {
			case interface {
				Save(*SaveContext) map[string]interface{}
			}:
				arr[i] = v.Save(ctx)
			default:
				arr[i] = item
			}
		}
		result["tools"] = arr
	}
	if obj.Template != nil {
		result["template"] = obj.Template.Save(ctx)
	}
	if obj.Instructions != nil {
		result["instructions"] = *obj.Instructions
	}
	if obj.AdditionalInstructions != nil {
		result["additionalInstructions"] = *obj.AdditionalInstructions
	}

	return result
}

// ToJSON serializes Prompty to JSON string
func (obj *Prompty) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes Prompty to YAML string
func (obj *Prompty) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := yaml.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// FromJSON creates Prompty from JSON string
func PromptyFromJSON(jsonStr string) (Prompty, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return Prompty{}, err
	}
	ctx := NewLoadContext()
	return LoadPrompty(data, ctx)
}

// FromYAML creates Prompty from YAML string
func PromptyFromYAML(yamlStr string) (Prompty, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return Prompty{}, err
	}
	ctx := NewLoadContext()
	return LoadPrompty(data, ctx)
}
