// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Conformance-only seam for opt-in live provider acceptance probes. Deterministic wire vectors own the canonical request bodies. These vectors run only when their declared provider credentials/capabilities are present and assert that the real provider accepts the runtime's request today.
#[async_trait::async_trait]
pub trait LiveProviderConformance: Send + Sync {
    /// Invoke a live provider and return structural acceptance evidence
    async fn invoke(
        &self,
        input: &serde_json::Value,
    ) -> Result<serde_json::Value, Box<dyn std::error::Error + Send + Sync>>;
}
