// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
//
// Part III behavioral @dispatch resolver for `Processor` — the twin of the
// shape discriminator match. The provider trait below has one method per
// @dispatch variant; a consumer attaches concrete impls by implementing it,
// so a forgotten slot fails to compile (E0046).
// See docs: reference/vector-conformance.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::processor::Processor;

/// Consumer-attached provider of `Processor` impls, one method per @dispatch
/// variant. Returns `None` to signal a valid-but-unimplemented variant to the
/// caller (e.g. the conformance harness skips it), never a silent miss.
pub trait ProcessorProvider {
    fn openai(&self) -> Option<&dyn Processor>;
    fn azure(&self) -> Option<&dyn Processor>;
    /// Catch-all for an unknown discriminator (the declared `*` child).
    fn custom(&self) -> Option<&dyn Processor>;
}

/// Map a `provider` discriminator value to the selected `Processor` impl —
/// the behavioral twin of the shape discriminator match.
pub fn resolve<'a>(
    provider: &str,
    registry: &'a dyn ProcessorProvider,
) -> Option<&'a dyn Processor> {
    match provider {
        "openai" => registry.openai(),
        "azure" => registry.azure(),
        _ => registry.custom(),
    }
}
