

// Code generated by AgentSchema emitter; DO NOT EDIT.

use super::context::{LoadContext, SaveContext};

/// Tracks token consumption for a single LLM call. Provider-specific field names (e.g., OpenAI's `prompt_tokens` vs Anthropic's `input_tokens`) are mapped via `knownAs` augments in the wire directory.
#[derive(Debug, Clone, Default, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenUsage {
    /// Number of tokens in the prompt/input sent to the model
    pub prompt_tokens: Option<i32>,
    /// Number of tokens generated in the model's completion/output
    pub completion_tokens: Option<i32>,
    /// Total tokens consumed (prompt + completion). May be provided by the API or computed.
    pub total_tokens: Option<i32>,
}

impl TokenUsage {
    /// Create a new TokenUsage with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load TokenUsage from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load TokenUsage from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load TokenUsage from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        Self {
            prompt_tokens: value.get("promptTokens").and_then(|v| v.as_i64()).map(|v| v as i32),
            completion_tokens: value.get("completionTokens").and_then(|v| v.as_i64()).map(|v| v as i32),
            total_tokens: value.get("totalTokens").and_then(|v| v.as_i64()).map(|v| v as i32),
        }
    }

    /// Serialize TokenUsage to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if let Some(val) = self.prompt_tokens {
            result.insert("promptTokens".to_string(), serde_json::Value::Number(serde_json::Number::from(val)));
        }
        if let Some(val) = self.completion_tokens {
            result.insert("completionTokens".to_string(), serde_json::Value::Number(serde_json::Number::from(val)));
        }
        if let Some(val) = self.total_tokens {
            result.insert("totalTokens".to_string(), serde_json::Value::Number(serde_json::Number::from(val)));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize TokenUsage to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize TokenUsage to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }

    /// Convert to provider-specific wire format.
    pub fn to_wire(&self, provider: &str) -> serde_json::Value {
        let data = serde_json::to_value(self).unwrap_or_default();
        let mut result = serde_json::Map::new();
        let wire_map: std::collections::HashMap<&str, std::collections::HashMap<&str, &str>> = std::collections::HashMap::from([
            ("promptTokens", std::collections::HashMap::from([("openai", "prompt_tokens"), ("anthropic", "input_tokens")])),
            ("completionTokens", std::collections::HashMap::from([("openai", "completion_tokens"), ("anthropic", "output_tokens")])),
            ("totalTokens", std::collections::HashMap::from([("openai", "total_tokens")])),
        ]);
        if let serde_json::Value::Object(map) = data {
            for (key, value) in map {
                if let Some(mapping) = wire_map.get(key.as_str()) {
                    if let Some(wire_name) = mapping.get(provider) {
                        result.insert(wire_name.to_string(), value);
                    }
                }
            }
        }
        serde_json::Value::Object(result)
    }
}
