// <auto-generated by typra-emitter>
// <auto-generated/>
// Code generated by Typra emitter; DO NOT EDIT.

using System;
using System.Text.Json.Serialization;

namespace Prompty.Core;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SessionSummaryStatus
{
    [JsonPropertyName("success")]
    Success,

    [JsonPropertyName("error")]
    Error,

    [JsonPropertyName("cancelled")]
    Cancelled,

    [JsonPropertyName("interrupted")]
    Interrupted,

}

public static class SessionSummaryStatusParser
{
    public static SessionSummaryStatus Parse(string value)
    {
        return value switch
        {
            "success" => SessionSummaryStatus.Success,
            "error" => SessionSummaryStatus.Error,
            "cancelled" => SessionSummaryStatus.Cancelled,
            "interrupted" => SessionSummaryStatus.Interrupted,
            _ => Enum.Parse<SessionSummaryStatus>(value, true),
        };
    }

    public static string ToValue(SessionSummaryStatus value)
    {
        return value switch
        {
            SessionSummaryStatus.Success => "success",
            SessionSummaryStatus.Error => "error",
            SessionSummaryStatus.Cancelled => "cancelled",
            SessionSummaryStatus.Interrupted => "interrupted",
            _ => value.ToString().ToLowerInvariant(),
        };
    }
}
