// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
using System.Text.Json;
using YamlDotNet.Serialization;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// Payload for "session_start" events.
    /// </summary>
public partial class SessionStartPayload
{
    /// <summary>
    /// The shorthand property name for this type, if any.
    /// </summary>
    public static string? ShorthandProperty => null;

    /// <summary>
    /// Initializes a new instance of <see cref="SessionStartPayload"/>.
    /// </summary>
#pragma warning disable CS8618
    public SessionStartPayload()
    {
    }
#pragma warning restore CS8618

    /// <summary>
    /// Stable session identifier
    /// </summary>
    public string SessionId { get; set; } = string.Empty;

    /// <summary>
    /// Session event schema version
    /// </summary>
    public string? SchemaVersion { get; set; }

    /// <summary>
    /// Producer that started the session
    /// </summary>
    public string? Producer { get; set; }

    /// <summary>
    /// Runtime that produced the session
    /// </summary>
    public string? Runtime { get; set; }

    /// <summary>
    /// Prompty library version
    /// </summary>
    public string? PromptyVersion { get; set; }

    /// <summary>
    /// ISO 8601 UTC timestamp when the session started
    /// </summary>
    public string? StartTime { get; set; }

    /// <summary>
    /// Selected model identifier, when known
    /// </summary>
    public string? SelectedModel { get; set; }

    /// <summary>
    /// Selected reasoning effort or equivalent model setting, when known
    /// </summary>
    public string? ReasoningEffort { get; set; }

    /// <summary>
    /// Repository and execution context
    /// </summary>
    public HarnessContext? Context { get; set; }



    #region Load Methods

    /// <summary>
    /// Load a SessionStartPayload instance from a dictionary.
    /// </summary>
    /// <param name="data">The dictionary containing the data.</param>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <returns>The loaded SessionStartPayload instance.</returns>
    public static SessionStartPayload Load(Dictionary<string, object?> data, LoadContext? context = null)
    {
        if (context is not null)
        {
            data = context.ProcessInput(data);
        }


        // Create new instance
        var instance = new SessionStartPayload();


        if (data.TryGetValue("sessionId", out var sessionIdValue) && sessionIdValue is not null)
        {
            instance.SessionId = sessionIdValue?.ToString()!;
        }

        if (data.TryGetValue("schemaVersion", out var schemaVersionValue) && schemaVersionValue is not null)
        {
            instance.SchemaVersion = schemaVersionValue?.ToString()!;
        }

        if (data.TryGetValue("producer", out var producerValue) && producerValue is not null)
        {
            instance.Producer = producerValue?.ToString()!;
        }

        if (data.TryGetValue("runtime", out var runtimeValue) && runtimeValue is not null)
        {
            instance.Runtime = runtimeValue?.ToString()!;
        }

        if (data.TryGetValue("promptyVersion", out var promptyVersionValue) && promptyVersionValue is not null)
        {
            instance.PromptyVersion = promptyVersionValue?.ToString()!;
        }

        if (data.TryGetValue("startTime", out var startTimeValue) && startTimeValue is not null)
        {
            instance.StartTime = startTimeValue?.ToString()!;
        }

        if (data.TryGetValue("selectedModel", out var selectedModelValue) && selectedModelValue is not null)
        {
            instance.SelectedModel = selectedModelValue?.ToString()!;
        }

        if (data.TryGetValue("reasoningEffort", out var reasoningEffortValue) && reasoningEffortValue is not null)
        {
            instance.ReasoningEffort = reasoningEffortValue?.ToString()!;
        }

        if (data.TryGetValue("context", out var contextValue) && contextValue is not null)
        {
            instance.Context = HarnessContext.Load(contextValue.GetDictionary(HarnessContext.ShorthandProperty), context);
        }

        if (context is not null)
        {
            instance = context.ProcessOutput(instance);
        }
        return instance;
    }


    #endregion

    #region Save Methods

    /// <summary>
    /// Save the SessionStartPayload instance to a dictionary.
    /// </summary>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <returns>The dictionary representation of this instance.</returns>
    public Dictionary<string, object?> Save(SaveContext? context = null)
    {
        var obj = this;
        if (context is not null)
        {
            obj = context.ProcessObject(obj);
        }


        var result = new Dictionary<string, object?>();


        result["sessionId"] = obj.SessionId;


        if (obj.SchemaVersion is not null)
        {
            result["schemaVersion"] = obj.SchemaVersion;
        }


        if (obj.Producer is not null)
        {
            result["producer"] = obj.Producer;
        }


        if (obj.Runtime is not null)
        {
            result["runtime"] = obj.Runtime;
        }


        if (obj.PromptyVersion is not null)
        {
            result["promptyVersion"] = obj.PromptyVersion;
        }


        if (obj.StartTime is not null)
        {
            result["startTime"] = obj.StartTime;
        }


        if (obj.SelectedModel is not null)
        {
            result["selectedModel"] = obj.SelectedModel;
        }


        if (obj.ReasoningEffort is not null)
        {
            result["reasoningEffort"] = obj.ReasoningEffort;
        }


        if (obj.Context is not null)
        {
            result["context"] = obj.Context?.Save(context);
        }


        if (context is not null)
        {
            result = context.ProcessDict(result);
        }

        return result;
    }


    /// <summary>
    /// Convert the SessionStartPayload instance to a YAML string.
    /// </summary>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <returns>The YAML string representation of this instance.</returns>
    public string ToYaml(SaveContext? context = null)
    {
        context ??= new SaveContext();
        return context.ToYaml(Save(context));
    }

    /// <summary>
    /// Convert the SessionStartPayload instance to a JSON string.
    /// </summary>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <param name="indent">Whether to indent the output. Defaults to true.</param>
    /// <returns>The JSON string representation of this instance.</returns>
    public string ToJson(SaveContext? context = null, bool indent = true)
    {
        context ??= new SaveContext();
        return context.ToJson(Save(context), indent);
    }

    /// <summary>
    /// Load a SessionStartPayload instance from a JSON string.
    /// </summary>
    /// <param name="json">The JSON string to parse.</param>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <returns>The loaded SessionStartPayload instance.</returns>
    public static SessionStartPayload FromJson(string json, LoadContext? context = null)
    {
        using var doc = JsonDocument.Parse(json);
        Dictionary<string, object?> dict;
        dict = JsonSerializer.Deserialize<Dictionary<string, object?>>(json, JsonUtils.Options)
            ?? throw new ArgumentException("Failed to parse JSON as dictionary");

        return Load(dict, context);
    }

    /// <summary>
    /// Load a SessionStartPayload instance from a YAML string.
    /// </summary>
    /// <param name="yaml">The YAML string to parse.</param>
    /// <param name="context">Optional context with pre/post processing callbacks.</param>
    /// <returns>The loaded SessionStartPayload instance.</returns>
    public static SessionStartPayload FromYaml(string yaml, LoadContext? context = null)
    {
        var dict = YamlUtils.Deserializer.Deserialize<Dictionary<string, object?>>(yaml)
            ?? throw new ArgumentException("Failed to parse YAML as dictionary");

        return Load(dict, context);
    }

    #endregion
}
