// <auto-generated/>
// Code generated by Prompty emitter; DO NOT EDIT.

using System.Text.Json.Serialization;

namespace Prompty.Core;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TurnEventType
{
    [JsonPropertyName("turn_start")]
    TurnStart,

    [JsonPropertyName("turn_end")]
    TurnEnd,

    [JsonPropertyName("llm_start")]
    LlmStart,

    [JsonPropertyName("llm_complete")]
    LlmComplete,

    [JsonPropertyName("retry")]
    Retry,

    [JsonPropertyName("permission_requested")]
    PermissionRequested,

    [JsonPropertyName("permission_completed")]
    PermissionCompleted,

    [JsonPropertyName("token")]
    Token,

    [JsonPropertyName("thinking")]
    Thinking,

    [JsonPropertyName("tool_call_start")]
    ToolCallStart,

    [JsonPropertyName("tool_call_complete")]
    ToolCallComplete,

    [JsonPropertyName("tool_result")]
    ToolResult,

    [JsonPropertyName("status")]
    Status,

    [JsonPropertyName("messages_updated")]
    MessagesUpdated,

    [JsonPropertyName("done")]
    Done,

    [JsonPropertyName("error")]
    Error,

    [JsonPropertyName("cancelled")]
    Cancelled,

    [JsonPropertyName("compaction_start")]
    CompactionStart,

    [JsonPropertyName("compaction_complete")]
    CompactionComplete,

    [JsonPropertyName("compaction_failed")]
    CompactionFailed,

}
