// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

public protocol TurnConformance: Sendable {
  func replay(input: Any) async throws -> Any
  func run(input: Any) async throws -> Any
  func runTurn(input: Any) async throws -> Any
}
