# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from typing import Protocol, runtime_checkable

from .contracts.events._SessionEvent import SessionEvent
from .contracts.events._TurnEvent import TurnEvent


@runtime_checkable
class EventSink(Protocol):
    """Receives typed turn and session events from a harness.
    """

    def emit_session(self, session_event: SessionEvent) -> bool:
        """Emit a typed session event to a host sink"""
        raise NotImplementedError

    def emit_turn(self, turn_event: TurnEvent) -> bool:
        """Emit a typed turn event to a host sink"""
        raise NotImplementedError
