# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from typing import Any, Protocol, runtime_checkable

from ._Agent import Agent


@runtime_checkable
class Renderer(Protocol):
    """Renders a template string with input values to produce the final prompt text."""

    def render(self, agent: Agent, template: str, inputs: dict[str, Any]) -> str:
        """Render the template string with input values"""
        raise NotImplementedError

    async def render_async(self, agent: Agent, template: str, inputs: dict[str, Any]) -> str:
        """Render the template string with input values (async variant)"""
        raise NotImplementedError
