// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use super::super::context::{LoadContext, SaveContext};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RedactionMode {
    None,
    Redacted,
    Hashed,
    Summary,
    Reference,
}

impl Default for RedactionMode {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for RedactionMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Redacted => write!(f, "redacted"),
            Self::Hashed => write!(f, "hashed"),
            Self::Summary => write!(f, "summary"),
            Self::Reference => write!(f, "reference"),
        }
    }
}

impl RedactionMode {
    pub fn from_str_opt(s: &str) -> Option<Self> {
        match s {
            "none" => Some(Self::None),
            "redacted" => Some(Self::Redacted),
            "hashed" => Some(Self::Hashed),
            "summary" => Some(Self::Summary),
            "reference" => Some(Self::Reference),
            _ => None,
        }
    }

    pub fn from_str_ignore_case_opt(s: &str) -> Option<Self> {
        if s.eq_ignore_ascii_case("none") {
            return Some(Self::None);
        }
        if s.eq_ignore_ascii_case("redacted") {
            return Some(Self::Redacted);
        }
        if s.eq_ignore_ascii_case("hashed") {
            return Some(Self::Hashed);
        }
        if s.eq_ignore_ascii_case("summary") {
            return Some(Self::Summary);
        }
        if s.eq_ignore_ascii_case("reference") {
            return Some(Self::Reference);
        }
        None
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::None => "none",
            Self::Redacted => "redacted",
            Self::Hashed => "hashed",
            Self::Summary => "summary",
            Self::Reference => "reference",
        }
    }
}

impl serde::Serialize for RedactionMode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for RedactionMode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::from_str_opt(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("invalid RedactionMode value: {}", s)))
    }
}

/// Redaction handling for one JSON-shaped field path.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct RedactedField {
    /// JSONPath-like field path, relative to the containing payload
    pub path: String,
    /// How the field was represented
    pub mode: RedactionMode,
    /// Human-readable reason or policy that caused this handling
    pub reason: Option<String>,
}

impl RedactedField {
    /// Create a new RedactedField with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load RedactedField from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load RedactedField from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load RedactedField from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        Self {
            path: value
                .get("path")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            mode: value
                .get("mode")
                .and_then(|v| v.as_str())
                .and_then(|s| RedactionMode::from_str_opt(s))
                .unwrap_or(RedactionMode::None),
            reason: value
                .get("reason")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
        }
    }

    /// Serialize RedactedField to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if !self.path.is_empty() {
            result.insert(
                "path".to_string(),
                serde_json::Value::String(self.path.clone()),
            );
        }
        result.insert(
            "mode".to_string(),
            serde_json::Value::String(self.mode.to_string()),
        );
        if let Some(ref val) = self.reason {
            result.insert("reason".to_string(), serde_json::Value::String(val.clone()));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize RedactedField to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize RedactedField to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `RedactedField` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
impl serde::Serialize for RedactedField {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

impl<'de> serde::Deserialize<'de> for RedactedField {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
