// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Linq;
using System.Text.Json;
using System.Threading;
using YamlDotNet.Serialization;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// The response body from the Anthropic Messages API.
    /// </summary>
public partial class AnthropicMessagesResponse
{
    /// <summary>
    /// The shorthand property name for this type, if any.
    /// </summary>
    public static string? ShorthandProperty => null;

    /// <summary>
    /// Initializes a new instance of <see cref="AnthropicMessagesResponse"/>.
    /// </summary>
#pragma warning disable CS8618
    public AnthropicMessagesResponse()
    {
    }
#pragma warning restore CS8618

    /// <summary>
    /// Unique response identifier
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Object type (always 'message')
    /// </summary>
    public string Type { get; set; } = "message";

    /// <summary>
    /// The role of the response (always 'assistant')
    /// </summary>
    public string Role { get; set; } = "assistant";

    /// <summary>
    /// Array of content blocks in the response (AnthropicTextBlock | AnthropicToolUseBlock)
    /// </summary>
    public IList<object> Content { get; set; } = [];

    /// <summary>
    /// The model that generated the response
    /// </summary>
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// The reason generation stopped ('end_turn', 'max_tokens', 'stop_sequence', 'tool_use')
    /// </summary>
    public string StopReason { get; set; } = string.Empty;

    /// <summary>
    /// Token usage statistics
    /// </summary>
    public AnthropicUsage Usage { get; set; }


}
