// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Linq;
using System.Text.Json;
using System.Threading;
using YamlDotNet.Serialization;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// A tool use content block returned in an assistant message when
    ///
    /// the model wants to invoke a tool.
    /// </summary>
public partial class AnthropicToolUseBlock
{
    /// <summary>
    /// The shorthand property name for this type, if any.
    /// </summary>
    public static string? ShorthandProperty => null;

    /// <summary>
    /// Initializes a new instance of <see cref="AnthropicToolUseBlock"/>.
    /// </summary>
#pragma warning disable CS8618
    public AnthropicToolUseBlock()
    {
    }
#pragma warning restore CS8618

    /// <summary>
    /// The content block type
    /// </summary>
    public string Type { get; set; } = "tool_use";

    /// <summary>
    /// Unique identifier for this tool invocation
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The name of the tool to invoke
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The JSON arguments for the tool call
    /// </summary>
    public IDictionary<string, object?> Input { get; set; } = new Dictionary<string, object?>();


}
