// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use super::super::context::{LoadContext, SaveContext};

/// Template parser definition
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ParserConfig {
    /// Parser used to process the rendered template into API-compatible format
    pub kind: String,
    /// Options for the parser
    pub options: serde_json::Value,
}

impl ParserConfig {
    /// Create a new ParserConfig with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load ParserConfig from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ParserConfig from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ParserConfig from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Some(s) = value.as_str() {
            let value = s.to_string();
            return ParserConfig {
                kind: value.into(),
                ..Default::default()
            };
        }
        Self {
            kind: value
                .get("kind")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            options: value
                .get("options")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        }
    }

    /// Serialize ParserConfig to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if !self.kind.is_empty() {
            result.insert(
                "kind".to_string(),
                serde_json::Value::String(self.kind.clone()),
            );
        }
        if !self.options.is_null() {
            result.insert("options".to_string(), self.options.clone());
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize ParserConfig to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize ParserConfig to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_options_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.options.as_object()
    }
}

// Serde for `ParserConfig` delegates to the canonical to_value/load_from_value
// logic so its scalar-coercion shorthand round-trips through the canonical semantics. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
impl serde::Serialize for ParserConfig {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

impl<'de> serde::Deserialize<'de> for ParserConfig {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
