// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "./context";

/**
 * The approval mode for MCP server tools.
 * When kind is "specify", use alwaysRequireApprovalTools and neverRequireApprovalTools
 * to control per-tool approval. For "always" and "never", those fields are ignored.
 *
 */
export class McpApprovalMode {
  /**
   * The shorthand property name for this type, if any.
   */
  static readonly shorthandProperty: string | undefined = "kind";

  /**
   * The approval mode: 'always', 'never', or 'specify'
   */
  kind: string = "";

  /**
   * List of tools that always require approval (only used when kind is 'specify')
   */
  alwaysRequireApprovalTools?: string[] = [];

  /**
   * List of tools that never require approval (only used when kind is 'specify')
   */
  neverRequireApprovalTools?: string[] = [];

  /**
   * Initializes a new instance of McpApprovalMode.
   */
  constructor(init?: Partial<McpApprovalMode>) {
    this.kind = init?.kind ?? "";

    if (init?.alwaysRequireApprovalTools !== undefined) {
      this.alwaysRequireApprovalTools = init.alwaysRequireApprovalTools;
    }

    if (init?.neverRequireApprovalTools !== undefined) {
      this.neverRequireApprovalTools = init.neverRequireApprovalTools;
    }
  }

  //#region Load Methods

  /**
   * Load a McpApprovalMode instance from a dictionary.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpApprovalMode instance.
   */
  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): McpApprovalMode {
    if (context) {
      data = context.processInput(data);
    }

    // Handle alternate representations
    if (typeof data === "string") {
      data = { kind: data };
    } else if (typeof data === "number") {
    } else if (typeof data === "boolean") {
    }

    // Create new instance
    const instance = new McpApprovalMode();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }

    if (
      data["alwaysRequireApprovalTools"] !== undefined &&
      data["alwaysRequireApprovalTools"] !== null
    ) {
      instance.alwaysRequireApprovalTools = Array.isArray(
        data["alwaysRequireApprovalTools"],
      )
        ? (data["alwaysRequireApprovalTools"] as unknown[]).map((v) =>
            String(v),
          )
        : [];
    }

    if (
      data["neverRequireApprovalTools"] !== undefined &&
      data["neverRequireApprovalTools"] !== null
    ) {
      instance.neverRequireApprovalTools = Array.isArray(
        data["neverRequireApprovalTools"],
      )
        ? (data["neverRequireApprovalTools"] as unknown[]).map((v) => String(v))
        : [];
    }

    if (context) {
      return context.processOutput(instance) as McpApprovalMode;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  /**
   * Save the McpApprovalMode instance to a dictionary.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The dictionary representation of this instance.
   */
  save(context?: SaveContext): Record<string, unknown> {
    const obj = context
      ? (context.processObject(this) as McpApprovalMode)
      : this;

    const result: Record<string, unknown> = {};

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }

    if (
      obj.alwaysRequireApprovalTools !== undefined &&
      obj.alwaysRequireApprovalTools !== null
    ) {
      result["alwaysRequireApprovalTools"] = obj.alwaysRequireApprovalTools;
    }

    if (
      obj.neverRequireApprovalTools !== undefined &&
      obj.neverRequireApprovalTools !== null
    ) {
      result["neverRequireApprovalTools"] = obj.neverRequireApprovalTools;
    }

    if (context) {
      return context.processDict(result);
    }

    return result;
  }

  /**
   * Convert the McpApprovalMode instance to a YAML string.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The YAML string representation of this instance.
   */
  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  /**
   * Convert the McpApprovalMode instance to a JSON string.
   * @param context - Optional context with pre/post processing callbacks.
   * @param indent - Number of spaces for indentation. Defaults to 2.
   * @returns The JSON string representation of this instance.
   */
  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  /**
   * Load a McpApprovalMode instance from a JSON string.
   * @param json - The JSON string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpApprovalMode instance.
   */
  static fromJson(json: string, context?: LoadContext): McpApprovalMode {
    const data = JSON.parse(json);

    // Handle alternate representations
    if (typeof data !== "object" || data === null || Array.isArray(data)) {
      if (typeof data === "string") {
        return McpApprovalMode.load({ kind: data }, context);
      } else if (typeof data === "number") {
        // Check if it's an integer or float
        if (Number.isInteger(data)) {
        } else {
        }
      } else if (typeof data === "boolean") {
      }
      // Fallback - shouldn't reach here
      return McpApprovalMode.load({ kind: data }, context);
    }

    return McpApprovalMode.load(data as Record<string, unknown>, context);
  }

  /**
   * Load a McpApprovalMode instance from a YAML string.
   * @param yaml - The YAML string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpApprovalMode instance.
   */
  static fromYaml(yaml: string, context?: LoadContext): McpApprovalMode {
    const { parse } = require("yaml");
    const data = parse(yaml);

    // Handle alternate representations
    if (typeof data !== "object" || data === null || Array.isArray(data)) {
      if (typeof data === "string") {
        return McpApprovalMode.load({ kind: data }, context);
      } else if (typeof data === "number") {
        // Check if it's an integer or float
        if (Number.isInteger(data)) {
        } else {
        }
      } else if (typeof data === "boolean") {
      }
      // Fallback - shouldn't reach here
      return McpApprovalMode.load({ kind: data }, context);
    }

    return McpApprovalMode.load(data as Record<string, unknown>, context);
  }

  //#endregion
}
