// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

/** Conformance-only seam that hosts the turn-engine behavior vectors: the agent
tool-calling loop against a scripted model, the turn engine's ordered typed
event stream, and the normalized replay journal. Each is validated
identically across every runtime.

This interface exists purely to carry */
export interface TurnConformance {
  /** Run a scenario and assert the normalized replay journal sequence */
  replay(input: unknown): Promise<unknown>;
  /** Run the agent tool-calling loop against a scripted model to a final result */
  run(input: unknown): Promise<unknown>;
  /** Run a single turn and assert the ordered typed event stream it emits */
  runTurn(input: unknown): Promise<unknown>;
}
