# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass
from typing import Any, ClassVar, Literal

TurnStatus = Literal["success", "error", "cancelled"]


@dataclass
class TurnEndPayload:
    """Payload for "turn_end" events — a turn has completed.

    Attributes
    ----------
    iterations : Optional[int]
        Number of tool-call iterations performed
    status : Optional[str]
        Final semantic status of the turn
    response : Optional[Any]
        Final response after processing, if available
    duration_ms : Optional[float]
        Total elapsed turn duration in milliseconds
    """

    _shorthand_property: ClassVar[str | None] = None

    iterations: int | None = None
    status: TurnStatus | None = None
    response: Any | None = None
    duration_ms: float | None = None
