// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestCompactionCompletePayloadLoadJSON tests loading CompactionCompletePayload from JSON
func TestCompactionCompletePayloadLoadJSON(t *testing.T) {
	jsonData := `
{
  "removed": 5,
  "remaining": 3,
  "summaryLength": 1200
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadCompactionCompletePayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload: %v", err)
	}
	if instance.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, instance.Removed)
	}
	if instance.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, instance.Remaining)
	}
	if instance.SummaryLength == nil || *instance.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, instance.SummaryLength)
	}
}

// TestCompactionCompletePayloadLoadYAML tests loading CompactionCompletePayload from YAML
func TestCompactionCompletePayloadLoadYAML(t *testing.T) {
	yamlData := `
removed: 5
remaining: 3
summaryLength: 1200

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadCompactionCompletePayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload: %v", err)
	}
	if instance.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, instance.Removed)
	}
	if instance.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, instance.Remaining)
	}
	if instance.SummaryLength == nil || *instance.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, instance.SummaryLength)
	}
}

// TestCompactionCompletePayloadFromJSON tests loading CompactionCompletePayload through the generated JSON helper
func TestCompactionCompletePayloadFromJSON(t *testing.T) {
	jsonData := `
{
  "removed": 5,
  "remaining": 3,
  "summaryLength": 1200
}
`

	instance, err := prompty.CompactionCompletePayloadFromJSON(jsonData)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload from JSON helper: %v", err)
	}
	if instance.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, instance.Removed)
	}
	if instance.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, instance.Remaining)
	}
	if instance.SummaryLength == nil || *instance.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, instance.SummaryLength)
	}
}

// TestCompactionCompletePayloadFromYAML tests loading CompactionCompletePayload through the generated YAML helper
func TestCompactionCompletePayloadFromYAML(t *testing.T) {
	yamlData := `
removed: 5
remaining: 3
summaryLength: 1200

`

	instance, err := prompty.CompactionCompletePayloadFromYAML(yamlData)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload from YAML helper: %v", err)
	}
	if instance.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, instance.Removed)
	}
	if instance.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, instance.Remaining)
	}
	if instance.SummaryLength == nil || *instance.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, instance.SummaryLength)
	}
}

// TestCompactionCompletePayloadRoundtrip tests load -> save -> load produces equivalent data
func TestCompactionCompletePayloadRoundtrip(t *testing.T) {
	jsonData := `
{
  "removed": 5,
  "remaining": 3,
  "summaryLength": 1200
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadCompactionCompletePayload(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadCompactionCompletePayload(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload CompactionCompletePayload: %v", err)
	}
	if reloaded.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, reloaded.Removed)
	}
	if reloaded.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, reloaded.Remaining)
	}
	if reloaded.SummaryLength == nil || *reloaded.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, reloaded.SummaryLength)
	}
}

// TestCompactionCompletePayloadToJSON tests that ToJSON produces valid JSON
func TestCompactionCompletePayloadToJSON(t *testing.T) {
	jsonData := `
{
  "removed": 5,
  "remaining": 3,
  "summaryLength": 1200
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadCompactionCompletePayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}

	reloaded, err := prompty.LoadCompactionCompletePayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated JSON: %v", err)
	}
	if reloaded.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, reloaded.Removed)
	}
	if reloaded.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, reloaded.Remaining)
	}
	if reloaded.SummaryLength == nil || *reloaded.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, reloaded.SummaryLength)
	}
}

// TestCompactionCompletePayloadToYAML tests that ToYAML produces valid YAML
func TestCompactionCompletePayloadToYAML(t *testing.T) {
	jsonData := `
{
  "removed": 5,
  "remaining": 3,
  "summaryLength": 1200
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadCompactionCompletePayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CompactionCompletePayload: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}

	reloaded, err := prompty.LoadCompactionCompletePayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated YAML: %v", err)
	}
	if reloaded.Removed != 5 {
		t.Errorf(`Expected Removed to be 5, got %v`, reloaded.Removed)
	}
	if reloaded.Remaining != 3 {
		t.Errorf(`Expected Remaining to be 3, got %v`, reloaded.Remaining)
	}
	if reloaded.SummaryLength == nil || *reloaded.SummaryLength != 1200 {
		t.Errorf(`Expected SummaryLength to be 1200, got %v`, reloaded.SummaryLength)
	}
}

// TestCompactionCompletePayloadFromJSONInvalid rejects malformed JSON instead of silently defaulting
func TestCompactionCompletePayloadFromJSONInvalid(t *testing.T) {
	if _, err := prompty.CompactionCompletePayloadFromJSON("{"); err == nil {
		t.Fatalf("Expected malformed JSON to fail")
	}
}
