// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
// Group: pipeline

package prompty

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// ContextRequest represents Planning input handed to the context pipeline before one model invocation.

type ContextRequest struct {
	SessionId            string                 `json:"sessionId" yaml:"sessionId"`
	TurnId               string                 `json:"turnId" yaml:"turnId"`
	InvocationId         string                 `json:"invocationId" yaml:"invocationId"`
	Iteration            int32                  `json:"iteration" yaml:"iteration"`
	Messages             []Message              `json:"messages" yaml:"messages"`
	StablePrefixMessages int32                  `json:"stablePrefixMessages" yaml:"stablePrefixMessages"`
	ContextState         InvocationContextState `json:"contextState" yaml:"contextState"`
	Inputs               *interface{}           `json:"inputs,omitempty" yaml:"inputs,omitempty"`
}

// LoadContextRequest creates a ContextRequest from a map[string]interface{}
func LoadContextRequest(data interface{}, ctx *LoadContext) (ContextRequest, error) {
	result := ContextRequest{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["sessionId"]; ok && val != nil {
			result.SessionId = string(val.(string))
		}
		if val, ok := m["turnId"]; ok && val != nil {
			result.TurnId = string(val.(string))
		}
		if val, ok := m["invocationId"]; ok && val != nil {
			result.InvocationId = string(val.(string))
		}
		if val, ok := m["iteration"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			var v int32
			switch n := val.(type) {
			case int:
				v = int32(n)
			case int32:
				v = int32(n)
			case int64:
				v = int32(n)
			case float64:
				v = int32(n)
			}
			result.Iteration = v
		}
		if val, ok := m["messages"]; ok && val != nil {
			if arr, ok := val.([]interface{}); ok {
				result.Messages = make([]Message, len(arr))
				for i, v := range arr {
					if item, ok := v.(map[string]interface{}); ok {
						loaded, _ := LoadMessage(item, ctx)
						result.Messages[i] = loaded
					}
				}
			}
		}
		if val, ok := m["stablePrefixMessages"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			var v int32
			switch n := val.(type) {
			case int:
				v = int32(n)
			case int32:
				v = int32(n)
			case int64:
				v = int32(n)
			case float64:
				v = int32(n)
			}
			result.StablePrefixMessages = v
		}
		if val, ok := m["contextState"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadInvocationContextState(m, ctx)
				result.ContextState = loaded
			}
		}
		if val, ok := m["inputs"]; ok && val != nil {
			result.Inputs = &val
		}
	}

	return result, nil
}

// Save serializes ContextRequest to map[string]interface{}
func (obj ContextRequest) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	result["sessionId"] = obj.SessionId
	result["turnId"] = obj.TurnId
	result["invocationId"] = obj.InvocationId
	result["iteration"] = obj.Iteration
	if obj.Messages != nil {
		arr := make([]interface{}, len(obj.Messages))
		for i, item := range obj.Messages {
			arr[i] = item.Save(ctx)
		}
		result["messages"] = arr
	}
	result["stablePrefixMessages"] = obj.StablePrefixMessages

	result["contextState"] = obj.ContextState.Save(ctx)
	if obj.Inputs != nil {
		result["inputs"] = *obj.Inputs
	}

	return result
}

// ToJSON serializes ContextRequest to JSON string
func (obj *ContextRequest) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes ContextRequest to YAML string
func (obj *ContextRequest) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	return marshalYAMLDocument(data)
}

// FromJSON creates ContextRequest from JSON string
func ContextRequestFromJSON(jsonStr string) (ContextRequest, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ContextRequest{}, err
	}
	ctx := NewLoadContext()
	return LoadContextRequest(data, ctx)
}

// FromYAML creates ContextRequest from YAML string
func ContextRequestFromYAML(yamlStr string) (ContextRequest, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return ContextRequest{}, err
	}
	ctx := NewLoadContext()
	return LoadContextRequest(data, ctx)
}
