// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"reflect"
	"testing"

	"gopkg.in/yaml.v3"

	prompty "prompty/model"
)

// TestDeviceAuthorizationLoadJSON tests loading DeviceAuthorization from JSON
func TestDeviceAuthorizationLoadJSON(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}
	if instance.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, instance.DeviceCode)
	}
	if instance.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, instance.UserCode)
	}
	if instance.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, instance.VerificationUri)
	}
	if instance.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, instance.ExpiresIn)
	}
	if instance.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, instance.Interval)
	}
}

// TestDeviceAuthorizationLoadYAML tests loading DeviceAuthorization from YAML
func TestDeviceAuthorizationLoadYAML(t *testing.T) {
	yamlData := `
deviceCode: sample
userCode: sample
verificationUri: sample
expiresIn: 1
interval: 1

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}
	if instance.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, instance.DeviceCode)
	}
	if instance.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, instance.UserCode)
	}
	if instance.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, instance.VerificationUri)
	}
	if instance.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, instance.ExpiresIn)
	}
	if instance.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, instance.Interval)
	}
}

// TestDeviceAuthorizationFromJSON tests loading DeviceAuthorization through the generated JSON helper
func TestDeviceAuthorizationFromJSON(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`

	instance, err := prompty.DeviceAuthorizationFromJSON(jsonData)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization from JSON helper: %v", err)
	}
	if instance.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, instance.DeviceCode)
	}
	if instance.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, instance.UserCode)
	}
	if instance.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, instance.VerificationUri)
	}
	if instance.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, instance.ExpiresIn)
	}
	if instance.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, instance.Interval)
	}
}

// TestDeviceAuthorizationFromYAML tests loading DeviceAuthorization through the generated YAML helper
func TestDeviceAuthorizationFromYAML(t *testing.T) {
	yamlData := `
deviceCode: sample
userCode: sample
verificationUri: sample
expiresIn: 1
interval: 1

`

	instance, err := prompty.DeviceAuthorizationFromYAML(yamlData)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization from YAML helper: %v", err)
	}
	if instance.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, instance.DeviceCode)
	}
	if instance.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, instance.UserCode)
	}
	if instance.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, instance.VerificationUri)
	}
	if instance.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, instance.ExpiresIn)
	}
	if instance.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, instance.Interval)
	}
}

// TestDeviceAuthorizationRoundtrip tests load -> save -> load produces equivalent data
func TestDeviceAuthorizationRoundtrip(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadDeviceAuthorization(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload DeviceAuthorization: %v", err)
	}
	if reloaded.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, reloaded.DeviceCode)
	}
	if reloaded.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, reloaded.UserCode)
	}
	if reloaded.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, reloaded.VerificationUri)
	}
	if reloaded.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, reloaded.ExpiresIn)
	}
	if reloaded.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, reloaded.Interval)
	}
}

// TestDeviceAuthorizationToJSON tests that ToJSON produces valid JSON
func TestDeviceAuthorizationToJSON(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}

	reloaded, err := prompty.LoadDeviceAuthorization(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated JSON: %v", err)
	}
	if reloaded.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, reloaded.DeviceCode)
	}
	if reloaded.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, reloaded.UserCode)
	}
	if reloaded.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, reloaded.VerificationUri)
	}
	if reloaded.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, reloaded.ExpiresIn)
	}
	if reloaded.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, reloaded.Interval)
	}
}

// TestDeviceAuthorizationToYAML tests that ToYAML produces valid YAML
func TestDeviceAuthorizationToYAML(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}

	reloaded, err := prompty.LoadDeviceAuthorization(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated YAML: %v", err)
	}
	if reloaded.DeviceCode != "sample" {
		t.Errorf(`Expected DeviceCode to be "sample", got %v`, reloaded.DeviceCode)
	}
	if reloaded.UserCode != "sample" {
		t.Errorf(`Expected UserCode to be "sample", got %v`, reloaded.UserCode)
	}
	if reloaded.VerificationUri != "sample" {
		t.Errorf(`Expected VerificationUri to be "sample", got %v`, reloaded.VerificationUri)
	}
	if reloaded.ExpiresIn != 1 {
		t.Errorf(`Expected ExpiresIn to be 1, got %v`, reloaded.ExpiresIn)
	}
	if reloaded.Interval != 1 {
		t.Errorf(`Expected Interval to be 1, got %v`, reloaded.Interval)
	}
}

// TestDeviceAuthorizationFromJSONInvalid rejects malformed JSON instead of silently defaulting
func TestDeviceAuthorizationFromJSONInvalid(t *testing.T) {
	if _, err := prompty.DeviceAuthorizationFromJSON("{"); err == nil {
		t.Fatalf("Expected malformed JSON to fail")
	}
}

// TestDeviceAuthorizationToWire tests provider-specific wire field names
func TestDeviceAuthorizationToWire(t *testing.T) {
	jsonData := `
{
  "deviceCode": "sample",
  "userCode": "sample",
  "verificationUri": "sample",
  "expiresIn": 1,
  "interval": 1
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadDeviceAuthorization(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load DeviceAuthorization: %v", err)
	}

	foundryWire := instance.ToWire("foundry")
	if _, ok := foundryWire["device_code"]; !ok {
		t.Errorf("Expected foundry wire output to include device_code")
	}
	if _, ok := foundryWire["deviceCode"]; ok {
		t.Errorf("Expected foundry wire output to omit source field deviceCode")
	}
	if _, ok := foundryWire["user_code"]; !ok {
		t.Errorf("Expected foundry wire output to include user_code")
	}
	if _, ok := foundryWire["userCode"]; ok {
		t.Errorf("Expected foundry wire output to omit source field userCode")
	}
	if _, ok := foundryWire["verification_uri"]; !ok {
		t.Errorf("Expected foundry wire output to include verification_uri")
	}
	if _, ok := foundryWire["verificationUri"]; ok {
		t.Errorf("Expected foundry wire output to omit source field verificationUri")
	}
	if _, ok := foundryWire["expires_in"]; !ok {
		t.Errorf("Expected foundry wire output to include expires_in")
	}
	if _, ok := foundryWire["expiresIn"]; ok {
		t.Errorf("Expected foundry wire output to omit source field expiresIn")
	}
	if _, ok := foundryWire["interval"]; !ok {
		t.Errorf("Expected foundry wire output to include interval")
	}
	foundryRestored, foundryErr := prompty.DeviceAuthorizationFromWire("foundry", foundryWire, ctx)
	if foundryErr != nil {
		t.Fatalf("Expected foundry FromWire to succeed, got %v", foundryErr)
	}
	if foundryRoundTrip := foundryRestored.ToWire("foundry"); !reflect.DeepEqual(foundryRoundTrip, foundryWire) {
		t.Errorf("Expected foundry FromWire round-trip to preserve the wire payload, got %v want %v", foundryRoundTrip, foundryWire)
	}
}

func assertDeviceAuthorizationStringField(t *testing.T, value interface{}, fieldName string, expected string, displayName string) {
	t.Helper()
	field := reflect.ValueOf(value)
	if field.Kind() == reflect.Pointer {
		if field.IsNil() {
			t.Fatalf("Expected %s to be populated", displayName)
		}
		field = field.Elem()
	}
	if field.Kind() != reflect.Struct {
		t.Fatalf("Expected %s receiver to be a struct, got %T", displayName, value)
	}
	member := field.FieldByName(fieldName)
	if !member.IsValid() {
		t.Fatalf("Expected %s to have field %s, got %T", displayName, fieldName, value)
	}
	if member.Kind() == reflect.Pointer {
		if member.IsNil() {
			t.Fatalf("Expected %s to be populated", displayName)
		}
		member = member.Elem()
	}
	if member.Kind() == reflect.Interface {
		if member.IsNil() {
			t.Fatalf("Expected %s to be populated", displayName)
		}
		member = member.Elem()
	}
	if member.Kind() != reflect.String {
		t.Fatalf("Expected %s to be a string field, got %s", displayName, member.Kind())
	}
	if got := member.String(); got != expected {
		t.Errorf("Expected %s to be %q, got %q", displayName, expected, got)
	}
}
