// Code generated by AgentSchema emitter; DO NOT EDIT.
// Group: events

package prompty

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// ErrorEventPayload represents Payload for "error" events — an error occurred during the loop.

type ErrorEventPayload struct {
	Message string `json:"message" yaml:"message"`
}

// LoadErrorEventPayload creates a ErrorEventPayload from a map[string]interface{}
func LoadErrorEventPayload(data interface{}, ctx *LoadContext) (ErrorEventPayload, error) {
	result := ErrorEventPayload{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["message"]; ok && val != nil {
			result.Message = string(val.(string))
		}
	}

	return result, nil
}

// Save serializes ErrorEventPayload to map[string]interface{}
func (obj *ErrorEventPayload) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	result["message"] = obj.Message

	return result
}

// ToJSON serializes ErrorEventPayload to JSON string
func (obj *ErrorEventPayload) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes ErrorEventPayload to YAML string
func (obj *ErrorEventPayload) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := yaml.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// FromJSON creates ErrorEventPayload from JSON string
func ErrorEventPayloadFromJSON(jsonStr string) (ErrorEventPayload, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ErrorEventPayload{}, err
	}
	ctx := NewLoadContext()
	return LoadErrorEventPayload(data, ctx)
}

// FromYAML creates ErrorEventPayload from YAML string
func ErrorEventPayloadFromYAML(yamlStr string) (ErrorEventPayload, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return ErrorEventPayload{}, err
	}
	ctx := NewLoadContext()
	return LoadErrorEventPayload(data, ctx)
}
