// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
// Group: pipeline

package prompty

// EventJournalWriter represents Persists typed events to a durable replay journal.

type EventJournalWriter interface {
	// AppendTurn — Append a turn event to a durable replay journal
	AppendTurn(turnEvent TurnEvent) (bool, error)
	// AppendSession — Append a session event to a durable replay journal
	AppendSession(sessionEvent SessionEvent) (bool, error)
	// Close — Finalize the journal with an optional session summary
	Close(summary *SessionSummary) (bool, error)
}
