// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestHookEndPayloadLoadJSON tests loading HookEndPayload from JSON
func TestHookEndPayloadLoadJSON(t *testing.T) {
	jsonData := `
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHookEndPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload: %v", err)
	}
	if instance.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, instance.HookInvocationId)
	}
	if instance.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, instance.HookType)
	}
	if instance.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, instance.Success)
	}
	if instance.DurationMs == nil || *instance.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, instance.DurationMs)
	}
	if instance.Error == nil || *instance.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, instance.Error)
	}
}

// TestHookEndPayloadLoadYAML tests loading HookEndPayload from YAML
func TestHookEndPayloadLoadYAML(t *testing.T) {
	yamlData := `
hookInvocationId: hook_abc123
hookType: preToolUse
success: true
durationMs: 12
error: hook failed

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHookEndPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload: %v", err)
	}
	if instance.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, instance.HookInvocationId)
	}
	if instance.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, instance.HookType)
	}
	if instance.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, instance.Success)
	}
	if instance.DurationMs == nil || *instance.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, instance.DurationMs)
	}
	if instance.Error == nil || *instance.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, instance.Error)
	}
}

// TestHookEndPayloadFromJSON tests loading HookEndPayload through the generated JSON helper
func TestHookEndPayloadFromJSON(t *testing.T) {
	jsonData := `
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
`

	instance, err := prompty.HookEndPayloadFromJSON(jsonData)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload from JSON helper: %v", err)
	}
	if instance.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, instance.HookInvocationId)
	}
	if instance.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, instance.HookType)
	}
	if instance.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, instance.Success)
	}
	if instance.DurationMs == nil || *instance.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, instance.DurationMs)
	}
	if instance.Error == nil || *instance.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, instance.Error)
	}
}

// TestHookEndPayloadFromYAML tests loading HookEndPayload through the generated YAML helper
func TestHookEndPayloadFromYAML(t *testing.T) {
	yamlData := `
hookInvocationId: hook_abc123
hookType: preToolUse
success: true
durationMs: 12
error: hook failed

`

	instance, err := prompty.HookEndPayloadFromYAML(yamlData)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload from YAML helper: %v", err)
	}
	if instance.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, instance.HookInvocationId)
	}
	if instance.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, instance.HookType)
	}
	if instance.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, instance.Success)
	}
	if instance.DurationMs == nil || *instance.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, instance.DurationMs)
	}
	if instance.Error == nil || *instance.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, instance.Error)
	}
}

// TestHookEndPayloadRoundtrip tests load -> save -> load produces equivalent data
func TestHookEndPayloadRoundtrip(t *testing.T) {
	jsonData := `
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadHookEndPayload(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadHookEndPayload(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload HookEndPayload: %v", err)
	}
	if reloaded.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, reloaded.HookInvocationId)
	}
	if reloaded.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, reloaded.HookType)
	}
	if reloaded.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, reloaded.Success)
	}
	if reloaded.DurationMs == nil || *reloaded.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, reloaded.DurationMs)
	}
	if reloaded.Error == nil || *reloaded.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, reloaded.Error)
	}
}

// TestHookEndPayloadToJSON tests that ToJSON produces valid JSON
func TestHookEndPayloadToJSON(t *testing.T) {
	jsonData := `
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHookEndPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}

	reloaded, err := prompty.LoadHookEndPayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated JSON: %v", err)
	}
	if reloaded.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, reloaded.HookInvocationId)
	}
	if reloaded.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, reloaded.HookType)
	}
	if reloaded.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, reloaded.Success)
	}
	if reloaded.DurationMs == nil || *reloaded.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, reloaded.DurationMs)
	}
	if reloaded.Error == nil || *reloaded.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, reloaded.Error)
	}
}

// TestHookEndPayloadToYAML tests that ToYAML produces valid YAML
func TestHookEndPayloadToYAML(t *testing.T) {
	jsonData := `
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHookEndPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HookEndPayload: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}

	reloaded, err := prompty.LoadHookEndPayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated YAML: %v", err)
	}
	if reloaded.HookInvocationId != "hook_abc123" {
		t.Errorf(`Expected HookInvocationId to be "hook_abc123", got %v`, reloaded.HookInvocationId)
	}
	if reloaded.HookType != "preToolUse" {
		t.Errorf(`Expected HookType to be "preToolUse", got %v`, reloaded.HookType)
	}
	if reloaded.Success != true {
		t.Errorf(`Expected Success to be true, got %v`, reloaded.Success)
	}
	if reloaded.DurationMs == nil || *reloaded.DurationMs != 12 {
		t.Errorf(`Expected DurationMs to be 12, got %v`, reloaded.DurationMs)
	}
	if reloaded.Error == nil || *reloaded.Error != "hook failed" {
		t.Errorf(`Expected Error to be "hook failed", got %v`, reloaded.Error)
	}
}

// TestHookEndPayloadFromJSONInvalid rejects malformed JSON instead of silently defaulting
func TestHookEndPayloadFromJSONInvalid(t *testing.T) {
	if _, err := prompty.HookEndPayloadFromJSON("{"); err == nil {
		t.Fatalf("Expected malformed JSON to fail")
	}
}
