// Code generated by Prompty emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestHostToolRequestLoadJSON tests loading HostToolRequest from JSON
func TestHostToolRequestLoadJSON(t *testing.T) {
	jsonData := `
{
  "requestId": "exec_abc123",
  "toolCallId": "call_abc123",
  "toolName": "powershell",
  "workingDirectory": "/workspace/project"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHostToolRequest(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HostToolRequest: %v", err)
	}
	if instance.RequestId == nil || *instance.RequestId != "exec_abc123" {
		t.Errorf(`Expected RequestId to be "exec_abc123", got %v`, instance.RequestId)
	}
	if instance.ToolCallId == nil || *instance.ToolCallId != "call_abc123" {
		t.Errorf(`Expected ToolCallId to be "call_abc123", got %v`, instance.ToolCallId)
	}
	if instance.ToolName != "powershell" {
		t.Errorf(`Expected ToolName to be "powershell", got %v`, instance.ToolName)
	}
	if instance.WorkingDirectory == nil || *instance.WorkingDirectory != "/workspace/project" {
		t.Errorf(`Expected WorkingDirectory to be "/workspace/project", got %v`, instance.WorkingDirectory)
	}
}

// TestHostToolRequestLoadYAML tests loading HostToolRequest from YAML
func TestHostToolRequestLoadYAML(t *testing.T) {
	yamlData := `
requestId: exec_abc123
toolCallId: call_abc123
toolName: powershell
workingDirectory: /workspace/project

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHostToolRequest(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HostToolRequest: %v", err)
	}
	if instance.RequestId == nil || *instance.RequestId != "exec_abc123" {
		t.Errorf(`Expected RequestId to be "exec_abc123", got %v`, instance.RequestId)
	}
	if instance.ToolCallId == nil || *instance.ToolCallId != "call_abc123" {
		t.Errorf(`Expected ToolCallId to be "call_abc123", got %v`, instance.ToolCallId)
	}
	if instance.ToolName != "powershell" {
		t.Errorf(`Expected ToolName to be "powershell", got %v`, instance.ToolName)
	}
	if instance.WorkingDirectory == nil || *instance.WorkingDirectory != "/workspace/project" {
		t.Errorf(`Expected WorkingDirectory to be "/workspace/project", got %v`, instance.WorkingDirectory)
	}
}

// TestHostToolRequestRoundtrip tests load -> save -> load produces equivalent data
func TestHostToolRequestRoundtrip(t *testing.T) {
	jsonData := `
{
  "requestId": "exec_abc123",
  "toolCallId": "call_abc123",
  "toolName": "powershell",
  "workingDirectory": "/workspace/project"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadHostToolRequest(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load HostToolRequest: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadHostToolRequest(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload HostToolRequest: %v", err)
	}
	if reloaded.RequestId == nil || *reloaded.RequestId != "exec_abc123" {
		t.Errorf(`Expected RequestId to be "exec_abc123", got %v`, reloaded.RequestId)
	}
	if reloaded.ToolCallId == nil || *reloaded.ToolCallId != "call_abc123" {
		t.Errorf(`Expected ToolCallId to be "call_abc123", got %v`, reloaded.ToolCallId)
	}
	if reloaded.ToolName != "powershell" {
		t.Errorf(`Expected ToolName to be "powershell", got %v`, reloaded.ToolName)
	}
	if reloaded.WorkingDirectory == nil || *reloaded.WorkingDirectory != "/workspace/project" {
		t.Errorf(`Expected WorkingDirectory to be "/workspace/project", got %v`, reloaded.WorkingDirectory)
	}
}

// TestHostToolRequestToJSON tests that ToJSON produces valid JSON
func TestHostToolRequestToJSON(t *testing.T) {
	jsonData := `
{
  "requestId": "exec_abc123",
  "toolCallId": "call_abc123",
  "toolName": "powershell",
  "workingDirectory": "/workspace/project"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHostToolRequest(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HostToolRequest: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestHostToolRequestToYAML tests that ToYAML produces valid YAML
func TestHostToolRequestToYAML(t *testing.T) {
	jsonData := `
{
  "requestId": "exec_abc123",
  "toolCallId": "call_abc123",
  "toolName": "powershell",
  "workingDirectory": "/workspace/project"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadHostToolRequest(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load HostToolRequest: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
