// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
// Group: model

package prompty

// ModelLister represents Lists models available through a provider connection.

type ModelLister interface {
	// ListModels — List models available through a provider connection
	ListModels(connection interface{}) ([]ModelInfo, error)
}
