// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestThinkingEventPayloadLoadJSON tests loading ThinkingEventPayload from JSON
func TestThinkingEventPayloadLoadJSON(t *testing.T) {
	jsonData := `
{
  "token": "Let me consider..."
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadThinkingEventPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload: %v", err)
	}
	if instance.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, instance.Token)
	}
}

// TestThinkingEventPayloadLoadYAML tests loading ThinkingEventPayload from YAML
func TestThinkingEventPayloadLoadYAML(t *testing.T) {
	yamlData := `
token: Let me consider...

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadThinkingEventPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload: %v", err)
	}
	if instance.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, instance.Token)
	}
}

// TestThinkingEventPayloadFromJSON tests loading ThinkingEventPayload through the generated JSON helper
func TestThinkingEventPayloadFromJSON(t *testing.T) {
	jsonData := `
{
  "token": "Let me consider..."
}
`

	instance, err := prompty.ThinkingEventPayloadFromJSON(jsonData)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload from JSON helper: %v", err)
	}
	if instance.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, instance.Token)
	}
}

// TestThinkingEventPayloadFromYAML tests loading ThinkingEventPayload through the generated YAML helper
func TestThinkingEventPayloadFromYAML(t *testing.T) {
	yamlData := `
token: Let me consider...

`

	instance, err := prompty.ThinkingEventPayloadFromYAML(yamlData)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload from YAML helper: %v", err)
	}
	if instance.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, instance.Token)
	}
}

// TestThinkingEventPayloadRoundtrip tests load -> save -> load produces equivalent data
func TestThinkingEventPayloadRoundtrip(t *testing.T) {
	jsonData := `
{
  "token": "Let me consider..."
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadThinkingEventPayload(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadThinkingEventPayload(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ThinkingEventPayload: %v", err)
	}
	if reloaded.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, reloaded.Token)
	}
}

// TestThinkingEventPayloadToJSON tests that ToJSON produces valid JSON
func TestThinkingEventPayloadToJSON(t *testing.T) {
	jsonData := `
{
  "token": "Let me consider..."
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadThinkingEventPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}

	reloaded, err := prompty.LoadThinkingEventPayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated JSON: %v", err)
	}
	if reloaded.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, reloaded.Token)
	}
}

// TestThinkingEventPayloadToYAML tests that ToYAML produces valid YAML
func TestThinkingEventPayloadToYAML(t *testing.T) {
	jsonData := `
{
  "token": "Let me consider..."
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadThinkingEventPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ThinkingEventPayload: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}

	reloaded, err := prompty.LoadThinkingEventPayload(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated YAML: %v", err)
	}
	if reloaded.Token != "Let me consider..." {
		t.Errorf(`Expected Token to be "Let me consider...", got %v`, reloaded.Token)
	}
}

// TestThinkingEventPayloadFromJSONInvalid rejects malformed JSON instead of silently defaulting
func TestThinkingEventPayloadFromJSONInvalid(t *testing.T) {
	if _, err := prompty.ThinkingEventPayloadFromJSON("{"); err == nil {
		t.Fatalf("Expected malformed JSON to fail")
	}
}
