// Code generated by AgentSchema emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestToolCallLoadJSON tests loading ToolCall from JSON
func TestToolCallLoadJSON(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCall(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCall: %v", err)
	}
	if instance.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, instance.Id)
	}
	if instance.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, instance.Name)
	}
	if instance.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, instance.Arguments)
	}
}

// TestToolCallLoadYAML tests loading ToolCall from YAML
func TestToolCallLoadYAML(t *testing.T) {
	yamlData := `
id: call_abc123
name: get_weather
arguments: "{\"city\": \"Paris\"}"

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCall(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCall: %v", err)
	}
	if instance.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, instance.Id)
	}
	if instance.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, instance.Name)
	}
	if instance.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, instance.Arguments)
	}
}

// TestToolCallRoundtrip tests load -> save -> load produces equivalent data
func TestToolCallRoundtrip(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCall(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ToolCall: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadToolCall(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ToolCall: %v", err)
	}
	if reloaded.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, reloaded.Id)
	}
	if reloaded.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, reloaded.Name)
	}
	if reloaded.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, reloaded.Arguments)
	}
}

// TestToolCallToJSON tests that ToJSON produces valid JSON
func TestToolCallToJSON(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCall(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCall: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestToolCallToYAML tests that ToYAML produces valid YAML
func TestToolCallToYAML(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCall(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCall: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
