// Code generated by Prompty emitter; DO NOT EDIT.
// Group: events

package prompty

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// ToolExecutionCompletePayload represents Payload for "tool_execution_complete" events — a concrete host tool execution finished.

type ToolExecutionCompletePayload struct {
	RequestId  *string                `json:"requestId,omitempty" yaml:"requestId,omitempty"`
	ToolCallId *string                `json:"toolCallId,omitempty" yaml:"toolCallId,omitempty"`
	ToolName   string                 `json:"toolName" yaml:"toolName"`
	Success    bool                   `json:"success" yaml:"success"`
	Result     *interface{}           `json:"result,omitempty" yaml:"result,omitempty"`
	ExitCode   *int32                 `json:"exitCode,omitempty" yaml:"exitCode,omitempty"`
	DurationMs *float64               `json:"durationMs,omitempty" yaml:"durationMs,omitempty"`
	ErrorKind  *string                `json:"errorKind,omitempty" yaml:"errorKind,omitempty"`
	Telemetry  map[string]interface{} `json:"telemetry,omitempty" yaml:"telemetry,omitempty"`
	Redaction  *RedactionMetadata     `json:"redaction,omitempty" yaml:"redaction,omitempty"`
}

// LoadToolExecutionCompletePayload creates a ToolExecutionCompletePayload from a map[string]interface{}
func LoadToolExecutionCompletePayload(data interface{}, ctx *LoadContext) (ToolExecutionCompletePayload, error) {
	result := ToolExecutionCompletePayload{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["requestId"]; ok && val != nil {
			v := string(val.(string))
			result.RequestId = &v
		}
		if val, ok := m["toolCallId"]; ok && val != nil {
			v := string(val.(string))
			result.ToolCallId = &v
		}
		if val, ok := m["toolName"]; ok && val != nil {
			result.ToolName = string(val.(string))
		}
		if val, ok := m["success"]; ok && val != nil {
			result.Success = val.(bool)
		}
		if val, ok := m["result"]; ok && val != nil {
			result.Result = &val
		}
		if val, ok := m["exitCode"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			var v int32
			switch n := val.(type) {
			case int:
				v = int32(n)
			case int32:
				v = int32(n)
			case int64:
				v = int32(n)
			case float64:
				v = int32(n)
			}
			result.ExitCode = &v
		}
		if val, ok := m["durationMs"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			var v float64
			switch n := val.(type) {
			case int:
				v = float64(n)
			case int32:
				v = float64(n)
			case int64:
				v = float64(n)
			case float32:
				v = float64(n)
			case float64:
				v = n
			}
			result.DurationMs = &v
		}
		if val, ok := m["errorKind"]; ok && val != nil {
			v := string(val.(string))
			result.ErrorKind = &v
		}
		if val, ok := m["telemetry"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				result.Telemetry = m
			}
		}
		if val, ok := m["redaction"]; ok && val != nil {
			if m, ok := val.(map[string]interface{}); ok {
				loaded, _ := LoadRedactionMetadata(m, ctx)
				result.Redaction = &loaded
			}
		}
	}

	return result, nil
}

// Save serializes ToolExecutionCompletePayload to map[string]interface{}
func (obj *ToolExecutionCompletePayload) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	if obj.RequestId != nil {
		result["requestId"] = *obj.RequestId
	}
	if obj.ToolCallId != nil {
		result["toolCallId"] = *obj.ToolCallId
	}
	result["toolName"] = obj.ToolName
	result["success"] = obj.Success
	if obj.Result != nil {
		result["result"] = *obj.Result
	}
	if obj.ExitCode != nil {
		result["exitCode"] = *obj.ExitCode
	}
	if obj.DurationMs != nil {
		result["durationMs"] = *obj.DurationMs
	}
	if obj.ErrorKind != nil {
		result["errorKind"] = *obj.ErrorKind
	}
	if obj.Telemetry != nil {
		result["telemetry"] = obj.Telemetry
	}
	if obj.Redaction != nil {
		result["redaction"] = obj.Redaction.Save(ctx)
	}

	return result
}

// ToJSON serializes ToolExecutionCompletePayload to JSON string
func (obj *ToolExecutionCompletePayload) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes ToolExecutionCompletePayload to YAML string
func (obj *ToolExecutionCompletePayload) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := yaml.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// FromJSON creates ToolExecutionCompletePayload from JSON string
func ToolExecutionCompletePayloadFromJSON(jsonStr string) (ToolExecutionCompletePayload, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ToolExecutionCompletePayload{}, err
	}
	ctx := NewLoadContext()
	return LoadToolExecutionCompletePayload(data, ctx)
}

// FromYAML creates ToolExecutionCompletePayload from YAML string
func ToolExecutionCompletePayloadFromYAML(yamlStr string) (ToolExecutionCompletePayload, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return ToolExecutionCompletePayload{}, err
	}
	ctx := NewLoadContext()
	return LoadToolExecutionCompletePayload(data, ctx)
}
