// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"prompty/model"
)

// TestToolCallStartPayloadLoadJSON tests loading ToolCallStartPayload from JSON
func TestToolCallStartPayloadLoadJSON(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCallStartPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCallStartPayload: %v", err)
	}
	if instance.Id == nil || *instance.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, instance.Id)
	}
	if instance.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, instance.Name)
	}
	if instance.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, instance.Arguments)
	}
}

// TestToolCallStartPayloadLoadYAML tests loading ToolCallStartPayload from YAML
func TestToolCallStartPayloadLoadYAML(t *testing.T) {
	yamlData := `
id: call_abc123
name: get_weather
arguments: "{\"city\": \"Paris\"}"

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCallStartPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCallStartPayload: %v", err)
	}
	if instance.Id == nil || *instance.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, instance.Id)
	}
	if instance.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, instance.Name)
	}
	if instance.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, instance.Arguments)
	}
}

// TestToolCallStartPayloadRoundtrip tests load -> save -> load produces equivalent data
func TestToolCallStartPayloadRoundtrip(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCallStartPayload(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ToolCallStartPayload: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadToolCallStartPayload(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ToolCallStartPayload: %v", err)
	}
	if reloaded.Id == nil || *reloaded.Id != "call_abc123" {
		t.Errorf(`Expected Id to be "call_abc123", got %v`, reloaded.Id)
	}
	if reloaded.Name != "get_weather" {
		t.Errorf(`Expected Name to be "get_weather", got %v`, reloaded.Name)
	}
	if reloaded.Arguments != "{\"city\": \"Paris\"}" {
		t.Errorf(`Expected Arguments to be "{\"city\": \"Paris\"}", got %v`, reloaded.Arguments)
	}
}

// TestToolCallStartPayloadToJSON tests that ToJSON produces valid JSON
func TestToolCallStartPayloadToJSON(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCallStartPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCallStartPayload: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestToolCallStartPayloadToYAML tests that ToYAML produces valid YAML
func TestToolCallStartPayloadToYAML(t *testing.T) {
	jsonData := `
{
  "id": "call_abc123",
  "name": "get_weather",
  "arguments": "{\"city\": \"Paris\"}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadToolCallStartPayload(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolCallStartPayload: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
