// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

package prompty_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	prompty "prompty/model"
)

// TestUsageChunkLoadJSON tests loading UsageChunk from JSON
func TestUsageChunkLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "usage",
  "usage": {
    "inputTokens": 150,
    "outputTokens": 42,
    "totalTokens": 192
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadUsageChunk(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk: %v", err)
	}
	if instance.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, instance.Kind)
	}
}

// TestUsageChunkLoadYAML tests loading UsageChunk from YAML
func TestUsageChunkLoadYAML(t *testing.T) {
	yamlData := `
kind: usage
usage:
  inputTokens: 150
  outputTokens: 42
  totalTokens: 192

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadUsageChunk(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk: %v", err)
	}
	if instance.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, instance.Kind)
	}
}

// TestUsageChunkFromJSON tests loading UsageChunk through the generated JSON helper
func TestUsageChunkFromJSON(t *testing.T) {
	jsonData := `
{
  "kind": "usage",
  "usage": {
    "inputTokens": 150,
    "outputTokens": 42,
    "totalTokens": 192
  }
}
`

	instance, err := prompty.UsageChunkFromJSON(jsonData)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk from JSON helper: %v", err)
	}
	if instance.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, instance.Kind)
	}
}

// TestUsageChunkFromYAML tests loading UsageChunk through the generated YAML helper
func TestUsageChunkFromYAML(t *testing.T) {
	yamlData := `
kind: usage
usage:
  inputTokens: 150
  outputTokens: 42
  totalTokens: 192

`

	instance, err := prompty.UsageChunkFromYAML(yamlData)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk from YAML helper: %v", err)
	}
	if instance.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, instance.Kind)
	}
}

// TestUsageChunkRoundtrip tests load -> save -> load produces equivalent data
func TestUsageChunkRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "usage",
  "usage": {
    "inputTokens": 150,
    "outputTokens": 42,
    "totalTokens": 192
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := prompty.NewLoadContext()
	instance, err := prompty.LoadUsageChunk(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk: %v", err)
	}
	saveCtx := prompty.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := prompty.LoadUsageChunk(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload UsageChunk: %v", err)
	}
	if reloaded.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, reloaded.Kind)
	}
}

// TestUsageChunkToJSON tests that ToJSON produces valid JSON
func TestUsageChunkToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "usage",
  "usage": {
    "inputTokens": 150,
    "outputTokens": 42,
    "totalTokens": 192
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadUsageChunk(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}

	reloaded, err := prompty.LoadUsageChunk(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated JSON: %v", err)
	}
	if reloaded.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, reloaded.Kind)
	}
}

// TestUsageChunkToYAML tests that ToYAML produces valid YAML
func TestUsageChunkToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "usage",
  "usage": {
    "inputTokens": 150,
    "outputTokens": 42,
    "totalTokens": 192
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := prompty.NewLoadContext()
	instance, err := prompty.LoadUsageChunk(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load UsageChunk: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}

	reloaded, err := prompty.LoadUsageChunk(parsed, ctx)
	if err != nil {
		t.Fatalf("Failed to reload generated YAML: %v", err)
	}
	if reloaded.Kind != "usage" {
		t.Errorf(`Expected Kind to be "usage", got %v`, reloaded.Kind)
	}
}

// TestUsageChunkFromJSONInvalid rejects malformed JSON instead of silently defaulting
func TestUsageChunkFromJSONInvalid(t *testing.T) {
	if _, err := prompty.UsageChunkFromJSON("{"); err == nil {
		t.Fatalf("Expected malformed JSON to fail")
	}
}
