# <auto-generated by typra-emitter>
import json

import yaml

from prompty.model import TurnModelRequest


def test_load_json_turnmodelrequest():
    json_data = r"""
    {
      "sessionId": "sess_abc123",
      "turnId": "turn_abc123",
      "iteration": 0
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TurnModelRequest.load(data)
    assert instance is not None
    assert instance.session_id == "sess_abc123"
    assert instance.turn_id == "turn_abc123"
    assert instance.iteration == 0


def test_load_yaml_turnmodelrequest():
    yaml_data = r"""
    sessionId: sess_abc123
    turnId: turn_abc123
    iteration: 0

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = TurnModelRequest.load(data)
    assert instance is not None
    assert instance.session_id == "sess_abc123"
    assert instance.turn_id == "turn_abc123"
    assert instance.iteration == 0


def test_roundtrip_json_turnmodelrequest():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "sessionId": "sess_abc123",
      "turnId": "turn_abc123",
      "iteration": 0
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = TurnModelRequest.load(original_data)
    saved_data = instance.save()
    reloaded = TurnModelRequest.load(saved_data)
    assert reloaded is not None
    assert reloaded.session_id == "sess_abc123"
    assert reloaded.turn_id == "turn_abc123"
    assert reloaded.iteration == 0


def test_to_json_turnmodelrequest():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "sessionId": "sess_abc123",
      "turnId": "turn_abc123",
      "iteration": 0
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TurnModelRequest.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_turnmodelrequest():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "sessionId": "sess_abc123",
      "turnId": "turn_abc123",
      "iteration": 0
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TurnModelRequest.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
