# <auto-generated by typra-emitter>
import json

import yaml

from prompty.model import ModelReconciliationState


def test_load_json_modelreconciliationstate():
    json_data = r"""
    {
      "invocationId": "inv_abc123",
      "message": "provider connection dropped after request was sent"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ModelReconciliationState.load(data)
    assert instance is not None
    assert instance.invocation_id == "inv_abc123"
    assert instance.message == "provider connection dropped after request was sent"


def test_load_yaml_modelreconciliationstate():
    yaml_data = r"""
    invocationId: inv_abc123
    message: provider connection dropped after request was sent

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ModelReconciliationState.load(data)
    assert instance is not None
    assert instance.invocation_id == "inv_abc123"
    assert instance.message == "provider connection dropped after request was sent"


def test_roundtrip_json_modelreconciliationstate():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "invocationId": "inv_abc123",
      "message": "provider connection dropped after request was sent"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = ModelReconciliationState.load(original_data)
    saved_data = instance.save()
    reloaded = ModelReconciliationState.load(saved_data)
    assert reloaded is not None
    assert reloaded.invocation_id == "inv_abc123"
    assert reloaded.message == "provider connection dropped after request was sent"


def test_to_json_modelreconciliationstate():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "invocationId": "inv_abc123",
      "message": "provider connection dropped after request was sent"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ModelReconciliationState.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_modelreconciliationstate():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "invocationId": "inv_abc123",
      "message": "provider connection dropped after request was sent"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ModelReconciliationState.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
