# <auto-generated by typra-emitter>
import json

import yaml

from prompty.model import MemoryEntry


def test_load_json_memoryentry():
    json_data = r"""
    {
      "content": "The user prefers concise answers.",
      "category": {
        "kind": "preference"
      },
      "createdAt": "2026-06-09T20:00:00Z",
      "tags": [
        "preference",
        "tone"
      ],
      "importance": 0.8
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MemoryEntry.load(data)
    assert instance is not None
    assert instance.content == "The user prefers concise answers."
    assert instance.created_at == "2026-06-09T20:00:00Z"
    assert instance.importance == 0.8


def test_load_yaml_memoryentry():
    yaml_data = r"""
    content: The user prefers concise answers.
    category:
      kind: preference
    createdAt: "2026-06-09T20:00:00Z"
    tags:
      - preference
      - tone
    importance: 0.8

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = MemoryEntry.load(data)
    assert instance is not None
    assert instance.content == "The user prefers concise answers."
    assert instance.created_at == "2026-06-09T20:00:00Z"
    assert instance.importance == 0.8


def test_roundtrip_json_memoryentry():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "content": "The user prefers concise answers.",
      "category": {
        "kind": "preference"
      },
      "createdAt": "2026-06-09T20:00:00Z",
      "tags": [
        "preference",
        "tone"
      ],
      "importance": 0.8
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = MemoryEntry.load(original_data)
    saved_data = instance.save()
    reloaded = MemoryEntry.load(saved_data)
    assert reloaded is not None
    assert reloaded.content == "The user prefers concise answers."
    assert reloaded.created_at == "2026-06-09T20:00:00Z"
    assert reloaded.importance == 0.8


def test_to_json_memoryentry():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "content": "The user prefers concise answers.",
      "category": {
        "kind": "preference"
      },
      "createdAt": "2026-06-09T20:00:00Z",
      "tags": [
        "preference",
        "tone"
      ],
      "importance": 0.8
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MemoryEntry.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_memoryentry():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "content": "The user prefers concise answers.",
      "category": {
        "kind": "preference"
      },
      "createdAt": "2026-06-09T20:00:00Z",
      "tags": [
        "preference",
        "tone"
      ],
      "importance": 0.8
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MemoryEntry.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
