// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Linq;
using System.Text.Json;
using System.Threading;
using YamlDotNet.Serialization;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// Context passed to tool handlers during agent loop execution. Provides
    ///
    /// access to the agent configuration, current conversation state, and
    ///
    /// arbitrary metadata for tool implementations that need broader context.
    /// </summary>
public partial class ToolContext
{
    /// <summary>
    /// The shorthand property name for this type, if any.
    /// </summary>
    public static string? ShorthandProperty => null;

    /// <summary>
    /// Initializes a new instance of <see cref="ToolContext"/>.
    /// </summary>
#pragma warning disable CS8618
    public ToolContext()
    {
    }
#pragma warning restore CS8618

    /// <summary>
    /// The current conversation messages at the point of tool invocation
    /// </summary>
    public IList<Message> Messages { get; set; } = [];

    /// <summary>
    /// Optional metadata for tool-specific context (e.g., user session info)
    /// </summary>
    public IDictionary<string, object?>? Metadata { get; set; }


}
