// <auto-generated by typra-emitter>
#nullable enable

using Xunit;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130


public class SubscriptionInfoConversionTests
{
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
subscriptionId: sample
displayName: sample
state: sample

""";

        var instance = SubscriptionInfo.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("sample", instance.SubscriptionId);
        Assert.Equal("sample", instance.DisplayName);
        Assert.Equal("sample", instance.State);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "subscriptionId": "sample",
  "displayName": "sample",
  "state": "sample"
}
""";

        var instance = SubscriptionInfo.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("sample", instance.SubscriptionId);
        Assert.Equal("sample", instance.DisplayName);
        Assert.Equal("sample", instance.State);
    }

    [Fact]
    public void RoundtripJson()
    {
        // Test that FromJson -> ToJson -> FromJson produces equivalent data
        string jsonData = """
{
  "subscriptionId": "sample",
  "displayName": "sample",
  "state": "sample"
}
""";

        var original = SubscriptionInfo.FromJson(jsonData);
        Assert.NotNull(original);

        var json = original.ToJson();
        Assert.False(string.IsNullOrEmpty(json));

        var reloaded = SubscriptionInfo.FromJson(json);
        Assert.NotNull(reloaded);
        Assert.Equal("sample", reloaded.SubscriptionId);
        Assert.Equal("sample", reloaded.DisplayName);
        Assert.Equal("sample", reloaded.State);
    }

    [Fact]
    public void RoundtripYaml()
    {
        // Test that FromYaml -> ToYaml -> FromYaml produces equivalent data
        string yamlData = """
subscriptionId: sample
displayName: sample
state: sample

""";

        var original = SubscriptionInfo.FromYaml(yamlData);
        Assert.NotNull(original);

        var yaml = original.ToYaml();
        Assert.False(string.IsNullOrEmpty(yaml));

        var reloaded = SubscriptionInfo.FromYaml(yaml);
        Assert.NotNull(reloaded);
        Assert.Equal("sample", reloaded.SubscriptionId);
        Assert.Equal("sample", reloaded.DisplayName);
        Assert.Equal("sample", reloaded.State);
    }

    [Fact]
    public void ToJsonProducesValidJson()
    {
        string jsonData = """
{
  "subscriptionId": "sample",
  "displayName": "sample",
  "state": "sample"
}
""";

        var instance = SubscriptionInfo.FromJson(jsonData);
        var json = instance.ToJson();

        // Verify it's valid JSON by parsing it
        var parsed = System.Text.Json.JsonDocument.Parse(json);
        Assert.NotNull(parsed);
    }

    [Fact]
    public void ToYamlProducesValidYaml()
    {
        string yamlData = """
subscriptionId: sample
displayName: sample
state: sample

""";

        var instance = SubscriptionInfo.FromYaml(yamlData);
        var yaml = instance.ToYaml();

        // Verify it's valid YAML by parsing it
        var deserializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
        var parsed = deserializer.Deserialize<object>(yaml);
        Assert.NotNull(parsed);
    }
}
