emit:
  - "@typespec/json-schema"
  - "@prompty/emitter"
options:
  "@typespec/json-schema":
    emitter-output-dir: "{cwd}/tsp-output/json-schema"
    emitAllModels: true
    emitAllRefs: true
    file-type: yaml
  "@prompty/emitter":
    emitter-output-dir: "{cwd}/tsp-output"
    root-object: "Prompty.Core.Prompty"
    root-namespace: "Microsoft.Extensions.AI.Agents"
    root-alias: "Agent"
    emit-targets:
      - type: markdown
        output-dir: "./tsp-output/Markdown"

