// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

/// Timing information for a trace span.
public struct TraceTime {
  public static let shorthandProperty: String? = nil
  public var start: String = ""
  public var end: String = ""
  public var duration: Double = 0

  public init(start: String = "", end: String = "", duration: Double = 0) {
    self.start = start
    self.end = end
    self.duration = duration
  }

}
