// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "../context";
import { InvocationContextState } from "./invocation-context-state";
import { Message } from "../conversation/message";
import { ModelInvocationResponse } from "./model-invocation-response";
import { ModelReconciliationState } from "./model-reconciliation-state";
import { ModelToolRequest } from "./model-tool-request";
import { ModelToolResult } from "./model-tool-result";

export class EngineCheckpoint {
  static readonly shorthandProperty: string | undefined = undefined;

  id: string = "";
  sessionId: string = "";
  turnId: string = "";
  runId: string = "";
  parentRunId?: string | undefined;
  delegationDepth: number = 0;
  iteration: number = 0;
  lastSequence: number = 0;
  messages: Message[] = [];
  stablePrefixMessages: number = 0;
  inputs?: unknown | undefined;
  activeInvocationId?: string | undefined;
  pendingToolRequests?: ModelToolRequest[] = [];
  completedToolResults?: ModelToolResult[] = [];
  completedModelIterations: number = 0;
  reconciliationRequired: boolean = false;
  modelReconciliation?: ModelReconciliationState | undefined;
  pendingOutput?: unknown | undefined;
  finalOutputReady: boolean = false;
  pendingModelResponse?: ModelInvocationResponse | undefined;
  resumeSameIteration: boolean = false;
  policyAppliedForIteration: boolean = false;
  contextState!: InvocationContextState;
  metadata?: Record<string, unknown> | undefined;

  constructor(init?: Partial<EngineCheckpoint>) {
    this.id = init?.id ?? "";
    this.sessionId = init?.sessionId ?? "";
    this.turnId = init?.turnId ?? "";
    this.runId = init?.runId ?? "";
    if (init?.parentRunId !== undefined) {
      this.parentRunId = init.parentRunId;
    }
    this.delegationDepth = init?.delegationDepth ?? 0;
    this.iteration = init?.iteration ?? 0;
    this.lastSequence = init?.lastSequence ?? 0;
    this.messages = init?.messages ?? [];
    this.stablePrefixMessages = init?.stablePrefixMessages ?? 0;
    if (init?.inputs !== undefined) {
      this.inputs = init.inputs;
    }
    if (init?.activeInvocationId !== undefined) {
      this.activeInvocationId = init.activeInvocationId;
    }
    if (init?.pendingToolRequests !== undefined) {
      this.pendingToolRequests = init.pendingToolRequests;
    }
    if (init?.completedToolResults !== undefined) {
      this.completedToolResults = init.completedToolResults;
    }
    this.completedModelIterations = init?.completedModelIterations ?? 0;
    this.reconciliationRequired = init?.reconciliationRequired ?? false;
    if (init?.modelReconciliation !== undefined) {
      this.modelReconciliation = init.modelReconciliation;
    }
    if (init?.pendingOutput !== undefined) {
      this.pendingOutput = init.pendingOutput;
    }
    this.finalOutputReady = init?.finalOutputReady ?? false;
    if (init?.pendingModelResponse !== undefined) {
      this.pendingModelResponse = init.pendingModelResponse;
    }
    this.resumeSameIteration = init?.resumeSameIteration ?? false;
    this.policyAppliedForIteration = init?.policyAppliedForIteration ?? false;
    if (init?.contextState !== undefined) {
      this.contextState = init.contextState;
    }
    if (init?.metadata !== undefined) {
      this.metadata = init.metadata;
    }
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): EngineCheckpoint {
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    const instance = new EngineCheckpoint();

    if (data["id"] !== undefined && data["id"] !== null) {
      instance.id = String(data["id"]);
    }
    if (data["sessionId"] !== undefined && data["sessionId"] !== null) {
      instance.sessionId = String(data["sessionId"]);
    }
    if (data["turnId"] !== undefined && data["turnId"] !== null) {
      instance.turnId = String(data["turnId"]);
    }
    if (data["runId"] !== undefined && data["runId"] !== null) {
      instance.runId = String(data["runId"]);
    }
    if (data["parentRunId"] !== undefined && data["parentRunId"] !== null) {
      instance.parentRunId = String(data["parentRunId"]);
    }
    if (
      data["delegationDepth"] !== undefined &&
      data["delegationDepth"] !== null
    ) {
      instance.delegationDepth = Number(data["delegationDepth"]);
    }
    if (data["iteration"] !== undefined && data["iteration"] !== null) {
      instance.iteration = Number(data["iteration"]);
    }
    if (data["lastSequence"] !== undefined && data["lastSequence"] !== null) {
      instance.lastSequence = Number(data["lastSequence"]);
    }
    if (data["messages"] !== undefined && data["messages"] !== null) {
      instance.messages = EngineCheckpoint.loadMessages(
        data["messages"] as unknown[],
        context,
      );
    }
    if (
      data["stablePrefixMessages"] !== undefined &&
      data["stablePrefixMessages"] !== null
    ) {
      instance.stablePrefixMessages = Number(data["stablePrefixMessages"]);
    }
    if (data["inputs"] !== undefined && data["inputs"] !== null) {
      instance.inputs = data["inputs"] as unknown;
    }
    if (
      data["activeInvocationId"] !== undefined &&
      data["activeInvocationId"] !== null
    ) {
      instance.activeInvocationId = String(data["activeInvocationId"]);
    }
    if (
      data["pendingToolRequests"] !== undefined &&
      data["pendingToolRequests"] !== null
    ) {
      instance.pendingToolRequests = EngineCheckpoint.loadPendingToolRequests(
        data["pendingToolRequests"] as unknown[],
        context,
      );
    }
    if (
      data["completedToolResults"] !== undefined &&
      data["completedToolResults"] !== null
    ) {
      instance.completedToolResults = EngineCheckpoint.loadCompletedToolResults(
        data["completedToolResults"] as unknown[],
        context,
      );
    }
    if (
      data["completedModelIterations"] !== undefined &&
      data["completedModelIterations"] !== null
    ) {
      instance.completedModelIterations = Number(
        data["completedModelIterations"],
      );
    }
    if (
      data["reconciliationRequired"] !== undefined &&
      data["reconciliationRequired"] !== null
    ) {
      instance.reconciliationRequired = Boolean(data["reconciliationRequired"]);
    }
    if (
      data["modelReconciliation"] !== undefined &&
      data["modelReconciliation"] !== null
    ) {
      instance.modelReconciliation = ModelReconciliationState.load(
        data["modelReconciliation"] as Record<string, unknown>,
        context,
      );
    }
    if (data["pendingOutput"] !== undefined && data["pendingOutput"] !== null) {
      instance.pendingOutput = data["pendingOutput"] as unknown;
    }
    if (
      data["finalOutputReady"] !== undefined &&
      data["finalOutputReady"] !== null
    ) {
      instance.finalOutputReady = Boolean(data["finalOutputReady"]);
    }
    if (
      data["pendingModelResponse"] !== undefined &&
      data["pendingModelResponse"] !== null
    ) {
      instance.pendingModelResponse = ModelInvocationResponse.load(
        data["pendingModelResponse"] as Record<string, unknown>,
        context,
      );
    }
    if (
      data["resumeSameIteration"] !== undefined &&
      data["resumeSameIteration"] !== null
    ) {
      instance.resumeSameIteration = Boolean(data["resumeSameIteration"]);
    }
    if (
      data["policyAppliedForIteration"] !== undefined &&
      data["policyAppliedForIteration"] !== null
    ) {
      instance.policyAppliedForIteration = Boolean(
        data["policyAppliedForIteration"],
      );
    }
    if (data["contextState"] !== undefined && data["contextState"] !== null) {
      instance.contextState = InvocationContextState.load(
        data["contextState"] as Record<string, unknown>,
        context,
      );
    }
    if (data["metadata"] !== undefined && data["metadata"] !== null) {
      instance.metadata = data["metadata"] as Record<string, unknown>;
    }

    if (context) {
      return context.processOutput(instance) as EngineCheckpoint;
    }
    return instance;
  }

  static loadMessages(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): Message[] {
    if (!Array.isArray(data)) {
      // Convert dict/object format to array format
      const result: Record<string, unknown>[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push({ name: k, ...(v as Record<string, unknown>) });
        } else {
          result.push({ name: k, role: v });
        }
      }
      data = result;
    }
    return data.map((item) =>
      Message.load(item as Record<string, unknown>, context),
    );
  }

  static saveMessages(
    items: Message[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    // This type doesn't have a 'name' property, so always use array format
    return items.map((item) => item.save(context));
  }

  static loadPendingToolRequests(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): ModelToolRequest[] {
    if (!Array.isArray(data)) {
      // Convert dict/object format to array format
      const result: Record<string, unknown>[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push({ name: k, ...(v as Record<string, unknown>) });
        } else {
          result.push({ name: k, id: v });
        }
      }
      data = result;
    }
    return data.map((item) =>
      ModelToolRequest.load(item as Record<string, unknown>, context),
    );
  }

  static savePendingToolRequests(
    items: ModelToolRequest[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    if (context.collectionFormat === "array") {
      return items.map((item) => item.save(context));
    }

    // Object format: use name as key
    const result: Record<string, unknown> = {};
    for (const item of items) {
      const itemData = item.save(context) as Record<string, unknown>;
      const name = itemData["name"] as string | undefined;
      delete itemData["name"];
      if (name) {
        // Check if we can use shorthand (only primary property set)
        const shorthand = (item.constructor as typeof ModelToolRequest)
          .shorthandProperty;
        if (
          context.useShorthand &&
          shorthand &&
          Object.keys(itemData).length === 1 &&
          shorthand in itemData
        ) {
          result[name] = itemData[shorthand];
          continue;
        }
        result[name] = itemData;
      } else {
        // No name, fall back to array format for this item
        if (!result["_unnamed"]) {
          result["_unnamed"] = [];
        }
        (result["_unnamed"] as unknown[]).push(itemData);
      }
    }
    return result;
  }

  static loadCompletedToolResults(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): ModelToolResult[] {
    if (!Array.isArray(data)) {
      // Convert dict/object format to array format
      const result: Record<string, unknown>[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push({ name: k, ...(v as Record<string, unknown>) });
        } else {
          result.push({ name: k, requestId: v });
        }
      }
      data = result;
    }
    return data.map((item) =>
      ModelToolResult.load(item as Record<string, unknown>, context),
    );
  }

  static saveCompletedToolResults(
    items: ModelToolResult[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    if (context.collectionFormat === "array") {
      return items.map((item) => item.save(context));
    }

    // Object format: use name as key
    const result: Record<string, unknown> = {};
    for (const item of items) {
      const itemData = item.save(context) as Record<string, unknown>;
      const name = itemData["name"] as string | undefined;
      delete itemData["name"];
      if (name) {
        // Check if we can use shorthand (only primary property set)
        const shorthand = (item.constructor as typeof ModelToolResult)
          .shorthandProperty;
        if (
          context.useShorthand &&
          shorthand &&
          Object.keys(itemData).length === 1 &&
          shorthand in itemData
        ) {
          result[name] = itemData[shorthand];
          continue;
        }
        result[name] = itemData;
      } else {
        // No name, fall back to array format for this item
        if (!result["_unnamed"]) {
          result["_unnamed"] = [];
        }
        (result["_unnamed"] as unknown[]).push(itemData);
      }
    }
    return result;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    const result: Record<string, unknown> = {};

    if (obj.id !== undefined && obj.id !== null) {
      result["id"] = obj.id;
    }
    if (obj.sessionId !== undefined && obj.sessionId !== null) {
      result["sessionId"] = obj.sessionId;
    }
    if (obj.turnId !== undefined && obj.turnId !== null) {
      result["turnId"] = obj.turnId;
    }
    if (obj.runId !== undefined && obj.runId !== null) {
      result["runId"] = obj.runId;
    }
    if (obj.parentRunId !== undefined && obj.parentRunId !== null) {
      result["parentRunId"] = obj.parentRunId;
    }
    if (obj.delegationDepth !== undefined && obj.delegationDepth !== null) {
      result["delegationDepth"] = obj.delegationDepth;
    }
    if (obj.iteration !== undefined && obj.iteration !== null) {
      result["iteration"] = obj.iteration;
    }
    if (obj.lastSequence !== undefined && obj.lastSequence !== null) {
      result["lastSequence"] = obj.lastSequence;
    }
    if (obj.messages !== undefined && obj.messages !== null) {
      result["messages"] = EngineCheckpoint.saveMessages(obj.messages, context);
    }
    if (
      obj.stablePrefixMessages !== undefined &&
      obj.stablePrefixMessages !== null
    ) {
      result["stablePrefixMessages"] = obj.stablePrefixMessages;
    }
    if (obj.inputs !== undefined && obj.inputs !== null) {
      result["inputs"] = obj.inputs;
    }
    if (
      obj.activeInvocationId !== undefined &&
      obj.activeInvocationId !== null
    ) {
      result["activeInvocationId"] = obj.activeInvocationId;
    }
    if (
      obj.pendingToolRequests !== undefined &&
      obj.pendingToolRequests !== null
    ) {
      result["pendingToolRequests"] = EngineCheckpoint.savePendingToolRequests(
        obj.pendingToolRequests,
        context,
      );
    }
    if (
      obj.completedToolResults !== undefined &&
      obj.completedToolResults !== null
    ) {
      result["completedToolResults"] =
        EngineCheckpoint.saveCompletedToolResults(
          obj.completedToolResults,
          context,
        );
    }
    if (
      obj.completedModelIterations !== undefined &&
      obj.completedModelIterations !== null
    ) {
      result["completedModelIterations"] = obj.completedModelIterations;
    }
    if (
      obj.reconciliationRequired !== undefined &&
      obj.reconciliationRequired !== null
    ) {
      result["reconciliationRequired"] = obj.reconciliationRequired;
    }
    if (
      obj.modelReconciliation !== undefined &&
      obj.modelReconciliation !== null
    ) {
      result["modelReconciliation"] = obj.modelReconciliation.save(context);
    }
    if (obj.pendingOutput !== undefined && obj.pendingOutput !== null) {
      result["pendingOutput"] = obj.pendingOutput;
    }
    if (obj.finalOutputReady !== undefined && obj.finalOutputReady !== null) {
      result["finalOutputReady"] = obj.finalOutputReady;
    }
    if (
      obj.pendingModelResponse !== undefined &&
      obj.pendingModelResponse !== null
    ) {
      result["pendingModelResponse"] = obj.pendingModelResponse.save(context);
    }
    if (
      obj.resumeSameIteration !== undefined &&
      obj.resumeSameIteration !== null
    ) {
      result["resumeSameIteration"] = obj.resumeSameIteration;
    }
    if (
      obj.policyAppliedForIteration !== undefined &&
      obj.policyAppliedForIteration !== null
    ) {
      result["policyAppliedForIteration"] = obj.policyAppliedForIteration;
    }
    if (obj.contextState !== undefined && obj.contextState !== null) {
      result["contextState"] = obj.contextState.save(context);
    }
    if (obj.metadata !== undefined && obj.metadata !== null) {
      result["metadata"] = obj.metadata;
    }

    if (context) {
      return context.processDict(result);
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): EngineCheckpoint {
    const data = JSON.parse(json);
    return EngineCheckpoint.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): EngineCheckpoint {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return EngineCheckpoint.load(data as Record<string, unknown>, context);
  }

  //#endregion
}
