// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest
@testable import PromptyModel

final class EngineEventTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
{
  "id": "evt_abc123",
  "timestamp": "2025-01-01T00:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_abc123",
  "runId": "run_abc123"
}
"""
    let instance = try EngineEvent.fromJSON(json)
    XCTAssertEqual(instance.id, "evt_abc123")
    XCTAssertEqual(instance.timestamp, "2025-01-01T00:00:00Z")
    XCTAssertEqual(instance.sessionId, "sess_abc123")
    XCTAssertEqual(instance.turnId, "turn_abc123")
    XCTAssertEqual(instance.runId, "run_abc123")
    let reloaded = try EngineEvent.fromJSON(try instance.toJSON())
    XCTAssertEqual(reloaded.id, "evt_abc123")
    XCTAssertEqual(reloaded.timestamp, "2025-01-01T00:00:00Z")
    XCTAssertEqual(reloaded.sessionId, "sess_abc123")
    XCTAssertEqual(reloaded.turnId, "turn_abc123")
    XCTAssertEqual(reloaded.runId, "run_abc123")
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
id: evt_abc123
timestamp: "2025-01-01T00:00:00Z"
sessionId: sess_abc123
turnId: turn_abc123
runId: run_abc123

"""
    let instance = try EngineEvent.fromYAML(yaml)
    XCTAssertEqual(instance.id, "evt_abc123")
    XCTAssertEqual(instance.timestamp, "2025-01-01T00:00:00Z")
    XCTAssertEqual(instance.sessionId, "sess_abc123")
    XCTAssertEqual(instance.turnId, "turn_abc123")
    XCTAssertEqual(instance.runId, "run_abc123")
    let reloaded = try EngineEvent.fromYAML(try instance.toYAML())
    XCTAssertEqual(reloaded.id, "evt_abc123")
    XCTAssertEqual(reloaded.timestamp, "2025-01-01T00:00:00Z")
    XCTAssertEqual(reloaded.sessionId, "sess_abc123")
    XCTAssertEqual(reloaded.turnId, "turn_abc123")
    XCTAssertEqual(reloaded.runId, "run_abc123")
  }

}
