// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest
@testable import PromptyModel

final class FinalOutputPolicyRequestTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
{
  "sessionId": "sample",
  "turnId": "sample",
  "iteration": 1,
  "messages": []
}
"""
    let instance = try FinalOutputPolicyRequest.fromJSON(json)
    XCTAssertEqual(instance.sessionId, "sample")
    XCTAssertEqual(instance.turnId, "sample")
    XCTAssertEqual(instance.iteration, 1)
    XCTAssertEqual(instance.messages.count, 0)
    let reloaded = try FinalOutputPolicyRequest.fromJSON(try instance.toJSON())
    XCTAssertEqual(reloaded.sessionId, "sample")
    XCTAssertEqual(reloaded.turnId, "sample")
    XCTAssertEqual(reloaded.iteration, 1)
    XCTAssertEqual(reloaded.messages.count, 0)
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
sessionId: sample
turnId: sample
iteration: 1
messages: []

"""
    let instance = try FinalOutputPolicyRequest.fromYAML(yaml)
    XCTAssertEqual(instance.sessionId, "sample")
    XCTAssertEqual(instance.turnId, "sample")
    XCTAssertEqual(instance.iteration, 1)
    XCTAssertEqual(instance.messages.count, 0)
    let reloaded = try FinalOutputPolicyRequest.fromYAML(try instance.toYAML())
    XCTAssertEqual(reloaded.sessionId, "sample")
    XCTAssertEqual(reloaded.turnId, "sample")
    XCTAssertEqual(reloaded.iteration, 1)
    XCTAssertEqual(reloaded.messages.count, 0)
  }

}
