// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest

@testable import PromptyModel

final class ReplayMismatchTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
      {
        "index": 1,
        "message": "sample"
      }
      """
    let instance = try ReplayMismatch.fromJSON(json)
    XCTAssertEqual(instance.index, 1)
    XCTAssertEqual(instance.message, "sample")
    let reloaded = try ReplayMismatch.fromJSON(try instance.toJSON())
    XCTAssertEqual(reloaded.index, 1)
    XCTAssertEqual(reloaded.message, "sample")
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
      index: 1
      message: sample

      """
    let instance = try ReplayMismatch.fromYAML(yaml)
    XCTAssertEqual(instance.index, 1)
    XCTAssertEqual(instance.message, "sample")
    let reloaded = try ReplayMismatch.fromYAML(try instance.toYAML())
    XCTAssertEqual(reloaded.index, 1)
    XCTAssertEqual(reloaded.message, "sample")
  }

}
