// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest

@testable import PromptyModel

final class RetryPolicyRequestTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
      {
        "failedAttempts": 1,
        "nextAttempt": 1,
        "maxAttempts": 1,
        "reason": "sample"
      }
      """
    let instance = try RetryPolicyRequest.fromJSON(json)
    XCTAssertEqual(instance.failedAttempts, 1)
    XCTAssertEqual(instance.nextAttempt, 1)
    XCTAssertEqual(instance.maxAttempts, 1)
    XCTAssertEqual(instance.reason, "sample")
    let reloaded = try RetryPolicyRequest.fromJSON(try instance.toJSON())
    XCTAssertEqual(reloaded.failedAttempts, 1)
    XCTAssertEqual(reloaded.nextAttempt, 1)
    XCTAssertEqual(reloaded.maxAttempts, 1)
    XCTAssertEqual(reloaded.reason, "sample")
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
      failedAttempts: 1
      nextAttempt: 1
      maxAttempts: 1
      reason: sample

      """
    let instance = try RetryPolicyRequest.fromYAML(yaml)
    XCTAssertEqual(instance.failedAttempts, 1)
    XCTAssertEqual(instance.nextAttempt, 1)
    XCTAssertEqual(instance.maxAttempts, 1)
    XCTAssertEqual(instance.reason, "sample")
    let reloaded = try RetryPolicyRequest.fromYAML(try instance.toYAML())
    XCTAssertEqual(reloaded.failedAttempts, 1)
    XCTAssertEqual(reloaded.nextAttempt, 1)
    XCTAssertEqual(reloaded.maxAttempts, 1)
    XCTAssertEqual(reloaded.reason, "sample")
  }

}
