// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

/// Payload for "compaction_start" events — context compaction is beginning.
public struct CompactionStartPayload {
  public static let shorthandProperty: String? = nil
  public var droppedCount: Int32 = 0

  public init(droppedCount: Int32 = 0) {
    self.droppedCount = droppedCount
  }

}
