// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

public enum StreamChunk: TypraModel {
  case textChunk(TextChunk)
  case thinkingChunk(ThinkingChunk)
  case toolChunk(ToolChunk)
  case usageChunk(UsageChunk)
  case errorChunk(ErrorChunk)

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> StreamChunk {
    let normalizedData: Any = data
    let object = try TypraRuntime.object(normalizedData, typeName: "StreamChunk")
    let discriminator = try TypraRuntime.string(object["kind"] ?? NSNull(), field: "kind")
    if discriminator.isEmpty {
      throw TypraRuntimeError.invalidField(field: context.at("kind").path, expected: "non-blank string")
    }
    switch discriminator {
    case "text": return .textChunk(try TextChunk.load(normalizedData, context: context))
    case "thinking": return .thinkingChunk(try ThinkingChunk.load(normalizedData, context: context))
    case "tool": return .toolChunk(try ToolChunk.load(normalizedData, context: context))
    case "usage": return .usageChunk(try UsageChunk.load(normalizedData, context: context))
    case "error": return .errorChunk(try ErrorChunk.load(normalizedData, context: context))
    default: throw TypraRuntimeError.unknownDiscriminator(type: "StreamChunk", field: "kind", value: discriminator)
    }
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    switch self {
    case .textChunk(let value): return try value.save(context)
    case .thinkingChunk(let value): return try value.save(context)
    case .toolChunk(let value): return try value.save(context)
    case .usageChunk(let value): return try value.save(context)
    case .errorChunk(let value): return try value.save(context)
    }
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> StreamChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "StreamChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> StreamChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "StreamChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}

/// A text content chunk from the LLM response stream.
public struct TextChunk: TypraModel {
  public static let shorthandProperty: String? = nil
  public var kind: String = "text"
  public var value: String = ""

  public init(kind: String = "text", value: String = "") {
    self.kind = kind
    self.value = value
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> TextChunk {
    let object = try TypraRuntime.object(data, typeName: "TextChunk")
    var instance = TextChunk()
    if let value = object["kind"] {
      instance.kind = try TypraRuntime.string(value, field: "kind")
    }
    else {
      instance.kind = "text"
    }
    if let value = object["value"] {
      instance.value = try TypraRuntime.string(value, field: "value")
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["kind"] = self.kind
    result["value"] = self.value
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> TextChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "TextChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> TextChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "TextChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}

/// A thinking/reasoning content chunk from the LLM response stream.
public struct ThinkingChunk: TypraModel {
  public static let shorthandProperty: String? = nil
  public var kind: String = "thinking"
  public var value: String = ""

  public init(kind: String = "thinking", value: String = "") {
    self.kind = kind
    self.value = value
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ThinkingChunk {
    let object = try TypraRuntime.object(data, typeName: "ThinkingChunk")
    var instance = ThinkingChunk()
    if let value = object["kind"] {
      instance.kind = try TypraRuntime.string(value, field: "kind")
    }
    else {
      instance.kind = "thinking"
    }
    if let value = object["value"] {
      instance.value = try TypraRuntime.string(value, field: "value")
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["kind"] = self.kind
    result["value"] = self.value
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> ThinkingChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "ThinkingChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> ThinkingChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "ThinkingChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}

/// A tool call chunk from the LLM response stream.
public struct ToolChunk: TypraModel {
  public static let shorthandProperty: String? = nil
  public var kind: String = "tool"
  public var toolCall: ToolCall = ToolCall()

  public init(kind: String = "tool", toolCall: ToolCall = ToolCall()) {
    self.kind = kind
    self.toolCall = toolCall
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ToolChunk {
    let object = try TypraRuntime.object(data, typeName: "ToolChunk")
    var instance = ToolChunk()
    if let value = object["kind"] {
      instance.kind = try TypraRuntime.string(value, field: "kind")
    }
    else {
      instance.kind = "tool"
    }
    if object["toolCall"] == nil || object["toolCall"] is NSNull {
      throw TypraRuntimeError.unsupported(context.at("toolCall").path + ": missing required field")
    }
    if let value = object["toolCall"] {
      instance.toolCall = try ToolCall.load(value, context: context.at("toolCall"))
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["kind"] = self.kind
    result["toolCall"] = try self.toolCall.save(context)
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> ToolChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "ToolChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> ToolChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "ToolChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}

/// Cumulative token usage emitted once after provider content and tool chunks.
public struct UsageChunk: TypraModel {
  public static let shorthandProperty: String? = nil
  public var kind: String = "usage"
  public var usage: InvocationUsage = InvocationUsage()

  public init(kind: String = "usage", usage: InvocationUsage = InvocationUsage()) {
    self.kind = kind
    self.usage = usage
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> UsageChunk {
    let object = try TypraRuntime.object(data, typeName: "UsageChunk")
    var instance = UsageChunk()
    if let value = object["kind"] {
      instance.kind = try TypraRuntime.string(value, field: "kind")
    }
    else {
      instance.kind = "usage"
    }
    if object["usage"] == nil || object["usage"] is NSNull {
      throw TypraRuntimeError.unsupported(context.at("usage").path + ": missing required field")
    }
    if let value = object["usage"] {
      instance.usage = try InvocationUsage.load(value, context: context.at("usage"))
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["kind"] = self.kind
    result["usage"] = try self.usage.save(context)
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> UsageChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "UsageChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> UsageChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "UsageChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}

/// An error chunk from the LLM response stream.
public struct ErrorChunk: TypraModel {
  public static let shorthandProperty: String? = nil
  public var kind: String = "error"
  public var message: String = ""

  public init(kind: String = "error", message: String = "") {
    self.kind = kind
    self.message = message
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ErrorChunk {
    let object = try TypraRuntime.object(data, typeName: "ErrorChunk")
    var instance = ErrorChunk()
    if let value = object["kind"] {
      instance.kind = try TypraRuntime.string(value, field: "kind")
    }
    else {
      instance.kind = "error"
    }
    if let value = object["message"] {
      instance.message = try TypraRuntime.string(value, field: "message")
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["kind"] = self.kind
    result["message"] = self.message
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> ErrorChunk {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "ErrorChunk"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> ErrorChunk {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "ErrorChunk"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}
