// <auto-generated by typra-emitter>
using Xunit;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130


public class HookEndPayloadConversionTests
{
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
hookInvocationId: hook_abc123
hookType: preToolUse
success: true
durationMs: 12
error: hook failed

""";

        var instance = HookEndPayload.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("hook_abc123", instance.HookInvocationId);
        Assert.Equal("preToolUse", instance.HookType);
        Assert.True(instance.Success);
        Assert.Equal(12, instance.DurationMs);
        Assert.Equal("hook failed", instance.Error);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
""";

        var instance = HookEndPayload.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("hook_abc123", instance.HookInvocationId);
        Assert.Equal("preToolUse", instance.HookType);
        Assert.True(instance.Success);
        Assert.Equal(12, instance.DurationMs);
        Assert.Equal("hook failed", instance.Error);
    }

    [Fact]
    public void RoundtripJson()
    {
        // Test that FromJson -> ToJson -> FromJson produces equivalent data
        string jsonData = """
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
""";

        var original = HookEndPayload.FromJson(jsonData);
        Assert.NotNull(original);

        var json = original.ToJson();
        Assert.False(string.IsNullOrEmpty(json));

        var reloaded = HookEndPayload.FromJson(json);
        Assert.NotNull(reloaded);
        Assert.Equal("hook_abc123", reloaded.HookInvocationId);
        Assert.Equal("preToolUse", reloaded.HookType);
        Assert.True(reloaded.Success);
        Assert.Equal(12, reloaded.DurationMs);
        Assert.Equal("hook failed", reloaded.Error);
    }

    [Fact]
    public void RoundtripYaml()
    {
        // Test that FromYaml -> ToYaml -> FromYaml produces equivalent data
        string yamlData = """
hookInvocationId: hook_abc123
hookType: preToolUse
success: true
durationMs: 12
error: hook failed

""";

        var original = HookEndPayload.FromYaml(yamlData);
        Assert.NotNull(original);

        var yaml = original.ToYaml();
        Assert.False(string.IsNullOrEmpty(yaml));

        var reloaded = HookEndPayload.FromYaml(yaml);
        Assert.NotNull(reloaded);
        Assert.Equal("hook_abc123", reloaded.HookInvocationId);
        Assert.Equal("preToolUse", reloaded.HookType);
        Assert.True(reloaded.Success);
        Assert.Equal(12, reloaded.DurationMs);
        Assert.Equal("hook failed", reloaded.Error);
    }

    [Fact]
    public void ToJsonProducesValidJson()
    {
        string jsonData = """
{
  "hookInvocationId": "hook_abc123",
  "hookType": "preToolUse",
  "success": true,
  "durationMs": 12,
  "error": "hook failed"
}
""";

        var instance = HookEndPayload.FromJson(jsonData);
        var json = instance.ToJson();

        // Verify it's valid JSON by parsing it
        var parsed = System.Text.Json.JsonDocument.Parse(json);
        Assert.NotNull(parsed);
    }

    [Fact]
    public void ToYamlProducesValidYaml()
    {
        string yamlData = """
hookInvocationId: hook_abc123
hookType: preToolUse
success: true
durationMs: 12
error: hook failed

""";

        var instance = HookEndPayload.FromYaml(yamlData);
        var yaml = instance.ToYaml();

        // Verify it's valid YAML by parsing it
        var deserializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
        var parsed = deserializer.Deserialize<object>(yaml);
        Assert.NotNull(parsed);
    }
}
