// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

public enum EngineTurnStatus: String, Codable, CaseIterable {
  case success = "success"
  case failed = "failed"
  case cancelled = "cancelled"
  case reconciliationRequired = "reconciliation_required"
  public static func parse(_ value: String) throws -> EngineTurnStatus {
    switch value {
    case "success": return .success
    case "failed": return .failed
    case "cancelled": return .cancelled
    case "reconciliation_required": return .reconciliationRequired
    default: throw TypraRuntimeError.invalidEnum(type: "EngineTurnStatus", value: value)
    }
  }
}

/// The committed outcome of a turn handed to post-commit consumers.
public struct TurnCommit: TypraModel {
  public var sessionId: String = ""
  public var turnId: String = ""
  public var status: EngineTurnStatus = (try! EngineTurnStatus.parse("success"))
  public var output: Any? = nil
  public var messages: [Message] = []
  public var iterations: Int32 = 0
  public var lastSequence: Int64 = 0
  public var contextState: InvocationContextState = InvocationContextState()
  public var modelReconciliation: ModelReconciliationState? = nil

  public init(
    sessionId: String = "", turnId: String = "",
    status: EngineTurnStatus = (try! EngineTurnStatus.parse("success")), output: Any? = nil,
    messages: [Message] = [], iterations: Int32 = 0, lastSequence: Int64 = 0,
    contextState: InvocationContextState = InvocationContextState(),
    modelReconciliation: ModelReconciliationState? = nil
  ) {
    self.sessionId = sessionId
    self.turnId = turnId
    self.status = status
    self.output = output
    self.messages = messages
    self.iterations = iterations
    self.lastSequence = lastSequence
    self.contextState = contextState
    self.modelReconciliation = modelReconciliation
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> TurnCommit {
    let object = try TypraRuntime.object(data, typeName: "TurnCommit")
    var instance = TurnCommit()
    if let value = object["sessionId"] {
      instance.sessionId = try TypraRuntime.string(value, field: "sessionId")
    }
    if let value = object["turnId"] {
      instance.turnId = try TypraRuntime.string(value, field: "turnId")
    }
    if let value = object["status"] {
      instance.status = try EngineTurnStatus.parse(try TypraRuntime.string(value, field: "status"))
    }
    if let value = object["output"] {
      instance.output = value
    }
    if let value = object["messages"] {
      instance.messages = try TypraRuntime.array(value, field: "messages").map {
        try Message.load($0, context: context)
      }
    }
    if let value = object["iterations"] {
      instance.iterations = try TypraRuntime.int32(value, field: "iterations")
    }
    if let value = object["lastSequence"] {
      instance.lastSequence = try TypraRuntime.int64(value, field: "lastSequence")
    }
    if let value = object["contextState"] {
      instance.contextState = try InvocationContextState.load(value, context: context)
    }
    if let value = object["modelReconciliation"] {
      instance.modelReconciliation = try ModelReconciliationState.load(value, context: context)
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["sessionId"] = self.sessionId
    result["turnId"] = self.turnId
    result["status"] = self.status.rawValue
    if let value = self.output {
      result["output"] = value
    }
    result["messages"] = try self.messages.map { try $0.save(context) }
    result["iterations"] = self.iterations
    result["lastSequence"] = self.lastSequence
    result["contextState"] = try self.contextState.save(context)
    if let value = self.modelReconciliation {
      result["modelReconciliation"] = try value.save(context)
    }
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws
    -> TurnCommit
  {
    return try load(TypraRuntime.jsonObject(from: json, typeName: "TurnCommit"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws
    -> TurnCommit
  {
    return try load(TypraRuntime.yamlObject(from: yaml, typeName: "TurnCommit"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}
