// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "../../context";

export class AuthorizationCodeFlow {
  static readonly shorthandProperty: string | undefined = undefined;

  authUrl: string = "";
  codeVerifier: string = "";

  constructor(init?: Partial<AuthorizationCodeFlow>) {
    this.authUrl = init?.authUrl ?? "";
    this.codeVerifier = init?.codeVerifier ?? "";
  }

  //#region Load Methods

  static load(data: Record<string, unknown>, context?: LoadContext): AuthorizationCodeFlow {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    const instance = new AuthorizationCodeFlow();

    if (data["authUrl"] !== undefined && data["authUrl"] !== null) {
      instance.authUrl = String(data["authUrl"]);
    }
    if (data["codeVerifier"] !== undefined && data["codeVerifier"] !== null) {
      instance.codeVerifier = String(data["codeVerifier"]);
    }

    if (context) {
      return context.processOutput(instance) as AuthorizationCodeFlow;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    const result: Record<string, unknown> = {};

    if (obj.authUrl !== undefined && obj.authUrl !== null) {
      result["authUrl"] = obj.authUrl;
    }
    if (obj.codeVerifier !== undefined && obj.codeVerifier !== null) {
      result["codeVerifier"] = obj.codeVerifier;
    }

    if (context) {
      return context.processDict(result);
    }
    return result;
  }

  toWire(provider: string): Record<string, unknown> {
    const data = this.save();
    const result: Record<string, unknown> = {};
    const wireMap: Record<string, Record<string, string>> = {
      "authUrl": { "foundry": "auth_url" },
      "codeVerifier": { "foundry": "code_verifier" },
    };
    for (const [key, value] of Object.entries(data)) {
      const mapping = wireMap[key];
      if (mapping?.[provider]) {
        result[mapping[provider]] = value;
      }
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): AuthorizationCodeFlow {
    const data = JSON.parse(json);
    return AuthorizationCodeFlow.load(data as Record<string, unknown>, context);
  }

  static fromYaml(yaml: string, context?: LoadContext): AuthorizationCodeFlow {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return AuthorizationCodeFlow.load(data as Record<string, unknown>, context);
  }

  //#endregion
}
