##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, ClassVar

from .._context import LoadContext, SaveContext
from ._RedactionMetadata import RedactionMetadata


@dataclass
class PermissionCompletedPayload:
    """Payload for permission completion events — an approval decision was made.

    Attributes
    ----------
    request_id : Optional[str]
        Stable permission request identifier
    tool_call_id : Optional[str]
        Associated tool call identifier, when the permission gated a tool call
    permission : str
        Permission/action name that was decided
    approved : bool
        Whether the requested permission was approved
    reason : Optional[str]
        Decision reason, if available
    result : Optional[dict[str, Any]]
        Host-specific decision result, such as a durable approval token or denial details
    redaction : Optional[RedactionMetadata]
        Redaction state for sensitive decision fields
    """

    _shorthand_property: ClassVar[str | None] = None

    request_id: str | None = None
    tool_call_id: str | None = None
    permission: str = field(default="")
    approved: bool = field(default=False)
    reason: str | None = None
    result: dict[str, Any] | None = None
    redaction: RedactionMetadata | None = None

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "PermissionCompletedPayload":
        """Load a PermissionCompletedPayload instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            PermissionCompletedPayload: The loaded PermissionCompletedPayload instance.

        """

        if context is not None:
            data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for PermissionCompletedPayload: {data}")

        # create new instance
        instance = PermissionCompletedPayload()

        if data is not None and "requestId" in data:
            instance.request_id = data["requestId"]
        if data is not None and "toolCallId" in data:
            instance.tool_call_id = data["toolCallId"]
        if data is not None and "permission" in data:
            instance.permission = data["permission"]
        if data is not None and "approved" in data:
            instance.approved = data["approved"]
        if data is not None and "reason" in data:
            instance.reason = data["reason"]
        if data is not None and "result" in data:
            instance.result = data["result"]
        if data is not None and "redaction" in data:
            instance.redaction = RedactionMetadata.load(data["redaction"], context)
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the PermissionCompletedPayload instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.request_id is not None:
            result["requestId"] = obj.request_id
        if obj.tool_call_id is not None:
            result["toolCallId"] = obj.tool_call_id
        if obj.permission is not None:
            result["permission"] = obj.permission
        if obj.approved is not None:
            result["approved"] = obj.approved
        if obj.reason is not None:
            result["reason"] = obj.reason
        if obj.result is not None:
            result["result"] = obj.result
        if obj.redaction is not None:
            result["redaction"] = obj.redaction.save(context)

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the PermissionCompletedPayload instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the PermissionCompletedPayload instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
