# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass
from typing import Any, ClassVar

from ...contracts.events._HostToolRequest import HostToolRequest
from ...contracts.models._InvocationUsage import InvocationUsage


@dataclass
class TurnModelResponse:
    """Response returned by the injected model callback to the reference turn runner.

    Attributes
    ----------
    output : Optional[Any]
        Provider-neutral final model output for the turn when no more tools are requested
    usage : Optional[InvocationUsage]
        Complete cumulative token usage reported for this model invocation, when available
    tool_requests : Optional[list[HostToolRequest]]
        Host tool execution requests emitted by the model callback
    checkpoint_state : Optional[dict[str, Any]]
        Additional deterministic state to merge into the iteration checkpoint. Values may be explicit null.
    """

    _shorthand_property: ClassVar[str | None] = None

    output: Any | None = None
    usage: InvocationUsage | None = None
    tool_requests: list[HostToolRequest] | None = None
    checkpoint_state: dict[str, Any] | None = None
