// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Threading;
using System.Threading.Tasks;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// Executes authorized model-requested tools at a runtime cancellation boundary.
    /// </summary>
    public interface IEngineToolPort
    {
        /// <summary>
        /// Execute one authorized model-requested tool
        /// </summary>
        Task<ModelToolResult> ExecuteAsync(ModelToolRequest request, CancellationToken cancellationToken = default);
    }
