// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Threading;
using System.Threading.Tasks;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// Authorizes model-requested tools at a runtime cancellation boundary.
    /// </summary>
    public interface IEnginePermissionPort
    {
        /// <summary>
        /// Authorize one model-requested tool before execution
        /// </summary>
        Task<EnginePermissionDecision> AuthorizeAsync(ModelToolRequest request, CancellationToken cancellationToken = default);
    }
