// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
#nullable enable

using System.Threading;
using System.Threading.Tasks;

#pragma warning disable IDE0130
namespace Prompty.Core;
#pragma warning restore IDE0130

    /// <summary>
    /// Persists semantic engine events and checkpoints without runtime cancellation.
    /// </summary>
    public interface IEngineDurabilityPort
    {
        /// <summary>
        /// Append one semantic engine event durably
        /// </summary>
        Task AppendAsync(EngineEvent @event);
        /// <summary>
        /// Atomically append semantic engine events and persist the checkpoint that reflects them
        /// </summary>
        Task AppendWithCheckpointAsync(List<EngineEvent> events, EngineCheckpoint checkpoint);
    }
