// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "../../context";
import { Message } from "../../contracts/conversation/message";

export class MessagesUpdatedPayload {
  static readonly shorthandProperty: string | undefined = undefined;

  messages?: Message[];
  reason?: string | undefined;
  appended?: Message[];
  removed?: number | undefined;

  constructor(init?: Partial<MessagesUpdatedPayload>) {
    if (init?.messages !== undefined) {
      this.messages = init.messages;
    }
    if (init?.reason !== undefined) {
      this.reason = init.reason;
    }
    if (init?.appended !== undefined) {
      this.appended = init.appended;
    }
    if (init?.removed !== undefined) {
      this.removed = init.removed;
    }
  }

  //#region Load Methods

  static load(
    data: Record<string, unknown>,
    context?: LoadContext,
  ): MessagesUpdatedPayload {
    context ??= new LoadContext();
    if (context) {
      data = context.processInput(data) as Record<string, unknown>;
    }

    const instance = new MessagesUpdatedPayload();

    if (data["messages"] !== undefined && data["messages"] !== null) {
      instance.messages = MessagesUpdatedPayload.loadMessages(
        data["messages"] as unknown[],
        context.at("messages"),
      );
    }
    if (data["reason"] !== undefined && data["reason"] !== null) {
      instance.reason = String(data["reason"]);
    }
    if (data["appended"] !== undefined && data["appended"] !== null) {
      instance.appended = MessagesUpdatedPayload.loadAppended(
        data["appended"] as unknown[],
        context.at("appended"),
      );
    }
    if (data["removed"] !== undefined && data["removed"] !== null) {
      instance.removed = Number(data["removed"]);
    }

    if (context) {
      return context.processOutput(instance) as MessagesUpdatedPayload;
    }
    return instance;
  }

  static loadMessages(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): Message[] {
    context ??= new LoadContext({ path: "messages" });
    if (!Array.isArray(data)) {
      const result: Message[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (Array.isArray(v)) {
          throw new TypeError(
            context.at(k).path +
              ": invalid named collection entry category array",
          );
        }
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push(
            Message.load(
              { name: k, ...(v as Record<string, unknown>) },
              context.at(k),
            ),
          );
        } else {
          result.push(Message.load({ name: k, role: v }, context.at(k)));
        }
      }
      return result;
    }
    return data.map((item, index) =>
      Message.load(item as Record<string, unknown>, context.atIndex(index)),
    );
  }

  static saveMessages(
    items: Message[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    // This type doesn't have a 'name' property, so always use array format
    return items.map((item) => item.save(context));
  }

  static loadAppended(
    data: Record<string, unknown>[] | unknown[],
    context?: LoadContext,
  ): Message[] {
    context ??= new LoadContext({ path: "appended" });
    if (!Array.isArray(data)) {
      const result: Message[] = [];
      for (const [k, v] of Object.entries(data)) {
        if (Array.isArray(v)) {
          throw new TypeError(
            context.at(k).path +
              ": invalid named collection entry category array",
          );
        }
        if (typeof v === "object" && v !== null && !Array.isArray(v)) {
          result.push(
            Message.load(
              { name: k, ...(v as Record<string, unknown>) },
              context.at(k),
            ),
          );
        } else {
          result.push(Message.load({ name: k, role: v }, context.at(k)));
        }
      }
      return result;
    }
    return data.map((item, index) =>
      Message.load(item as Record<string, unknown>, context.atIndex(index)),
    );
  }

  static saveAppended(
    items: Message[],
    context?: SaveContext,
  ): Record<string, unknown>[] | Record<string, unknown> {
    if (!context) {
      context = new SaveContext();
    }

    // This type doesn't have a 'name' property, so always use array format
    return items.map((item) => item.save(context));
  }

  //#endregion

  //#region Save Methods

  save(context?: SaveContext): Record<string, unknown> {
    let obj: this = this;
    if (context) {
      obj = context.processObject(obj) as this;
    }

    const result: Record<string, unknown> = {};

    if (obj.messages !== undefined && obj.messages !== null) {
      result["messages"] = MessagesUpdatedPayload.saveMessages(
        obj.messages,
        context,
      );
    }
    if (obj.reason !== undefined && obj.reason !== null) {
      result["reason"] = obj.reason;
    }
    if (obj.appended !== undefined && obj.appended !== null) {
      result["appended"] = MessagesUpdatedPayload.saveAppended(
        obj.appended,
        context,
      );
    }
    if (obj.removed !== undefined && obj.removed !== null) {
      result["removed"] = obj.removed;
    }

    if (context) {
      return context.processDict(result);
    }
    return result;
  }

  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  static fromJson(json: string, context?: LoadContext): MessagesUpdatedPayload {
    const data = JSON.parse(json);
    return MessagesUpdatedPayload.load(
      data as Record<string, unknown>,
      context,
    );
  }

  static fromYaml(yaml: string, context?: LoadContext): MessagesUpdatedPayload {
    const { parse } = require("yaml");
    const data = parse(yaml);
    return MessagesUpdatedPayload.load(
      data as Record<string, unknown>,
      context,
    );
  }

  //#endregion
}
