// <auto-generated by typra-emitter>
// <auto-generated/>
// Code generated by Typra emitter; DO NOT EDIT.

using System;
using System.Text.Json.Serialization;

namespace Prompty.Core;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum McpApprovalModeKind
{
    [JsonPropertyName("always")]
    Always,

    [JsonPropertyName("never")]
    Never,

    [JsonPropertyName("specify")]
    Specify,

}

public static class McpApprovalModeKindParser
{
    public static McpApprovalModeKind Parse(string value)
    {
        return value switch
        {
            "always" => McpApprovalModeKind.Always,
            "never" => McpApprovalModeKind.Never,
            "specify" => McpApprovalModeKind.Specify,
            _ => Enum.Parse<McpApprovalModeKind>(value, true),
        };
    }

    public static string ToValue(McpApprovalModeKind value)
    {
        return value switch
        {
            McpApprovalModeKind.Always => "always",
            McpApprovalModeKind.Never => "never",
            McpApprovalModeKind.Specify => "specify",
            _ => value.ToString().ToLowerInvariant(),
        };
    }
}
