# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from typing import Protocol, runtime_checkable

from ._EnginePermissionDecision import EnginePermissionDecision
from ._ModelToolRequest import ModelToolRequest
from prompty.core.cancellation import CancellationToken


@runtime_checkable
class EnginePermissionPort(Protocol):
    """Authorizes model-requested tools at a runtime cancellation boundary.
    """

    def authorize(self, request: ModelToolRequest, cancellation: CancellationToken | None = None) -> EnginePermissionDecision:
        """Authorize one model-requested tool before execution"""
        raise NotImplementedError

    async def authorize_async(self, request: ModelToolRequest, cancellation: CancellationToken | None = None) -> EnginePermissionDecision:
        """Authorize one model-requested tool before execution (async variant)"""
        raise NotImplementedError
