// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

/// Final output supplied to the host policy immediately before a success commit.
public struct FinalOutputPolicyRequest {
  public static let shorthandProperty: String? = nil
  public var sessionId: String = ""
  public var turnId: String = ""
  public var iteration: Int32 = 0
  public var messages: [Message] = []
  public var output: Any? = nil
  public var inputs: Any? = nil

  public init(sessionId: String = "", turnId: String = "", iteration: Int32 = 0, messages: [Message] = [], output: Any? = nil, inputs: Any? = nil) {
    self.sessionId = sessionId
    self.turnId = turnId
    self.iteration = iteration
    self.messages = messages
    self.output = output
    self.inputs = inputs
  }

}
