// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use prompty::model::LlmCompletePayload;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_llm_complete_payload_load_json() {
    let json = r####"
{
  "requestId": "req_abc123",
  "serviceRequestId": "srv_abc123",
  "durationMs": 820
}
"####;
    let ctx = LoadContext::default();
    let result = LlmCompletePayload::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.request_id.is_some(),
        "Expected request_id to be Some"
    );
    assert_eq!(instance.request_id.as_ref().unwrap(), &"req_abc123");
    assert!(
        instance.service_request_id.is_some(),
        "Expected service_request_id to be Some"
    );
    assert_eq!(instance.service_request_id.as_ref().unwrap(), &"srv_abc123");
    assert!(
        instance.duration_ms.is_some(),
        "Expected duration_ms to be Some"
    );
    assert_eq!(instance.duration_ms.as_ref().unwrap(), &820.0);
}

#[test]
fn test_llm_complete_payload_load_yaml() {
    let yaml = r####"
requestId: req_abc123
serviceRequestId: srv_abc123
durationMs: 820

"####;
    let ctx = LoadContext::default();
    let result = LlmCompletePayload::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.request_id.is_some(),
        "Expected request_id to be Some"
    );
    assert!(
        instance.service_request_id.is_some(),
        "Expected service_request_id to be Some"
    );
    assert!(
        instance.duration_ms.is_some(),
        "Expected duration_ms to be Some"
    );
}

#[test]
fn test_llm_complete_payload_roundtrip() {
    let json = r####"
{
  "requestId": "req_abc123",
  "serviceRequestId": "srv_abc123",
  "durationMs": 820
}
"####;
    let load_ctx = LoadContext::default();
    let result = LlmCompletePayload::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}
