// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use prompty::model::SessionWarningPayload;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_session_warning_payload_load_json() {
    let json = r####"
{
  "warningType": "remote",
  "message": "Remote session disabled"
}
"####;
    let ctx = LoadContext::default();
    let result = SessionWarningPayload::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.warning_type, "remote");
    assert_eq!(instance.message, "Remote session disabled");
}

#[test]
fn test_session_warning_payload_load_yaml() {
    let yaml = r####"
warningType: remote
message: Remote session disabled

"####;
    let ctx = LoadContext::default();
    let result = SessionWarningPayload::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.warning_type, "remote");
    assert_eq!(instance.message, "Remote session disabled");
}

#[test]
fn test_session_warning_payload_roundtrip() {
    let json = r####"
{
  "warningType": "remote",
  "message": "Remote session disabled"
}
"####;
    let load_ctx = LoadContext::default();
    let result = SessionWarningPayload::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}

#[test]
fn test_session_warning_payload_serde_roundtrip() {
    let json = r####"
{
  "warningType": "remote",
  "message": "Remote session disabled"
}
"####;
    let instance: SessionWarningPayload =
        serde_json::from_str(json).expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance).expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json).expect("canonical json parses");
    assert_eq!(
        value,
        instance.to_value(&SaveContext::default()),
        "serde serialize must equal canonical to_value"
    );
    assert_eq!(
        instance,
        SessionWarningPayload::load_from_value(&canonical, &LoadContext::default()),
        "serde deserialize must equal canonical load_from_value"
    );
    assert_eq!(
        value, canonical,
        "serde must serialize to byte-identical canonical wire (empty-omission preserved; no plain-derive divergence)"
    );
    let reparsed: SessionWarningPayload =
        serde_json::from_value(value).expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}
