// Code generated by Prompty emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, clippy::all)]

use prompty::model::SessionEvent;
use prompty::model::SessionEventType;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_session_event_load_json() {
    let json = r####"
{
  "id": "evt_abc123",
  "timestamp": "2026-06-09T20:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_001",
  "parentId": "evt_parent",
  "spanId": "span_hook_001"
}
"####;
    let ctx = LoadContext::default();
    let result = SessionEvent::from_json(json, &ctx);
    assert!(result.is_ok(), "Failed to load from JSON: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.id, "evt_abc123");
    assert_eq!(instance.timestamp, "2026-06-09T20:00:00Z");
    assert!(instance.session_id.is_some(), "Expected session_id to be Some");
    assert_eq!(instance.session_id.as_ref().unwrap(), &"sess_abc123");
    assert!(instance.turn_id.is_some(), "Expected turn_id to be Some");
    assert_eq!(instance.turn_id.as_ref().unwrap(), &"turn_001");
    assert!(instance.parent_id.is_some(), "Expected parent_id to be Some");
    assert_eq!(instance.parent_id.as_ref().unwrap(), &"evt_parent");
    assert!(instance.span_id.is_some(), "Expected span_id to be Some");
    assert_eq!(instance.span_id.as_ref().unwrap(), &"span_hook_001");
}

#[test]
fn test_session_event_load_yaml() {
    let yaml = r####"
id: evt_abc123
timestamp: "2026-06-09T20:00:00Z"
sessionId: sess_abc123
turnId: turn_001
parentId: evt_parent
spanId: span_hook_001

"####;
    let ctx = LoadContext::default();
    let result = SessionEvent::from_yaml(yaml, &ctx);
    assert!(result.is_ok(), "Failed to load from YAML: {:?}", result.err());
    let instance = result.unwrap();
    assert_eq!(instance.id, "evt_abc123");
    assert_eq!(instance.timestamp, "2026-06-09T20:00:00Z");
    assert!(instance.session_id.is_some(), "Expected session_id to be Some");
    assert!(instance.turn_id.is_some(), "Expected turn_id to be Some");
    assert!(instance.parent_id.is_some(), "Expected parent_id to be Some");
    assert!(instance.span_id.is_some(), "Expected span_id to be Some");
}

#[test]
fn test_session_event_roundtrip() {
    let json = r####"
{
  "id": "evt_abc123",
  "timestamp": "2026-06-09T20:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_001",
  "parentId": "evt_parent",
  "spanId": "span_hook_001"
}
"####;
    let load_ctx = LoadContext::default();
    let result = SessionEvent::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(json_output.is_ok(), "Failed to serialize to JSON: {:?}", json_output.err());
}
