// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use prompty::model::SessionRef;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_session_ref_load_json() {
    let json = r####"
{
  "sessionId": "sess_abc123",
  "refType": "issue",
  "refValue": "owner/repo#123",
  "turnIndex": 2,
  "createdAt": "2026-06-09T20:00:00Z"
}
"####;
    let ctx = LoadContext::default();
    let result = SessionRef::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.session_id.is_some(),
        "Expected session_id to be Some"
    );
    assert_eq!(instance.session_id.as_ref().unwrap(), &"sess_abc123");
    assert_eq!(instance.ref_type, "issue");
    assert_eq!(instance.ref_value, "owner/repo#123");
    assert!(
        instance.turn_index.is_some(),
        "Expected turn_index to be Some"
    );
    assert_eq!(instance.turn_index.as_ref().unwrap(), &2);
    assert!(
        instance.created_at.is_some(),
        "Expected created_at to be Some"
    );
    assert_eq!(
        instance.created_at.as_ref().unwrap(),
        &"2026-06-09T20:00:00Z"
    );
}

#[test]
fn test_session_ref_load_yaml() {
    let yaml = r####"
sessionId: sess_abc123
refType: issue
refValue: "owner/repo#123"
turnIndex: 2
createdAt: "2026-06-09T20:00:00Z"

"####;
    let ctx = LoadContext::default();
    let result = SessionRef::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.session_id.is_some(),
        "Expected session_id to be Some"
    );
    assert_eq!(instance.ref_type, "issue");
    assert_eq!(instance.ref_value, "owner/repo#123");
    assert!(
        instance.turn_index.is_some(),
        "Expected turn_index to be Some"
    );
    assert!(
        instance.created_at.is_some(),
        "Expected created_at to be Some"
    );
}

#[test]
fn test_session_ref_roundtrip() {
    let json = r####"
{
  "sessionId": "sess_abc123",
  "refType": "issue",
  "refValue": "owner/repo#123",
  "turnIndex": 2,
  "createdAt": "2026-06-09T20:00:00Z"
}
"####;
    let load_ctx = LoadContext::default();
    let result = SessionRef::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}

#[test]
fn test_session_ref_serde_roundtrip() {
    let json = r####"
{
  "sessionId": "sess_abc123",
  "refType": "issue",
  "refValue": "owner/repo#123",
  "turnIndex": 2,
  "createdAt": "2026-06-09T20:00:00Z"
}
"####;
    let instance: SessionRef =
        serde_json::from_str(json).expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance).expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json).expect("canonical json parses");
    assert_eq!(
        value,
        instance.to_value(&SaveContext::default()),
        "serde serialize must equal canonical to_value"
    );
    assert_eq!(
        instance,
        SessionRef::load_from_value(&canonical, &LoadContext::default()),
        "serde deserialize must equal canonical load_from_value"
    );
    assert_eq!(
        value, canonical,
        "serde must serialize to byte-identical canonical wire (empty-omission preserved; no plain-derive divergence)"
    );
    let reparsed: SessionRef = serde_json::from_value(value).expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}
