emit:
  - "@typespec/json-schema"
  - "agentschema-emitter"
options:
  "@typespec/json-schema":
    emitter-output-dir: "{cwd}/../vscode/prompty/schemas"
    emitAllModels: true
    emitAllRefs: true
    file-type: yaml
  "agentschema-emitter":
    emitter-output-dir: "{cwd}/tsp-output"
    root-object: "Prompty.Prompty"
    emit-targets:
      - type: TypeScript
        output-dir: "../runtime/typescript/packages/core/src/model"
        test-dir: "../runtime/typescript/packages/core/tests/model"
        import-path: "../../src/model/index"
      - type: Python
        output-dir: "../runtime/python/prompty/prompty/model"
        test-dir: "../runtime/python/prompty/tests/model"
        import-path: "prompty.model"
      - type: CSharp
        output-dir: "../runtime/csharp/Prompty.Core/Model"
        test-dir: "../runtime/csharp/Prompty.Core.Tests/Model"
      - type: Go
        output-dir: "../runtime/go/prompty/model"
        test-dir: "../runtime/go/prompty/model"
      - type: Rust
        output-dir: "../runtime/rust/prompty/src/model"
        test-dir: "../runtime/rust/prompty/tests/model"
      - type: markdown
        output-dir: "../web/src/content/docs/reference"
