// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use prompty::model::TokenUsage;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_token_usage_load_json() {
    let json = r####"
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"####;
    let ctx = LoadContext::default();
    let result = TokenUsage::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.prompt_tokens.is_some(),
        "Expected prompt_tokens to be Some"
    );
    assert_eq!(instance.prompt_tokens.as_ref().unwrap(), &150);
    assert!(
        instance.completion_tokens.is_some(),
        "Expected completion_tokens to be Some"
    );
    assert_eq!(instance.completion_tokens.as_ref().unwrap(), &42);
    assert!(
        instance.total_tokens.is_some(),
        "Expected total_tokens to be Some"
    );
    assert_eq!(instance.total_tokens.as_ref().unwrap(), &192);
}

#[test]
fn test_token_usage_load_yaml() {
    let yaml = r####"
promptTokens: 150
completionTokens: 42
totalTokens: 192

"####;
    let ctx = LoadContext::default();
    let result = TokenUsage::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert!(
        instance.prompt_tokens.is_some(),
        "Expected prompt_tokens to be Some"
    );
    assert!(
        instance.completion_tokens.is_some(),
        "Expected completion_tokens to be Some"
    );
    assert!(
        instance.total_tokens.is_some(),
        "Expected total_tokens to be Some"
    );
}

#[test]
fn test_token_usage_roundtrip() {
    let json = r####"
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"####;
    let load_ctx = LoadContext::default();
    let result = TokenUsage::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}

#[cfg(feature = "serde")]
#[test]
fn test_token_usage_serde_roundtrip() {
    let json = r####"
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"####;
    let instance: TokenUsage =
        serde_json::from_str(json).expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance).expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json).expect("canonical json parses");
    assert_eq!(
        value,
        instance.to_value(&SaveContext::default()),
        "serde serialize must equal canonical to_value"
    );
    assert_eq!(
        instance,
        TokenUsage::load_from_value(&canonical, &LoadContext::default()),
        "serde deserialize must equal canonical load_from_value"
    );
    assert_eq!(
        value, canonical,
        "serde must serialize to byte-identical canonical wire (empty-omission preserved; no plain-derive divergence)"
    );
    let reparsed: TokenUsage = serde_json::from_value(value).expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}

#[test]
fn test_token_usage_wire_conversion() {
    let json = r####"
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"####;
    let ctx = LoadContext::default();
    let instance = TokenUsage::from_json(json, &ctx).expect("load should succeed");
    let openai_wire = instance.to_wire("openai");
    let openai_obj = openai_wire.as_object().expect("to_wire returns an object");
    assert!(
        openai_obj.contains_key("prompt_tokens"),
        "Expected openai wire output to include prompt_tokens"
    );
    assert!(
        !openai_obj.contains_key("promptTokens"),
        "Expected openai wire output to omit promptTokens"
    );
    assert!(
        openai_obj.contains_key("completion_tokens"),
        "Expected openai wire output to include completion_tokens"
    );
    assert!(
        !openai_obj.contains_key("completionTokens"),
        "Expected openai wire output to omit completionTokens"
    );
    assert!(
        openai_obj.contains_key("total_tokens"),
        "Expected openai wire output to include total_tokens"
    );
    assert!(
        !openai_obj.contains_key("totalTokens"),
        "Expected openai wire output to omit totalTokens"
    );
    let openai_restored = TokenUsage::from_wire("openai", &openai_wire, &ctx);
    let openai_round = openai_restored.to_wire("openai");
    let mut openai_expected: Vec<&String> = openai_obj.keys().collect();
    let mut openai_actual: Vec<&String> = openai_round
        .as_object()
        .expect("to_wire returns an object")
        .keys()
        .collect();
    openai_expected.sort();
    openai_actual.sort();
    assert_eq!(
        openai_expected, openai_actual,
        "Expected openai round-trip to preserve wire keys"
    );
    let anthropic_wire = instance.to_wire("anthropic");
    let anthropic_obj = anthropic_wire
        .as_object()
        .expect("to_wire returns an object");
    assert!(
        anthropic_obj.contains_key("input_tokens"),
        "Expected anthropic wire output to include input_tokens"
    );
    assert!(
        !anthropic_obj.contains_key("promptTokens"),
        "Expected anthropic wire output to omit promptTokens"
    );
    assert!(
        anthropic_obj.contains_key("output_tokens"),
        "Expected anthropic wire output to include output_tokens"
    );
    assert!(
        !anthropic_obj.contains_key("completionTokens"),
        "Expected anthropic wire output to omit completionTokens"
    );
    let anthropic_restored = TokenUsage::from_wire("anthropic", &anthropic_wire, &ctx);
    let anthropic_round = anthropic_restored.to_wire("anthropic");
    let mut anthropic_expected: Vec<&String> = anthropic_obj.keys().collect();
    let mut anthropic_actual: Vec<&String> = anthropic_round
        .as_object()
        .expect("to_wire returns an object")
        .keys()
        .collect();
    anthropic_expected.sort();
    anthropic_actual.sort();
    assert_eq!(
        anthropic_expected, anthropic_actual,
        "Expected anthropic round-trip to preserve wire keys"
    );
}

#[test]
fn test_token_usage_from_json_invalid() {
    let ctx = LoadContext::default();
    assert!(
        TokenUsage::from_json("{", &ctx).is_err(),
        "malformed JSON must be rejected instead of silently defaulting"
    );
}
