// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { TraceFile } from "../../src/model/index";

describe("TraceFile", () => {
  describe("construction", () => {
    it("should create a new instance with defaults", () => {
      const instance = new TraceFile();
      expect(instance).toBeDefined();
    });

    it("should create a new instance with partial initialization", () => {
      const instance = new TraceFile({});
      expect(instance).toBeDefined();
    });
  });

  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "runtime": "python",\n  "version": "2.0.0"\n}`;
      const instance = TraceFile.fromJson(json);
      expect(instance).toBeDefined();
      expect(instance.runtime).toEqual("python");
      expect(instance.version).toEqual("2.0.0");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "runtime": "python",\n  "version": "2.0.0"\n}`;
      const instance = TraceFile.fromJson(json);
      const output = instance.toJson();
      const reloaded = TraceFile.fromJson(output);
      expect(reloaded.runtime).toEqual(instance.runtime);
      expect(reloaded.version).toEqual(instance.version);
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `runtime: python\nversion: 2.0.0\n`;
      const instance = TraceFile.fromYaml(yaml);
      expect(instance).toBeDefined();
      expect(instance.runtime).toEqual("python");
      expect(instance.version).toEqual("2.0.0");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `runtime: python\nversion: 2.0.0\n`;
      const instance = TraceFile.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = TraceFile.fromYaml(output);
      expect(reloaded.runtime).toEqual(instance.runtime);
      expect(reloaded.version).toEqual(instance.version);
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = TraceFile.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new TraceFile();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
