// <auto-generated/>
// Code generated by Prompty emitter; DO NOT EDIT.

using System.Text.Json.Serialization;

namespace Prompty.Core;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Role
{
    [JsonPropertyName("system")]
    System,

    [JsonPropertyName("user")]
    User,

    [JsonPropertyName("assistant")]
    Assistant,

    [JsonPropertyName("developer")]
    Developer,

    [JsonPropertyName("tool")]
    Tool,

}
