# <auto-generated by typra-emitter>
import json

import yaml

from prompty.model import OpenAIModel


def test_load_json_openaimodel():
    json_data = r"""
    {
      "provider": "openai"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = OpenAIModel.load(data)
    assert instance is not None
    assert instance.provider == "openai"


def test_load_yaml_openaimodel():
    yaml_data = r"""
    provider: openai

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = OpenAIModel.load(data)
    assert instance is not None
    assert instance.provider == "openai"


def test_roundtrip_json_openaimodel():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "provider": "openai"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = OpenAIModel.load(original_data)
    saved_data = instance.save()
    reloaded = OpenAIModel.load(saved_data)
    assert reloaded is not None
    assert reloaded.provider == "openai"


def test_to_json_openaimodel():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "provider": "openai"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = OpenAIModel.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_openaimodel():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "provider": "openai"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = OpenAIModel.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)


def test_load_openaimodel_invalid():
    """load must reject invalid input instead of silently defaulting."""
    raised = False
    try:
        OpenAIModel.load(object())
    except ValueError:
        raised = True
    assert raised, "Expected invalid input to be rejected"
