# <auto-generated by typra-emitter>
import json

import yaml

from prompty.model import ProjectInfo


def test_load_json_projectinfo():
    json_data = r'''
    {
      "name": "sample",
      "displayName": "sample",
      "endpoint": "sample"
    }
    '''
    data = json.loads(json_data, strict=False)
    instance = ProjectInfo.load(data)
    assert instance is not None
    assert instance.name == "sample"
    assert instance.display_name == "sample"
    assert instance.endpoint == "sample"

def test_load_yaml_projectinfo():
    yaml_data = r'''
    name: sample
    displayName: sample
    endpoint: sample

    '''
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ProjectInfo.load(data)
    assert instance is not None
    assert instance.name == "sample"
    assert instance.display_name == "sample"
    assert instance.endpoint == "sample"

def test_roundtrip_json_projectinfo():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r'''
    {
      "name": "sample",
      "displayName": "sample",
      "endpoint": "sample"
    }
    '''
    original_data = json.loads(json_data, strict=False)
    instance = ProjectInfo.load(original_data)
    saved_data = instance.save()
    reloaded = ProjectInfo.load(saved_data)
    assert reloaded is not None
    assert reloaded.name == "sample"
    assert reloaded.display_name == "sample"
    assert reloaded.endpoint == "sample"

def test_to_json_projectinfo():
    """Test that to_json produces valid JSON."""
    json_data = r'''
    {
      "name": "sample",
      "displayName": "sample",
      "endpoint": "sample"
    }
    '''
    data = json.loads(json_data, strict=False)
    instance = ProjectInfo.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)

def test_to_yaml_projectinfo():
    """Test that to_yaml produces valid YAML."""
    json_data = r'''
    {
      "name": "sample",
      "displayName": "sample",
      "endpoint": "sample"
    }
    '''
    data = json.loads(json_data, strict=False)
    instance = ProjectInfo.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
