// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

use super::anthropic_image_source::AnthropicImageSource;

/// An image content block using base64-encoded data. Anthropic requires images as base64 with an explicit media type.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct AnthropicImageBlock {
    /// The content block type
    pub r#type: String,
    /// The image source (base64-encoded)
    pub source: AnthropicImageSource,
}

impl AnthropicImageBlock {
    /// Create a new AnthropicImageBlock with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        let child_path = if path.is_empty() {
            "source".to_string()
        } else {
            format!("{}.source", path)
        };
        let child = value
            .get("source")
            .filter(|candidate| !candidate.is_null())
            .ok_or_else(|| format!("{}: missing required field", child_path))?;
        AnthropicImageSource::validate_input_at(child, &child_path)?;
        Ok(())
    }
}
