// Code generated by AgentSchema emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code)]

use super::super::context::{LoadContext, SaveContext};

/// A tool call requested by the LLM. Contains the function name and serialized arguments that should be dispatched to the appropriate tool handler.
#[derive(Debug, Clone, Default)]
pub struct ToolCall {
    /// The unique identifier of the tool call
    pub id: String,
    /// The name of the tool to call
    pub name: String,
    /// The serialized JSON arguments for the tool call
    pub arguments: String,
}

impl ToolCall {
    /// Create a new ToolCall with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load ToolCall from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ToolCall from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ToolCall from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        Self {
            id: value
                .get("id")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            name: value
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            arguments: value
                .get("arguments")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
        }
    }

    /// Serialize ToolCall to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if !self.id.is_empty() {
            result.insert("id".to_string(), serde_json::Value::String(self.id.clone()));
        }
        if !self.name.is_empty() {
            result.insert(
                "name".to_string(),
                serde_json::Value::String(self.name.clone()),
            );
        }
        if !self.arguments.is_empty() {
            result.insert(
                "arguments".to_string(),
                serde_json::Value::String(self.arguments.clone()),
            );
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize ToolCall to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize ToolCall to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}
