// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest

@testable import PromptyModel

final class InvocationUsageTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
      {
        "inputTokens": 150,
        "outputTokens": 42,
        "totalTokens": 192
      }
      """
    let instance = try InvocationUsage.fromJSON(json)
    XCTAssertEqual(instance.inputTokens, 150)
    XCTAssertEqual(instance.outputTokens, 42)
    XCTAssertEqual(instance.totalTokens, 192)
    let reloaded = try InvocationUsage.fromJSON(try instance.toJSON())
    XCTAssertEqual(reloaded.inputTokens, 150)
    XCTAssertEqual(reloaded.outputTokens, 42)
    XCTAssertEqual(reloaded.totalTokens, 192)
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
      inputTokens: 150
      outputTokens: 42
      totalTokens: 192

      """
    let instance = try InvocationUsage.fromYAML(yaml)
    XCTAssertEqual(instance.inputTokens, 150)
    XCTAssertEqual(instance.outputTokens, 42)
    XCTAssertEqual(instance.totalTokens, 192)
    let reloaded = try InvocationUsage.fromYAML(try instance.toYAML())
    XCTAssertEqual(reloaded.inputTokens, 150)
    XCTAssertEqual(reloaded.outputTokens, 42)
    XCTAssertEqual(reloaded.totalTokens, 192)
  }

}
