// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest
@testable import PromptyModel

final class TokenUsageTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"""
    let instance = try TokenUsage.fromJSON(json)
    XCTAssertEqual((try XCTUnwrap(instance.promptTokens)), 150)
    XCTAssertEqual((try XCTUnwrap(instance.completionTokens)), 42)
    XCTAssertEqual((try XCTUnwrap(instance.totalTokens)), 192)
    let reloaded = try TokenUsage.fromJSON(try instance.toJSON())
    XCTAssertEqual((try XCTUnwrap(reloaded.promptTokens)), 150)
    XCTAssertEqual((try XCTUnwrap(reloaded.completionTokens)), 42)
    XCTAssertEqual((try XCTUnwrap(reloaded.totalTokens)), 192)
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
promptTokens: 150
completionTokens: 42
totalTokens: 192

"""
    let instance = try TokenUsage.fromYAML(yaml)
    XCTAssertEqual((try XCTUnwrap(instance.promptTokens)), 150)
    XCTAssertEqual((try XCTUnwrap(instance.completionTokens)), 42)
    XCTAssertEqual((try XCTUnwrap(instance.totalTokens)), 192)
    let reloaded = try TokenUsage.fromYAML(try instance.toYAML())
    XCTAssertEqual((try XCTUnwrap(reloaded.promptTokens)), 150)
    XCTAssertEqual((try XCTUnwrap(reloaded.completionTokens)), 42)
    XCTAssertEqual((try XCTUnwrap(reloaded.totalTokens)), 192)
  }


  func testWireConversion() throws {
    let json = """
{
  "promptTokens": 150,
  "completionTokens": 42,
  "totalTokens": 192
}
"""
    let instance = try TokenUsage.fromJSON(json)
    let openaiWire = try instance.toWire("openai")
    XCTAssertNotNil(openaiWire["prompt_tokens"])
    XCTAssertNil(openaiWire["promptTokens"])
    XCTAssertNotNil(openaiWire["completion_tokens"])
    XCTAssertNil(openaiWire["completionTokens"])
    XCTAssertNotNil(openaiWire["total_tokens"])
    XCTAssertNil(openaiWire["totalTokens"])
    let openaiRestored = try TokenUsage.fromWire("openai", openaiWire)
    XCTAssertEqual(Set(try openaiRestored.toWire("openai").keys), Set(openaiWire.keys))
    let anthropicWire = try instance.toWire("anthropic")
    XCTAssertNotNil(anthropicWire["input_tokens"])
    XCTAssertNil(anthropicWire["promptTokens"])
    XCTAssertNotNil(anthropicWire["output_tokens"])
    XCTAssertNil(anthropicWire["completionTokens"])
    let anthropicRestored = try TokenUsage.fromWire("anthropic", anthropicWire)
    XCTAssertEqual(Set(try anthropicRestored.toWire("anthropic").keys), Set(anthropicWire.keys))
  }
  // Invalid-input test (malformed JSON must be rejected, issue #328 class)
  func testFromJSONInvalid() throws {
    XCTAssertThrowsError(try TokenUsage.fromJSON("{"))
  }

}
