// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

final class FormatConfigGeneratedTest {
  private FormatConfigGeneratedTest() { }

  static void run() {

    // FormatConfig example 1: fromJson, fromYaml, save, and reload
    String jsonData1 = """
      {
        "kind": "mustache",
        "strict": true,
        "options": {
          "key": "value"
        }
      }
      """;
    FormatConfig instance1 = FormatConfig.fromJson(jsonData1);
    assertEquals("mustache", instance1.kind, "Expected kind");
    assertEquals(true, instance1.strict, "Expected strict");
    assertEquals("value", instance1.options.get("key"), "Expected options.key");
    String yamlRoundtrip1 = instance1.toYaml();
    FormatConfig fromYaml1 = FormatConfig.fromYaml(yamlRoundtrip1);
    assertEquals("mustache", fromYaml1.kind, "Expected kind");
    assertEquals(true, fromYaml1.strict, "Expected strict");
    assertEquals("value", fromYaml1.options.get("key"), "Expected options.key");
    FormatConfig reloaded1 = FormatConfig.load(instance1.save(new SaveContext()), new LoadContext());
    assertEquals("mustache", reloaded1.kind, "Expected kind");
    assertEquals(true, reloaded1.strict, "Expected strict");
    assertEquals("value", reloaded1.options.get("key"), "Expected options.key");

    assertThrows(() -> FormatConfig.fromJson("{"), "FormatConfig.fromJson should reject malformed JSON");

    assertThrows(() -> FormatConfig.fromYaml(":\n  broken"), "FormatConfig.fromYaml should reject malformed YAML");
  }

  private static Object unwrapEnum(Object value) {
    if (value == null || !value.getClass().isEnum()) return value;
    try {
      return value.getClass().getField("value").get(value);
    } catch (ReflectiveOperationException ignored) {
      return value;
    }
  }

  private static void assertEquals(Object expected, Object actual, String message) {
    expected = unwrapEnum(expected);
    actual = unwrapEnum(actual);
    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {
      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;
    }
    if (expected == null ? actual != null : !expected.equals(actual)) {
      throw new AssertionError(message + ": expected " + expected + ", got " + actual);
    }
  }

  private static void assertTrue(boolean condition, String message) {
    if (!condition) throw new AssertionError(message);
  }

  private static void assertThrows(Runnable runnable, String message) {
    try {
      runnable.run();
    } catch (RuntimeException expected) {
      return;
    }
    throw new AssertionError(message);
  }
}
