// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

final class InvokerErrorGeneratedTest {
  private InvokerErrorGeneratedTest() { }

  static void run() {

    // InvokerError example 1: fromJson, fromYaml, save, and reload
    String jsonData1 = """
      {
        "message": "No renderer registered for key: jinja2",
        "component": "renderer",
        "key": "jinja2"
      }
      """;
    InvokerError instance1 = InvokerError.fromJson(jsonData1);
    assertEquals("No renderer registered for key: jinja2", instance1.message, "Expected message");
    assertEquals("renderer", instance1.component, "Expected component");
    assertEquals("jinja2", instance1.key, "Expected key");
    String yamlRoundtrip1 = instance1.toYaml();
    InvokerError fromYaml1 = InvokerError.fromYaml(yamlRoundtrip1);
    assertEquals("No renderer registered for key: jinja2", fromYaml1.message, "Expected message");
    assertEquals("renderer", fromYaml1.component, "Expected component");
    assertEquals("jinja2", fromYaml1.key, "Expected key");
    InvokerError reloaded1 = InvokerError.load(instance1.save(new SaveContext()), new LoadContext());
    assertEquals("No renderer registered for key: jinja2", reloaded1.message, "Expected message");
    assertEquals("renderer", reloaded1.component, "Expected component");
    assertEquals("jinja2", reloaded1.key, "Expected key");

    assertThrows(() -> InvokerError.fromJson("{"), "InvokerError.fromJson should reject malformed JSON");

    assertThrows(() -> InvokerError.fromYaml(":\n  broken"), "InvokerError.fromYaml should reject malformed YAML");

    java.util.Map<String, Object> yamlControl = new java.util.LinkedHashMap<>();
    String yamlControlValue = new String(new int[] { 0x0001, 0x0008, 0x000c, 0x1f642 }, 0, 4);
    yamlControl.put("value", yamlControlValue);
    String yamlControlText = TypraYaml.stringify(yamlControl);
    assertTrue(yamlControlText.contains("\\u0001"), "YAML should unicode-escape C0 controls");
    assertTrue(yamlControlText.contains("\\b"), "YAML should escape backspace");
    assertTrue(yamlControlText.contains("\\f"), "YAML should escape form feed");
    Object yamlParsed = TypraYaml.parse("value: \"\\b\\f\\u0001\\uD83D\\uDE42\"");
    Object yamlValue = ((java.util.Map<?, ?>) yamlParsed).get("value");
    String yamlParsedExpected = new String(new int[] { 0x0008, 0x000c, 0x0001, 0x1f642 }, 0, 4);
    assertEquals(yamlParsedExpected, yamlValue, "YAML should decode named and unicode escapes");
    assertThrows(() -> TypraYaml.parse("value: \"\\x\""), "YAML should reject unknown escapes");
  }

  private static void assertEquals(Object expected, Object actual, String message) {
    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {
      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;
    }
    if (expected == null ? actual != null : !expected.equals(actual)) {
      throw new AssertionError(message + ": expected " + expected + ", got " + actual);
    }
  }

  private static void assertTrue(boolean condition, String message) {
    if (!condition) throw new AssertionError(message);
  }

  private static void assertThrows(Runnable runnable, String message) {
    try {
      runnable.run();
    } catch (RuntimeException expected) {
      return;
    }
    throw new AssertionError(message);
  }
}
