// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

final class MemoryEntryGeneratedTest {
  private MemoryEntryGeneratedTest() { }

  static void run() {

    // MemoryEntry example 1: fromJson, fromYaml, save, and reload
    String jsonData1 = """
      {
        "content": "The user prefers concise answers.",
        "category": "core",
        "createdAt": "2026-06-09T20:00:00Z",
        "tags": [
          "preference",
          "tone"
        ]
      }
      """;
    MemoryEntry instance1 = MemoryEntry.fromJson(jsonData1);
    assertEquals("The user prefers concise answers.", instance1.content, "Expected content");
    assertEquals(MemoryCategory.fromValue("core"), instance1.category, "Expected category");
    assertEquals("2026-06-09T20:00:00Z", instance1.createdAt, "Expected createdAt");
    assertEquals(2, instance1.tags.size(), "Expected tags size");
    assertEquals("preference", instance1.tags.get(0), "Expected tags[0]");
    assertEquals("tone", instance1.tags.get(1), "Expected tags[1]");
    String yamlRoundtrip1 = instance1.toYaml();
    MemoryEntry fromYaml1 = MemoryEntry.fromYaml(yamlRoundtrip1);
    assertEquals("The user prefers concise answers.", fromYaml1.content, "Expected content");
    assertEquals(MemoryCategory.fromValue("core"), fromYaml1.category, "Expected category");
    assertEquals("2026-06-09T20:00:00Z", fromYaml1.createdAt, "Expected createdAt");
    assertEquals(2, fromYaml1.tags.size(), "Expected tags size");
    assertEquals("preference", fromYaml1.tags.get(0), "Expected tags[0]");
    assertEquals("tone", fromYaml1.tags.get(1), "Expected tags[1]");
    MemoryEntry reloaded1 = MemoryEntry.load(instance1.save(new SaveContext()), new LoadContext());
    assertEquals("The user prefers concise answers.", reloaded1.content, "Expected content");
    assertEquals(MemoryCategory.fromValue("core"), reloaded1.category, "Expected category");
    assertEquals("2026-06-09T20:00:00Z", reloaded1.createdAt, "Expected createdAt");
    assertEquals(2, reloaded1.tags.size(), "Expected tags size");
    assertEquals("preference", reloaded1.tags.get(0), "Expected tags[0]");
    assertEquals("tone", reloaded1.tags.get(1), "Expected tags[1]");

    assertThrows(() -> MemoryEntry.fromJson("{"), "MemoryEntry.fromJson should reject malformed JSON");

    assertThrows(() -> MemoryEntry.fromYaml(":\n  broken"), "MemoryEntry.fromYaml should reject malformed YAML");
  }

  private static Object unwrapEnum(Object value) {
    if (value == null || !value.getClass().isEnum()) return value;
    try {
      return value.getClass().getField("value").get(value);
    } catch (ReflectiveOperationException ignored) {
      return value;
    }
  }

  private static void assertEquals(Object expected, Object actual, String message) {
    expected = unwrapEnum(expected);
    actual = unwrapEnum(actual);
    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {
      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;
    }
    if (expected == null ? actual != null : !expected.equals(actual)) {
      throw new AssertionError(message + ": expected " + expected + ", got " + actual);
    }
  }

  private static void assertTrue(boolean condition, String message) {
    if (!condition) throw new AssertionError(message);
  }

  private static void assertThrows(Runnable runnable, String message) {
    try {
      runnable.run();
    } catch (RuntimeException expected) {
      return;
    }
    throw new AssertionError(message);
  }
}
