// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

final class ThreadMarkerGeneratedTest {
  private ThreadMarkerGeneratedTest() { }

  static void run() {

    // ThreadMarker example 1: fromJson, fromYaml, save, and reload
    String jsonData1 = """
      {
        "name": "thread",
        "kind": "thread"
      }
      """;
    ThreadMarker instance1 = ThreadMarker.fromJson(jsonData1);
    assertEquals("thread", instance1.name, "Expected name");
    assertEquals("thread", instance1.kind, "Expected kind");
    String yamlRoundtrip1 = instance1.toYaml();
    ThreadMarker fromYaml1 = ThreadMarker.fromYaml(yamlRoundtrip1);
    assertEquals("thread", fromYaml1.name, "Expected name");
    assertEquals("thread", fromYaml1.kind, "Expected kind");
    ThreadMarker reloaded1 = ThreadMarker.load(instance1.save(new SaveContext()), new LoadContext());
    assertEquals("thread", reloaded1.name, "Expected name");
    assertEquals("thread", reloaded1.kind, "Expected kind");

    assertThrows(() -> ThreadMarker.fromJson("{"), "ThreadMarker.fromJson should reject malformed JSON");

    assertThrows(() -> ThreadMarker.fromYaml(":\n  broken"), "ThreadMarker.fromYaml should reject malformed YAML");
  }

  private static Object unwrapEnum(Object value) {
    if (value == null || !value.getClass().isEnum()) return value;
    try {
      return value.getClass().getField("value").get(value);
    } catch (ReflectiveOperationException ignored) {
      return value;
    }
  }

  private static void assertEquals(Object expected, Object actual, String message) {
    expected = unwrapEnum(expected);
    actual = unwrapEnum(actual);
    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {
      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;
    }
    if (expected == null ? actual != null : !expected.equals(actual)) {
      throw new AssertionError(message + ": expected " + expected + ", got " + actual);
    }
  }

  private static void assertTrue(boolean condition, String message) {
    if (!condition) throw new AssertionError(message);
  }

  private static void assertThrows(Runnable runnable, String message) {
    try {
      runnable.run();
    } catch (RuntimeException expected) {
      return;
    }
    throw new AssertionError(message);
  }
}
