// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

final class TraceFileGeneratedTest {
  private TraceFileGeneratedTest() { }

  static void run() {

    // TraceFile example 1: fromJson, fromYaml, save, and reload
    String jsonData1 = """
      {
        "runtime": "python",
        "version": "2.0.0"
      }
      """;
    TraceFile instance1 = TraceFile.fromJson(jsonData1);
    assertEquals("python", instance1.runtime, "Expected runtime");
    assertEquals("2.0.0", instance1.version, "Expected version");
    String yamlRoundtrip1 = instance1.toYaml();
    TraceFile fromYaml1 = TraceFile.fromYaml(yamlRoundtrip1);
    assertEquals("python", fromYaml1.runtime, "Expected runtime");
    assertEquals("2.0.0", fromYaml1.version, "Expected version");
    TraceFile reloaded1 = TraceFile.load(instance1.save(new SaveContext()), new LoadContext());
    assertEquals("python", reloaded1.runtime, "Expected runtime");
    assertEquals("2.0.0", reloaded1.version, "Expected version");

    assertThrows(() -> TraceFile.fromJson("{"), "TraceFile.fromJson should reject malformed JSON");

    assertThrows(() -> TraceFile.fromYaml(":\n  broken"), "TraceFile.fromYaml should reject malformed YAML");
  }

  private static Object unwrapEnum(Object value) {
    if (value == null || !value.getClass().isEnum()) return value;
    try {
      return value.getClass().getField("value").get(value);
    } catch (ReflectiveOperationException ignored) {
      return value;
    }
  }

  private static void assertEquals(Object expected, Object actual, String message) {
    expected = unwrapEnum(expected);
    actual = unwrapEnum(actual);
    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {
      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;
    }
    if (expected == null ? actual != null : !expected.equals(actual)) {
      throw new AssertionError(message + ": expected " + expected + ", got " + actual);
    }
  }

  private static void assertTrue(boolean condition, String message) {
    if (!condition) throw new AssertionError(message);
  }

  private static void assertThrows(Runnable runnable, String message) {
    try {
      runnable.run();
    } catch (RuntimeException expected) {
      return;
    }
    throw new AssertionError(message);
  }
}
