// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use prompty::model::EngineEvent;
use prompty::model::EngineEventKind;
use prompty::model::context::{LoadContext, SaveContext};

#[test]
fn test_engine_event_load_json() {
    let json = r####"
{
  "id": "evt_abc123",
  "timestamp": "2025-01-01T00:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_abc123",
  "runId": "run_abc123"
}
"####;
    let ctx = LoadContext::default();
    let result = EngineEvent::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "evt_abc123");
    assert_eq!(instance.timestamp, "2025-01-01T00:00:00Z");
    assert_eq!(instance.session_id, "sess_abc123");
    assert_eq!(instance.turn_id, "turn_abc123");
    assert_eq!(instance.run_id, "run_abc123");
}

#[test]
fn test_engine_event_load_yaml() {
    let yaml = r####"
id: evt_abc123
timestamp: "2025-01-01T00:00:00Z"
sessionId: sess_abc123
turnId: turn_abc123
runId: run_abc123

"####;
    let ctx = LoadContext::default();
    let result = EngineEvent::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "evt_abc123");
    assert_eq!(instance.timestamp, "2025-01-01T00:00:00Z");
    assert_eq!(instance.session_id, "sess_abc123");
    assert_eq!(instance.turn_id, "turn_abc123");
    assert_eq!(instance.run_id, "run_abc123");
}

#[test]
fn test_engine_event_roundtrip() {
    let json = r####"
{
  "id": "evt_abc123",
  "timestamp": "2025-01-01T00:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_abc123",
  "runId": "run_abc123"
}
"####;
    let load_ctx = LoadContext::default();
    let result = EngineEvent::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}

#[test]
fn test_engine_event_serde_roundtrip() {
    let json = r####"
{
  "id": "evt_abc123",
  "timestamp": "2025-01-01T00:00:00Z",
  "sessionId": "sess_abc123",
  "turnId": "turn_abc123",
  "runId": "run_abc123"
}
"####;
    let instance: EngineEvent =
        serde_json::from_str(json).expect("serde should deserialize canonical JSON");
    let value = serde_json::to_value(&instance).expect("serde should serialize");
    let canonical: serde_json::Value = serde_json::from_str(json).expect("canonical json parses");
    assert_eq!(
        value,
        instance.to_value(&SaveContext::default()),
        "serde serialize must equal canonical to_value"
    );
    assert_eq!(
        instance,
        EngineEvent::load_from_value(&canonical, &LoadContext::default()),
        "serde deserialize must equal canonical load_from_value"
    );
    let reparsed: EngineEvent = serde_json::from_value(value).expect("serde should re-deserialize");
    assert_eq!(instance, reparsed, "serde round-trip must be stable");
}
