// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    clippy::all
)]

use prompty::model::context::{LoadContext, SaveContext};
use prompty::model::ModelToolRequest;

#[test]
fn test_model_tool_request_load_json() {
    let json = r####"
{
  "id": "call_abc123",
  "name": "get_weather"
}
"####;
    let ctx = LoadContext::default();
    let result = ModelToolRequest::from_json(json, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "call_abc123");
    assert_eq!(instance.name, "get_weather");
}

#[test]
fn test_model_tool_request_load_yaml() {
    let yaml = r####"
id: call_abc123
name: get_weather

"####;
    let ctx = LoadContext::default();
    let result = ModelToolRequest::from_yaml(yaml, &ctx);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "call_abc123");
    assert_eq!(instance.name, "get_weather");
}

#[test]
fn test_model_tool_request_roundtrip() {
    let json = r####"
{
  "id": "call_abc123",
  "name": "get_weather"
}
"####;
    let load_ctx = LoadContext::default();
    let result = ModelToolRequest::from_json(json, &load_ctx);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let save_ctx = SaveContext::default();
    let json_output = instance.to_json(&save_ctx);
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}
