// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "../../context";
import { TurnOptions } from "./turn-options";

export class RunTurnRequest {
  static readonly shorthandProperty: string | undefined = undefined;

  sessionId: string = "";
  turnId: string = "";
  inputs?: Record<string, unknown> | undefined;
  options?: TurnOptions | undefined;

  constructor(init?: Partial<RunTurnRequest>) {
    this.sessionId = init?.sessionId ?? "";
    this.turnId = init?.turnId ?? "";
    if (init?.inputs !== undefined) {
      this.inputs = init.inputs;
    }
    if (init?.options !== undefined) {
      this.options = init.options;
    }
  }
}
