// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// Payload for "compaction_start" events — context compaction is beginning.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct CompactionStartPayload {
    /// Number of messages selected for compaction
    pub dropped_count: i32,
}

impl CompactionStartPayload {
    /// Create a new CompactionStartPayload with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }
}
