// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// Payload for "error" events — an error occurred during the loop.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ErrorEventPayload {
    /// Human-readable error description
    pub message: String,
    /// Stable machine-readable error category
    pub error_kind: Option<String>,
    /// Operation or phase where the error occurred
    pub phase: Option<String>,
}

impl ErrorEventPayload {
    /// Create a new ErrorEventPayload with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }
}
