// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// A file observed or touched by a harness session.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SessionFileRef {
    /// Stable session identifier
    pub session_id: Option<String>,
    /// File path, relative to the harness workspace when possible
    pub path: String,
    /// Tool that first observed the file, when known
    pub tool_name: Option<String>,
    /// Zero-based turn index where the file was first observed
    pub turn_index: Option<i32>,
    /// ISO 8601 UTC timestamp when the file was first observed
    pub first_seen_at: Option<String>,
}

impl SessionFileRef {
    /// Create a new SessionFileRef with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }
}
