// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::super::super::context::{LoadContext, SaveContext};

/// Payload for "tool_call_start" events — the LLM has requested a tool call.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ToolCallStartPayload {
    /// The unique identifier of the tool call
    pub id: Option<String>,
    /// The name of the tool being called
    pub name: String,
    /// The serialized JSON arguments for the tool call
    pub arguments: String,
}

impl ToolCallStartPayload {
    /// Create a new ToolCallStartPayload with default values.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }
}
