// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation

/// An image content block using base64-encoded data. Anthropic requires images as base64 with an explicit media type.
public struct AnthropicImageBlock: TypraModel {
  public static let shorthandProperty: String? = nil
  public var type: String = "image"
  public var source: AnthropicImageSource = AnthropicImageSource()

  public init(type: String = "image", source: AnthropicImageSource = AnthropicImageSource()) {
    self.type = type
    self.source = source
  }

  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws
    -> AnthropicImageBlock
  {
    let object = try TypraRuntime.object(data, typeName: "AnthropicImageBlock")
    var instance = AnthropicImageBlock()
    if let value = object["type"] {
      instance.type = try TypraRuntime.string(value, field: "type")
    } else {
      instance.type = "image"
    }
    if object["source"] == nil || object["source"] is NSNull {
      throw TypraRuntimeError.unsupported(context.at("source").path + ": missing required field")
    }
    if let value = object["source"] {
      instance.source = try AnthropicImageSource.load(value, context: context.at("source"))
    }
    return instance
  }

  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {
    var result: [String: Any] = [:]
    result["type"] = self.type
    result["source"] = try self.source.save(context)
    return result
  }

  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws
    -> AnthropicImageBlock
  {
    return try load(
      TypraRuntime.jsonObject(from: json, typeName: "AnthropicImageBlock"), context: context)
  }

  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.jsonString(from: save(context))
  }

  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws
    -> AnthropicImageBlock
  {
    return try load(
      TypraRuntime.yamlObject(from: yaml, typeName: "AnthropicImageBlock"), context: context)
  }

  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {
    return try TypraRuntime.yamlString(from: save(context))
  }
}
