// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

import java.util.Map;
import java.util.function.Function;

public final class LoadContext {
  private final Function<Object, Object> preProcess;
  private final Function<Object, Object> postProcess;
  public final String path;

  public LoadContext() {
    this(null, null, "");
  }

  public LoadContext(Function<Object, Object> preProcess, Function<Object, Object> postProcess) {
    this(preProcess, postProcess, "");
  }

  private LoadContext(Function<Object, Object> preProcess, Function<Object, Object> postProcess, String path) {
    this.preProcess = preProcess;
    this.postProcess = postProcess;
    this.path = path;
  }

  public LoadContext at(String segment) {
    return new LoadContext(preProcess, postProcess, path.isEmpty() ? segment : path + "." + segment);
  }

  // Descend into an array element. Rendered with bracket notation (messages[3]) so an
  // index is never confused with a map key of the same name, which dot-joining would
  // make ambiguous.
  public LoadContext atIndex(int index) {
    return new LoadContext(preProcess, postProcess, path + "[" + index + "]");
  }

  public Object processInput(Object value) {
    return preProcess == null ? value : preProcess.apply(value);
  }

  @SuppressWarnings("unchecked")
  public <T> T processOutput(T value) {
    return postProcess == null ? value : (T) postProcess.apply(value);
  }
}
