// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ParserConfig {
  public static final String SHORTHAND_PROPERTY = "kind";

  public String kind = "*";
  public Map<String, Object> options = null;

  public ParserConfig() { }

  @SuppressWarnings("unchecked")
  public static ParserConfig load(Object input, LoadContext context) {
    LoadContext ctx = context == null ? new LoadContext() : context;
    Object data = ctx.processInput(input);
    if (data instanceof String) {
      ParserConfig result = new ParserConfig();
      result.kind = String.valueOf(data);
      return ctx.processOutput(result);
    }
    if (!(data instanceof Map<?, ?> map)) {
      return ctx.processOutput(new ParserConfig());
    }
    ParserConfig result = new ParserConfig();
    ParserConfig.loadBaseInto(result, map, ctx);
    return ctx.processOutput(result);
  }

  static void loadBaseInto(ParserConfig result, Map<?, ?> map, LoadContext ctx) {
    if (map.containsKey("kind") && map.get("kind") != null) {
      result.kind = String.valueOf(map.get("kind"));
    }
    if (map.containsKey("options") && map.get("options") != null) {
      if (map.get("options") instanceof Map<?, ?> dict) {
        result.options = copyMap(dict);
      }
    }
  }

  public Map<String, Object> save(SaveContext context) {
    SaveContext ctx = context == null ? new SaveContext() : context;
    ParserConfig obj = ctx.processObject(this);
    Map<String, Object> result = new LinkedHashMap<>();
    obj.saveFields(result, ctx);
    return ctx.processDict(result);
  }

  protected void saveFields(Map<String, Object> result, SaveContext ctx) {
    ParserConfig obj = this;
    if (obj.kind != null) result.put("kind", serializeScalar(obj.kind));
    if (obj.options != null) result.put("options", serializeScalar(obj.options));
  }

  public String toYaml() {
    return TypraYaml.stringify(save(new SaveContext()));
  }

  public String toJson() {
    return TypraJson.stringify(save(new SaveContext()));
  }

  public static ParserConfig fromYaml(String yaml) {
    return fromYaml(yaml, new LoadContext());
  }

  public static ParserConfig fromYaml(String yaml, LoadContext context) {
    return load(TypraYaml.parse(yaml), context);
  }

  public static ParserConfig fromJson(String json) {
    return fromJson(json, new LoadContext());
  }

  public static ParserConfig fromJson(String json, LoadContext context) {
    return load(TypraJson.parse(json), context);
  }

  private static Map<String, Object> copyMap(Map<?, ?> source) {
    Map<String, Object> result = new LinkedHashMap<>();
    for (Map.Entry<?, ?> entry : source.entrySet()) {
      result.put(String.valueOf(entry.getKey()), entry.getValue());
    }
    return result;
  }

  private static Object serializeScalar(Object value) {
    if (value instanceof Enum<?> e) return e.name().toLowerCase().replace("_", "-");
    return value;
  }

}
