// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class SessionTrace {
  public static final String SHORTHAND_PROPERTY = null;

  public String version = "1";
  public String runtime = null;
  public String promptyVersion = null;
  public String sessionId = null;
  public List<SessionEvent> events = new ArrayList<>();
  public List<TurnTrace> turns = null;
  public List<Checkpoint> checkpoints = null;
  public List<TrajectoryEvent> trajectory = null;
  public List<SessionFileRef> files = null;
  public List<SessionRef> refs = null;
  public SessionSummary summary = null;

  public SessionTrace() { }

  @SuppressWarnings("unchecked")
  public static SessionTrace load(Object input, LoadContext context) {
    LoadContext ctx = context == null ? new LoadContext() : context;
    Object data = ctx.processInput(input);
    if (!(data instanceof Map<?, ?> map)) {
      return ctx.processOutput(new SessionTrace());
    }
    SessionTrace result = new SessionTrace();
    SessionTrace.loadBaseInto(result, map, ctx);
    return ctx.processOutput(result);
  }

  static void loadBaseInto(SessionTrace result, Map<?, ?> map, LoadContext ctx) {
    if (map.containsKey("version") && map.get("version") != null) {
      result.version = String.valueOf(map.get("version"));
    }
    if (map.containsKey("runtime") && map.get("runtime") != null) {
      result.runtime = String.valueOf(map.get("runtime"));
    }
    if (map.containsKey("promptyVersion") && map.get("promptyVersion") != null) {
      result.promptyVersion = String.valueOf(map.get("promptyVersion"));
    }
    if (map.containsKey("sessionId") && map.get("sessionId") != null) {
      result.sessionId = String.valueOf(map.get("sessionId"));
    }
    if (map.containsKey("events") && map.get("events") != null) {
      result.events = new ArrayList<>();
      if (map.get("events") instanceof Iterable<?> values) {
        int eventsIndex = 0;
        for (Object item : values) {
          result.events.add(SessionEvent.load(item, ctx.at("events").atIndex(eventsIndex++)));
        }
      }
    }
    if (map.containsKey("turns") && map.get("turns") != null) {
      result.turns = new ArrayList<>();
      if (map.get("turns") instanceof Iterable<?> values) {
        int turnsIndex = 0;
        for (Object item : values) {
          result.turns.add(TurnTrace.load(item, ctx.at("turns").atIndex(turnsIndex++)));
        }
      }
    }
    if (map.containsKey("checkpoints") && map.get("checkpoints") != null) {
      result.checkpoints = new ArrayList<>();
      if (map.get("checkpoints") instanceof Iterable<?> values) {
        int checkpointsIndex = 0;
        for (Object item : values) {
          result.checkpoints.add(Checkpoint.load(item, ctx.at("checkpoints").atIndex(checkpointsIndex++)));
        }
      }
    }
    if (map.containsKey("trajectory") && map.get("trajectory") != null) {
      result.trajectory = new ArrayList<>();
      if (map.get("trajectory") instanceof Iterable<?> values) {
        int trajectoryIndex = 0;
        for (Object item : values) {
          result.trajectory.add(TrajectoryEvent.load(item, ctx.at("trajectory").atIndex(trajectoryIndex++)));
        }
      }
    }
    if (map.containsKey("files") && map.get("files") != null) {
      result.files = new ArrayList<>();
      if (map.get("files") instanceof Iterable<?> values) {
        int filesIndex = 0;
        for (Object item : values) {
          result.files.add(SessionFileRef.load(item, ctx.at("files").atIndex(filesIndex++)));
        }
      }
    }
    if (map.containsKey("refs") && map.get("refs") != null) {
      result.refs = new ArrayList<>();
      if (map.get("refs") instanceof Iterable<?> values) {
        int refsIndex = 0;
        for (Object item : values) {
          result.refs.add(SessionRef.load(item, ctx.at("refs").atIndex(refsIndex++)));
        }
      }
    }
    if (map.containsKey("summary") && map.get("summary") != null) {
      result.summary = SessionSummary.load(map.get("summary"), ctx.at("summary"));
    }
  }

  public Map<String, Object> save(SaveContext context) {
    SaveContext ctx = context == null ? new SaveContext() : context;
    SessionTrace obj = ctx.processObject(this);
    Map<String, Object> result = new LinkedHashMap<>();
    obj.saveFields(result, ctx);
    return ctx.processDict(result);
  }

  protected void saveFields(Map<String, Object> result, SaveContext ctx) {
    SessionTrace obj = this;
    if (obj.version != null) result.put("version", serializeScalar(obj.version));
    if (obj.runtime != null) result.put("runtime", serializeScalar(obj.runtime));
    if (obj.promptyVersion != null) result.put("promptyVersion", serializeScalar(obj.promptyVersion));
    if (obj.sessionId != null) result.put("sessionId", serializeScalar(obj.sessionId));
    if (obj.events != null) {
      List<Object> items = new ArrayList<>();
      for (SessionEvent item : obj.events) items.add(item.save(ctx));
      result.put("events", items);
    }
    if (obj.turns != null) {
      List<Object> items = new ArrayList<>();
      for (TurnTrace item : obj.turns) items.add(item.save(ctx));
      result.put("turns", items);
    }
    if (obj.checkpoints != null) {
      List<Object> items = new ArrayList<>();
      for (Checkpoint item : obj.checkpoints) items.add(item.save(ctx));
      result.put("checkpoints", items);
    }
    if (obj.trajectory != null) {
      List<Object> items = new ArrayList<>();
      for (TrajectoryEvent item : obj.trajectory) items.add(item.save(ctx));
      result.put("trajectory", items);
    }
    if (obj.files != null) {
      List<Object> items = new ArrayList<>();
      for (SessionFileRef item : obj.files) items.add(item.save(ctx));
      result.put("files", items);
    }
    if (obj.refs != null) {
      List<Object> items = new ArrayList<>();
      for (SessionRef item : obj.refs) items.add(item.save(ctx));
      result.put("refs", items);
    }
    if (obj.summary != null) result.put("summary", obj.summary.save(ctx));
  }

  public String toYaml() {
    return TypraYaml.stringify(save(new SaveContext()));
  }

  public String toJson() {
    return TypraJson.stringify(save(new SaveContext()));
  }

  public static SessionTrace fromYaml(String yaml) {
    return fromYaml(yaml, new LoadContext());
  }

  public static SessionTrace fromYaml(String yaml, LoadContext context) {
    return load(TypraYaml.parse(yaml), context);
  }

  public static SessionTrace fromJson(String json) {
    return fromJson(json, new LoadContext());
  }

  public static SessionTrace fromJson(String json, LoadContext context) {
    return load(TypraJson.parse(json), context);
  }

  private static Map<String, Object> copyMap(Map<?, ?> source) {
    Map<String, Object> result = new LinkedHashMap<>();
    for (Map.Entry<?, ?> entry : source.entrySet()) {
      result.put(String.valueOf(entry.getKey()), entry.getValue());
    }
    return result;
  }

  private static Object serializeScalar(Object value) {
    if (value instanceof Enum<?> e) return e.name().toLowerCase().replace("_", "-");
    return value;
  }

}
