// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
package com.microsoft.prompty.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ToolContext {
  public static final String SHORTHAND_PROPERTY = null;

  public List<Message> messages = new ArrayList<>();
  public Map<String, Object> metadata = null;

  public ToolContext() { }

  @SuppressWarnings("unchecked")
  public static ToolContext load(Object input, LoadContext context) {
    LoadContext ctx = context == null ? new LoadContext() : context;
    Object data = ctx.processInput(input);
    if (!(data instanceof Map<?, ?> map)) {
      return ctx.processOutput(new ToolContext());
    }
    ToolContext result = new ToolContext();
    ToolContext.loadBaseInto(result, map, ctx);
    return ctx.processOutput(result);
  }
  static void loadBaseInto(ToolContext result, Map<?, ?> map, LoadContext ctx) {
    if (map.containsKey("messages") && map.get("messages") != null) {
      result.messages = ModelCollections.loadList(
          map.get("messages"), "messages", Message.SHORTHAND_PROPERTY, Message::load, ctx);
    }
    if (map.containsKey("metadata") && map.get("metadata") != null) {
      if (map.get("metadata") instanceof Map<?, ?> dict) {
        result.metadata = copyMap(dict);
      }
    }
  }


  public Map<String, Object> save(SaveContext context) {
    SaveContext ctx = context == null ? new SaveContext() : context;
    ToolContext obj = ctx.processObject(this);
    Map<String, Object> result = new LinkedHashMap<>();
    if (obj.messages != null) {
      List<Object> items = new ArrayList<>();
      for (Message item : obj.messages) items.add(item.save(ctx));
      result.put("messages", items);
    }
    if (obj.metadata != null) result.put("metadata", serializeScalar(obj.metadata));
    return ctx.processDict(result);
  }

  public String toYaml() {
    return TypraYaml.stringify(save(new SaveContext()));
  }

  public String toJson() {
    return TypraJson.stringify(save(new SaveContext()));
  }

  public static ToolContext fromYaml(String yaml) {
    return fromYaml(yaml, new LoadContext());
  }

  public static ToolContext fromYaml(String yaml, LoadContext context) {
    return load(TypraYaml.parse(yaml), context);
  }

  public static ToolContext fromJson(String json) {
    return fromJson(json, new LoadContext());
  }

  public static ToolContext fromJson(String json, LoadContext context) {
    return load(TypraJson.parse(json), context);
  }

  private static Map<String, Object> copyMap(Map<?, ?> source) {
    Map<String, Object> result = new LinkedHashMap<>();
    for (Map.Entry<?, ?> entry : source.entrySet()) {
      result.put(String.valueOf(entry.getKey()), entry.getValue());
    }
    return result;
  }

  private static Object serializeScalar(Object value) {
    if (value instanceof Enum<?> e) return e.name().toLowerCase().replace("_", "-");
    return value;
  }

}
