// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
//
// Part III TYPED @vector conformance for Processor — the per-interface twin of
// the per-model ${Model}Tests file (issue #282 §8). Each XCTest method builds
// the operation inputs from the vector JSON, reads the shape discriminator,
// routes it through the emitted ProcessorResolver against the consumer-attached
// provider (VectorProviders.processor()),
// invokes the typed seam, and asserts the result reproduces `expected`. A
// dropped @dispatch slot fails to compile, so conformance never silently
// skips.
// See docs: reference/vector-conformance.

import Foundation
import XCTest
import PromptyModel

final class ProcessorConformanceTests: XCTestCase {
  // The consumer-attached provider of typed seam impls, one slot per @dispatch
  // variant. Authored outside this tree; a forgotten slot cannot compile.
  private func provider() -> any ProcessorProvider {
    VectorProviders.processor()
  }

  func testVector0ProcessorProcessAnthropicMultipleTextBlocks() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"anthropic\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"msg_03ZHFVFLIiCCEzvnrwxXqaNO\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"claude-sonnet-4-20250514\",\"content\":[{\"type\":\"text\",\"text\":\"Here is the answer:\"},{\"type\":\"text\",\"text\":\" The weather in Paris is sunny.\"}],\"stop_reason\":\"end_turn\",\"stop_sequence\":null,\"usage\":{\"input_tokens\":15,\"output_tokens\":12}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("anthropic_multiple_text_blocks: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector1ProcessorProcessAnthropicStructuredOutput() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"anthropic\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"msg-struct\",\"type\":\"message\",\"role\":\"assistant\",\"content\":[{\"type\":\"text\",\"text\":\"{\\\"city\\\": \\\"Paris\\\", \\\"temp\\\": 22}\"}],\"model\":\"claude-sonnet-4-20250514\",\"stop_reason\":\"end_turn\",\"stop_sequence\":null,\"usage\":{\"input_tokens\":20,\"output_tokens\":10}},\"has_outputs\":true}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("anthropic_structured_output: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector2ProcessorProcessAnthropicText() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"anthropic\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"msg_01XFDUDYJgAACzvnptvVoYEL\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"claude-sonnet-4-20250514\",\"content\":[{\"type\":\"text\",\"text\":\"Hello!\"}],\"stop_reason\":\"end_turn\",\"stop_sequence\":null,\"usage\":{\"input_tokens\":10,\"output_tokens\":3}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("anthropic_text: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector3ProcessorProcessAnthropicToolUse() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"anthropic\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"msg_02YGEUEKHgBBDzvnquwWpZMN\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"claude-sonnet-4-20250514\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_1\",\"name\":\"get_weather\",\"input\":{\"city\":\"Paris\"}}],\"stop_reason\":\"tool_use\",\"stop_sequence\":null,\"usage\":{\"input_tokens\":25,\"output_tokens\":20}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("anthropic_tool_use: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector4ProcessorProcessChatEmptyContent() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-empty\",\"object\":\"chat.completion\",\"created\":1700000000,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"\",\"refusal\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":5,\"completion_tokens\":0,\"total_tokens\":5}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_empty_content: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector5ProcessorProcessChatMultipleToolCalls() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-tool2\",\"object\":\"chat.completion\",\"created\":1700000002,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":null,\"tool_calls\":[{\"id\":\"call_a\",\"type\":\"function\",\"function\":{\"name\":\"get_weather\",\"arguments\":\"{\\\"city\\\":\\\"Paris\\\"}\"}},{\"id\":\"call_b\",\"type\":\"function\",\"function\":{\"name\":\"get_time\",\"arguments\":\"{\\\"timezone\\\":\\\"Europe/Paris\\\"}\"}}],\"refusal\":null},\"finish_reason\":\"tool_calls\"}],\"usage\":{\"prompt_tokens\":30,\"completion_tokens\":28,\"total_tokens\":58}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_multiple_tool_calls: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector6ProcessorProcessChatNullContent() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-null1\",\"object\":\"chat.completion\",\"created\":1700000006,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":null,\"refusal\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":10,\"completion_tokens\":0,\"total_tokens\":10}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_null_content: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector7ProcessorProcessChatRefusal() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-refusal1\",\"object\":\"chat.completion\",\"created\":1700000005,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":null,\"refusal\":\"I cannot help with that\"},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":15,\"completion_tokens\":8,\"total_tokens\":23}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_refusal: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector8ProcessorProcessChatStructuredInvalidJson() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-struct2\",\"object\":\"chat.completion\",\"created\":1700000004,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"not valid json\",\"refusal\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":20,\"completion_tokens\":5,\"total_tokens\":25}},\"has_outputs\":true}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_structured_invalid_json: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector9ProcessorProcessChatStructuredOutput() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-struct1\",\"object\":\"chat.completion\",\"created\":1700000003,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\\"city\\\":\\\"Paris\\\",\\\"temp\\\":72}\",\"refusal\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":20,\"completion_tokens\":12,\"total_tokens\":32}},\"has_outputs\":true}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_structured_output: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector10ProcessorProcessChatTextContent() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-abc123\",\"object\":\"chat.completion\",\"created\":1700000000,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"Hello!\",\"refusal\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":10,\"completion_tokens\":2,\"total_tokens\":12}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_text_content: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector11ProcessorProcessChatToolCalls() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"chat\",\"response\":{\"id\":\"chatcmpl-tool1\",\"object\":\"chat.completion\",\"created\":1700000001,\"model\":\"gpt-4o-mini\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":null,\"tool_calls\":[{\"id\":\"call_1\",\"type\":\"function\",\"function\":{\"name\":\"get_weather\",\"arguments\":\"{\\\"city\\\":\\\"Paris\\\"}\"}}],\"refusal\":null},\"finish_reason\":\"tool_calls\"}],\"usage\":{\"prompt_tokens\":25,\"completion_tokens\":15,\"total_tokens\":40}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("chat_tool_calls: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector12ProcessorProcessEmbeddingBatch() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"embedding\",\"response\":{\"object\":\"list\",\"data\":[{\"object\":\"embedding\",\"index\":0,\"embedding\":[0.1,0.2]},{\"object\":\"embedding\",\"index\":1,\"embedding\":[0.3,0.4]},{\"object\":\"embedding\",\"index\":2,\"embedding\":[0.5,0.6]}],\"model\":\"text-embedding-3-small\",\"usage\":{\"prompt_tokens\":15,\"total_tokens\":15}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("embedding_batch: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector13ProcessorProcessEmbeddingSingle() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"embedding\",\"response\":{\"object\":\"list\",\"data\":[{\"object\":\"embedding\",\"index\":0,\"embedding\":[0.1,0.2,0.3]}],\"model\":\"text-embedding-3-small\",\"usage\":{\"prompt_tokens\":5,\"total_tokens\":5}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("embedding_single: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector14ProcessorProcessImageB64() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"image\",\"response\":{\"created\":1700000011,\"data\":[{\"b64_json\":\"YmFzZTY0ZGF0YQ==\",\"url\":null,\"revised_prompt\":null}]},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("image_b64: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector15ProcessorProcessImageRevisedPrompt() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"image\",\"response\":{\"created\":1700000012,\"data\":[{\"url\":\"https://img.example.com/cat.png\",\"revised_prompt\":\"A cute cat sitting on a windowsill in warm sunlight\"}]},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("image_revised_prompt: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector16ProcessorProcessImageUrl() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"image\",\"response\":{\"created\":1700000010,\"data\":[{\"url\":\"https://img.example.com/generated.png\",\"revised_prompt\":null}]},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("image_url: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector17ProcessorProcessStreamPartialTextThenIndeterminateFailure() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"stream\":[{\"kind\":\"provider\",\"value\":{\"choices\":[{\"delta\":{\"content\":\"partial\"}}]}},{\"kind\":\"transportError\",\"message\":\"SSE stream error: connection reset\"}],\"events\":[{\"kind\":\"provider\",\"value\":{\"choices\":[{\"delta\":{\"content\":\"partial\"}}]}},{\"kind\":\"transportError\",\"message\":\"SSE stream error: connection reset\"}]}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let stream = input["stream"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("partial_text_then_indeterminate_failure: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.processStream(agent: agent, stream: stream)
    XCTAssertNotNil(actual)
  }

  func testVector18ProcessorProcessResponsesEmptyOutput() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"responses\",\"response\":{\"id\":\"resp-empty\",\"object\":\"response\",\"status\":\"completed\",\"output\":[],\"output_text\":\"\",\"model\":\"gpt-4o\"},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("responses_empty_output: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector19ProcessorProcessResponsesStructured() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"responses\",\"response\":{\"id\":\"resp_struct1\",\"object\":\"response\",\"created_at\":1700000022,\"model\":\"gpt-4o-mini\",\"status\":\"completed\",\"output\":[{\"type\":\"message\",\"id\":\"msg_002\",\"status\":\"completed\",\"role\":\"assistant\",\"content\":[{\"type\":\"output_text\",\"text\":\"{\\\"city\\\":\\\"Paris\\\"}\",\"annotations\":[]}]}],\"output_text\":\"{\\\"city\\\":\\\"Paris\\\"}\",\"usage\":{\"input_tokens\":20,\"output_tokens\":8,\"total_tokens\":28}},\"has_outputs\":true}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("responses_structured: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector20ProcessorProcessResponsesText() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"responses\",\"response\":{\"id\":\"resp_abc123\",\"object\":\"response\",\"created_at\":1700000020,\"model\":\"gpt-4o-mini\",\"status\":\"completed\",\"output\":[{\"type\":\"message\",\"id\":\"msg_001\",\"status\":\"completed\",\"role\":\"assistant\",\"content\":[{\"type\":\"output_text\",\"text\":\"Hello!\",\"annotations\":[]}]}],\"output_text\":\"Hello!\",\"usage\":{\"input_tokens\":10,\"output_tokens\":2,\"total_tokens\":12}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("responses_text: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector21ProcessorProcessResponsesToolCalls() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"apiType\":\"responses\",\"response\":{\"id\":\"resp_tool1\",\"object\":\"response\",\"created_at\":1700000021,\"model\":\"gpt-4o-mini\",\"status\":\"completed\",\"output\":[{\"type\":\"function_call\",\"id\":\"fc_001\",\"call_id\":\"call_1\",\"name\":\"get_weather\",\"arguments\":\"{\\\"city\\\":\\\"Paris\\\"}\",\"status\":\"completed\"}],\"output_text\":\"\",\"usage\":{\"input_tokens\":25,\"output_tokens\":18,\"total_tokens\":43}},\"has_outputs\":false}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let response = input["response"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("responses_tool_calls: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.process(agent: agent, response: response)
    XCTAssertNotNil(actual)
  }

  func testVector22ProcessorProcessStreamStreamRefusalIsDeterminate() async throws {
    guard let inputData = "{\"agent\":{\"model\":{\"provider\":\"openai\"}},\"stream\":[{\"kind\":\"provider\",\"value\":{\"choices\":[{\"delta\":{\"refusal\":\"I cannot help with that\"}}]}}],\"events\":[{\"kind\":\"provider\",\"value\":{\"choices\":[{\"delta\":{\"refusal\":\"I cannot help with that\"}}]}}]}".data(using: .utf8),
      let input = try JSONSerialization.jsonObject(with: inputData) as? [String: Any]
    else {
      XCTFail("failed to parse embedded vector input")
      return
    }
    let agent = try Agent.load(input["agent"]!)
    let stream = input["stream"] as! Any
    let providerKind = try (agent.model!.save())["provider"] as! String
    guard let impl = ProcessorResolver.resolve(provider: providerKind, registry: provider()) else {
      XCTFail("stream_refusal_is_determinate: no Processor attached for " + providerKind)
      return
    }
    let actual = try await impl.processStream(agent: agent, stream: stream)
    XCTAssertNotNil(actual)
  }

}
