// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { ReplayMismatch } from "../../../src/model/index";

describe("ReplayMismatch", () => {
  describe("construction", () => {
    it("should create a new instance with defaults", () => {
      const instance = new ReplayMismatch();
      expect(instance).toBeDefined();
    });

    it("should create a new instance with partial initialization", () => {
      const instance = new ReplayMismatch({});
      expect(instance).toBeDefined();
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = ReplayMismatch.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new ReplayMismatch();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
