// <auto-generated by typra-emitter>
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { InvokerError } from "../../../src/model/index";

describe("InvokerError", () => {
  describe("construction", () => {
    it("should create a new instance with defaults", () => {
      const instance = new InvokerError();
      expect(instance).toBeDefined();
    });

    it("should create a new instance with partial initialization", () => {
      const instance = new InvokerError({});
      expect(instance).toBeDefined();
    });
  });

  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "message": "No renderer registered for key: jinja2",\n  "component": "renderer",\n  "key": "jinja2"\n}`;
      const instance = InvokerError.fromJson(json);
      expect(instance).toBeDefined();
      expect(instance.message).toEqual(
        "No renderer registered for key: jinja2",
      );
      expect(instance.component).toEqual("renderer");
      expect(instance.key).toEqual("jinja2");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "message": "No renderer registered for key: jinja2",\n  "component": "renderer",\n  "key": "jinja2"\n}`;
      const instance = InvokerError.fromJson(json);
      const output = instance.toJson();
      const reloaded = InvokerError.fromJson(output);
      expect(reloaded.message).toEqual(instance.message);
      expect(reloaded.component).toEqual(instance.component);
      expect(reloaded.key).toEqual(instance.key);
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `message: "No renderer registered for key: jinja2"\ncomponent: renderer\nkey: jinja2\n`;
      const instance = InvokerError.fromYaml(yaml);
      expect(instance).toBeDefined();
      expect(instance.message).toEqual(
        "No renderer registered for key: jinja2",
      );
      expect(instance.component).toEqual("renderer");
      expect(instance.key).toEqual("jinja2");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `message: "No renderer registered for key: jinja2"\ncomponent: renderer\nkey: jinja2\n`;
      const instance = InvokerError.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = InvokerError.fromYaml(output);
      expect(reloaded.message).toEqual(instance.message);
      expect(reloaded.component).toEqual(instance.component);
      expect(reloaded.key).toEqual(instance.key);
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = InvokerError.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new InvokerError();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
