// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

import Foundation
import XCTest
@testable import PromptyModel

final class OAuthTokenTests: XCTestCase {
  func testJSONRoundTrip1() throws {
    let json = """
{
  "refreshToken": "0.AXoAoffline-refresh-token-value",
  "scope": "https://cognitiveservices.azure.com/.default offline_access"
}
"""
    let instance = try OAuthToken.fromJSON(json)
    XCTAssertEqual((try XCTUnwrap(instance.refreshToken)), "0.AXoAoffline-refresh-token-value")
    XCTAssertEqual((try XCTUnwrap(instance.scope)), "https://cognitiveservices.azure.com/.default offline_access")
    let reloaded = try OAuthToken.fromJSON(try instance.toJSON())
    XCTAssertEqual((try XCTUnwrap(reloaded.refreshToken)), "0.AXoAoffline-refresh-token-value")
    XCTAssertEqual((try XCTUnwrap(reloaded.scope)), "https://cognitiveservices.azure.com/.default offline_access")
  }

  func testYAMLRoundTrip1() throws {
    let yaml = """
refreshToken: 0.AXoAoffline-refresh-token-value
scope: "https://cognitiveservices.azure.com/.default offline_access"

"""
    let instance = try OAuthToken.fromYAML(yaml)
    XCTAssertEqual((try XCTUnwrap(instance.refreshToken)), "0.AXoAoffline-refresh-token-value")
    XCTAssertEqual((try XCTUnwrap(instance.scope)), "https://cognitiveservices.azure.com/.default offline_access")
    let reloaded = try OAuthToken.fromYAML(try instance.toYAML())
    XCTAssertEqual((try XCTUnwrap(reloaded.refreshToken)), "0.AXoAoffline-refresh-token-value")
    XCTAssertEqual((try XCTUnwrap(reloaded.scope)), "https://cognitiveservices.azure.com/.default offline_access")
  }


  func testWireConversion() throws {
    let json = """
{
  "refreshToken": "0.AXoAoffline-refresh-token-value",
  "scope": "https://cognitiveservices.azure.com/.default offline_access"
}
"""
    let instance = try OAuthToken.fromJSON(json)
    let foundryWire = try instance.toWire("foundry")
    XCTAssertNotNil(foundryWire["refresh_token"])
    XCTAssertNil(foundryWire["refreshToken"])
    XCTAssertNotNil(foundryWire["scope"])
    let foundryRestored = try OAuthToken.fromWire("foundry", foundryWire)
    XCTAssertEqual(Set(try foundryRestored.toWire("foundry").keys), Set(foundryWire.keys))
  }
  // Invalid-input test (malformed JSON must be rejected, issue #328 class)
  func testFromJSONInvalid() throws {
    XCTAssertThrowsError(try OAuthToken.fromJSON("{"))
  }

}
